import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = (path: string) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const routerSource = () => source('../src/app/router.tsx')
const adminGateSource = () => source('../src/pages/admin/AdminAccessGate.tsx')
const adminHomeSource = () => source('../src/pages/admin/AdminHomePage.tsx')
const adminShopManageSource = () => source('../src/pages/admin/AdminShopManagePage.tsx')
const adminShopsSource = () => source('../src/pages/admin/AdminShopsPage.tsx')
const adminShopLocationSource = () => source('../src/pages/admin/AdminShopLocationPage.tsx')
const adminShopDraftStoreSource = () => source('../src/pages/admin/AdminShopDraftStore.ts')
const adminRewardsSource = () => source('../src/pages/admin/AdminRewardsPage.tsx')
const adminOutletSource = () => source('../src/pages/admin/adminOutlet.ts')
const adminPageSource = () => source('../src/pages/AdminPage.tsx')
const adminCssSource = () => source('../src/styles/admin-shop.css')
const aitNavigationSource = () => source('../src/shared/ui/ait/AitNavigation.tsx')
const shopsApiSource = () => source('../src/shared/api/shops.ts')
const apiClientSource = () => source('../src/shared/api/client.ts')
const naverMapLoaderSource = () => source('../src/shared/lib/naverMapLoader.ts')
const tdsLayerGuideSource = () => source('../../docs/tds-compatible-ui-layer.md')
const designTokensGuideSource = () => source('../../docs/design-tokens.md')
const eslintConfigSource = () => source('../eslint.config.js')
const packageSource = () => source('../package.json')
const aitAllowlistSource = () => source('../scripts/assert-ait-usage-allowlist.mjs')

test('admin routes are split under a shared access gate', () => {
  const router = routerSource()
  const gate = adminGateSource()
  const outlet = adminOutletSource()

  assert.match(router, /path:\s*'\/admin'/)
  assert.match(router, /element:\s*<AdminAccessGate \/>/)
  assert.match(router, /index:\s*true[\s\S]*<AdminHomePage \/>/)
  assert.match(router, /path:\s*'shops'[\s\S]*<AdminShopManagePage \/>/)
  assert.match(router, /path:\s*'shops\/new'[\s\S]*<AdminShopsPage \/>/)
  assert.match(router, /path:\s*'shops\/:shopId\/edit'[\s\S]*<AdminShopsPage \/>/)
  assert.match(router, /path:\s*'shops\/location'[\s\S]*<AdminShopLocationPage \/>/)
  assert.doesNotMatch(router, /path:\s*'\/admin\/shops'/)
  assert.match(router, /path:\s*'rewards'[\s\S]*<AdminRewardsPage \/>/)
  assert.match(gate, /<Outlet context=\{\{ lockAdmin \}\} \/>/)
  assert.match(gate, /unlockAdminSession/)
  assert.match(gate, /unlockAdminPreview/)
  assert.match(gate, /const unlocked = isAdminUnlocked\(\)/)
  assert.match(gate, /setIsUnlocked\(unlocked\)/)
  assert.match(outlet, /useOutletContext<AdminOutletContext>/)
})

test('admin hub focuses on shop management and point rewards only', () => {
  const home = adminHomeSource()
  const styles = adminCssSource()

  assert.match(home, /to="\/admin\/shops"/)
  assert.match(home, /to="\/admin\/rewards"/)
  assert.doesNotMatch(home, /사장님|셀프|사업자|제보/)
  assert.match(styles, /\.admin-hub-grid/)
  assert.match(styles, /\.admin-hub-card/)
})

test('admin shops route is a standalone TDS-style CRUD screen after role verification', () => {
  const manage = adminShopManageSource()
  const shops = adminShopsSource()
  const location = adminShopLocationSource()
  const draftStore = adminShopDraftStoreSource()
  const aitNavigation = aitNavigationSource()
  const styles = adminCssSource()
  const shopsApi = shopsApiSource()
  const apiClient = apiClientSource()
  const tdsLayerGuide = tdsLayerGuideSource()
  const designTokensGuide = designTokensGuideSource()
  const eslintConfig = eslintConfigSource()
  const packageJson = packageSource()
  const aitAllowlist = aitAllowlistSource()

  assert.doesNotMatch(manage, /AdminPage/)
  assert.doesNotMatch(manage, /useAdminOutlet/)
  assert.doesNotMatch(shops, /AdminPage/)
  assert.doesNotMatch(shops, /useAdminOutlet/)
  assert.match(shops, /AitNavigation/)
  assert.match(manage, /AitNavigation/)
  assert.doesNotMatch(shops, /AitTop/)
  assert.doesNotMatch(shops, /eyebrow/)
  assert.match(manage, /admin-shop-manage-shell/)
  assert.match(styles, /\.admin-shop-manage-shell\.admin-shop-crud-shell\s*\{[\s\S]*padding-bottom:\s*0;/)
  assert.match(manage, /title="매장 관리"/)
  assert.match(shops, /title=\{isEditMode \? '매장 수정' : '매장 등록'\}/)
  assert.doesNotMatch(shops, /admin-shop-screen-title/)
  assert.match(location, /className="route-navigation"[\s\S]*title="주소 검색"/)
  assert.doesNotMatch(location, /renderInToss/)
  assert.match(aitNavigation, /showLogo\?: boolean/)
  assert.match(aitNavigation, /renderInToss\?: boolean/)
  assert.match(aitNavigation, /shouldUseTossNavigation && !renderInToss/)
  assert.match(aitNavigation, /showLogo &&/)
  assert.match(styles, /\.admin-shop-crud-shell\s*\{[\s\S]*padding:\s*0 0 40px;/)
  assert.doesNotMatch(styles, /\.admin-shop-crud-shell \.ait-navigation\s*\{/)
  assert.doesNotMatch(shops, /임시저장/)
  assert.doesNotMatch(shops, /getShops\(\{ page: 0, size: 200 \}\)/)
  assert.match(manage, /keyword: appliedKeyword \|\| undefined/)
  assert.match(manage, /status: statusFilter === 'ALL' \? undefined : statusFilter/)
  assert.match(manage, /admin-shop-summary/)
  assert.match(manage, /totalSummaryQuery\.data\?\.totalElements/)
  assert.match(manage, /activeSummaryQuery\.data\?\.totalElements/)
  assert.doesNotMatch(manage, /filteredShops/)
  assert.match(manage, /SHOP_MANAGE_PAGE_SIZE = 20/)
  assert.match(manage, /page: currentPage/)
  assert.match(manage, /setCurrentPage\(0\)/)
  assert.match(manage, /ShopStatusFilter/)
  assert.match(manage, /statusFilter === 'ALL'/)
  assert.match(manage, /placeholder="매장명 또는 주소 검색"/)
  assert.match(manage, /admin-shop-status-filter/)
  assert.match(manage, /admin-shop-pagination/)
  assert.match(manage, /useNavigate/)
  assert.match(manage, /navigate\(`\$\{location\.pathname\}\$\{location\.search\}`, \{ replace: true, state: null \}\)/)
  assert.doesNotMatch(manage, /queryKey: \['shops', 'admin-shop-summary', appliedKeyword/)
  assert.match(manage, /등록 매장/)
  assert.match(manage, /영업 종료/)
  assert.match(manage, /검색 결과/)
  assert.match(manage, /전체 목록/)
  assert.match(manage, /\{resultLabel\} \{shopsQuery\.data\?\.totalElements \?\? 0\}건/)
  assert.match(manage, /매장 목록을 불러오고 있어요./)
  assert.match(manage, /조건에 맞는 매장이 없어요./)
  assert.match(manage, /매장을 삭제할까요?/)
  assert.match(styles, /grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\);/)
  assert.match(styles, /\.admin-shop-manage-list\s*\{[\s\S]*max-height:\s*min\(520px, 58dvh\);/)
  assert.match(styles, /\.admin-shop-manage-list\s*\{[\s\S]*overflow-y:\s*auto;/)
  assert.match(manage, /이전/)
  assert.match(manage, /다음/)
  assert.match(manage, /검증 필요/)
  assert.match(manage, /영업 종료/)
  assert.match(manage, /to="\/admin\/shops\/new"/)
  assert.match(manage, /to=\{`\/admin\/shops\/\$\{shop\.id\}\/edit`\}/)
  assert.match(manage, /deleteShop/)
  assert.match(manage, /buildShopDeletedNotice/)
  assert.match(manage, /\$\{shopName\} 매장을 삭제했어요\./)
  assert.match(manage, /await deleteShop\(shop\.id\)/)
  assert.doesNotMatch(manage, /window\.confirm/)
  assert.match(manage, /deleteTargetId/)
  assert.match(manage, /admin-shop-delete-confirm/)
  assert.match(manage, /confirmDelete\(shop\)/)
  assert.match(manage, /cancelDelete/)
  assert.match(manage, /매장 등록/)
  assert.match(manage, /수정/)
  assert.match(manage, /삭제/)
  assert.match(shops, /createShop/)
  assert.match(shops, /updateShop/)
  assert.match(shops, /buildShopSavedNotice/)
  assert.match(shops, /\$\{shopName\} 매장을 \$\{isEditMode \? '수정' : '등록'\}했어요\./)
  assert.doesNotMatch(shops, /새 매장을 등록했어요/)
  assert.doesNotMatch(shops, /매장을 수정했어요/)
  assert.match(shops, /updateShopWithImages/)
  assert.match(shops, /getShop\(editingShopId as number\)/)
  assert.match(shops, /buildEditableImageItems/)
  assert.match(shops, /API_BASE_URL/)
  assert.match(shops, /buildShopImageDisplayUrl/)
  assert.match(shops, /aniwhere\.link/)
  assert.match(shops, /\/img\/shop\//)
  assert.match(shops, /\/api\/v1\/shop-images\//)
  assert.match(shops, /buildUpdateImagePayload/)
  assert.match(shops, /editableImageItemToFile/)
  assert.match(shops, /existingGalleryImageIds/)
  assert.match(shops, /response\.headers\.get\('content-type'\)/)
  assert.match(shops, /contentType\.toLowerCase\(\)\.startsWith\('image\/'\)/)
  assert.match(shops, /기존 사진을 불러오지 못했어요. 다시 시도해주세요./)
  assert.match(shops, /failedImageIds/)
  assert.match(shops, /admin-shop-photo-error/)
  assert.match(shops, /사진 확인 필요/)
  assert.match(shops, /replaceGallery/)
  assert.match(shops, /대표사진은 1장 이상 필요해요./)
  assert.match(shops, /getShopSaveErrorMessage/)
  assert.match(shops, /AwsCredentialsProviderChain/)
  assert.match(shops, /Unable to load credentials/)
  assert.doesNotMatch(shops, /이미지 저장소 인증 정보/)
  assert.doesNotMatch(shops, /서버 S3 설정/)
  assert.match(shops, /사진을 저장하지 못했어요. 잠시 후 다시 시도해주세요./)
  assert.match(shops, /from '@aniwhere\/tds-mobile'/)
  assert.match(manage, /from '@aniwhere\/tds-mobile'/)
  assert.match(tdsLayerGuide, /Apps in Toss\/ads\/local 우선 개발에서는 프로젝트 TDS facade를 통해 공식 `@toss\/tds-mobile` 컴포넌트를 먼저 사용한다/)
  assert.match(tdsLayerGuide, /page code는 `@toss\/tds-mobile`을 직접 import하지 않는다/)
  assert.match(eslintConfig, /no-restricted-imports/)
  assert.match(eslintConfig, /@toss\/tds-mobile/)
  assert.match(eslintConfig, /@aniwhere\/tds-mobile/)
  assert.match(packageJson, /assert-ait-usage-allowlist\.mjs/)
  assert.match(aitAllowlist, /allowedAitImportFiles/)
  assert.match(aitAllowlist, /New Ait\* imports are not allowed/)
  assert.match(tdsLayerGuide, /Existing `Ait\*` imports are treated as migration debt/)
  assert.match(tdsLayerGuide, /Route migration should reduce the allowlist over time, starting with `\/intro`/)
  assert.match(tdsLayerGuide, /main` 머지 후 자동으로 반영되는 배포 표면/)
  assert.match(tdsLayerGuide, /모든 client UI PR은 아래 검증을 통과해야 합니다/)
  assert.match(designTokensGuide, /Apps in Toss\/ads\/local 우선 화면은 프로젝트 TDS facade를 통해 공식 `@toss\/tds-mobile` 컴포넌트를 먼저 사용한다/)
  assert.match(shops, /<Toast/)
  assert.match(manage, /<Toast/)
  assert.match(shops, /text=\{notice \?\? ''\}/)
  assert.match(manage, /text=\{notice \?\? ''\}/)
  assert.match(shops, /position="bottom"/)
  assert.match(manage, /position="bottom"/)
  assert.match(shops, /duration=\{SHOP_TOAST_VISIBLE_MS\}/)
  assert.match(manage, /duration=\{SHOP_TOAST_VISIBLE_MS\}/)
  assert.match(shops, /higherThanCTA/)
  assert.match(manage, /higherThanCTA/)
  assert.match(shops, /aria-live="polite"/)
  assert.match(manage, /aria-live="polite"/)
  assert.match(shops, /SHOP_TOAST_VISIBLE_MS = 3000/)
  assert.match(manage, /SHOP_TOAST_VISIBLE_MS = 3000/)
  assert.doesNotMatch(shops, /window\.setTimeout\(\(\) => setNotice\(null\), SHOP_TOAST_VISIBLE_MS\)/)
  assert.doesNotMatch(manage, /window\.setTimeout\(\(\) => setNotice\(null\), SHOP_TOAST_VISIBLE_MS\)/)
  assert.doesNotMatch(shops, /<p className=\{isNoticeError\(notice\) \? 'error-text' : 'success-text'\}/)
  assert.doesNotMatch(shops, /deleteShop/)
  assert.doesNotMatch(shops, /기존 매장 수정/)
  assert.match(shops, /admin-shop-photo-add/)
  assert.doesNotMatch(shops, /<h2>매장 사진<\/h2>/)
  assert.match(shops, /MAX_SHOP_IMAGE_FILES = 7/)
  assert.match(shops, /MAX_SHOP_IMAGE_FILE_SIZE_BYTES = 12 \* 1024 \* 1024/)
  assert.match(shops, /filterSelectableImageFiles/)
  assert.match(shops, /file\.type\.toLowerCase\(\)\.startsWith\('image\/'\)/)
  assert.match(shops, /file\.size <= MAX_SHOP_IMAGE_FILE_SIZE_BYTES/)
  assert.match(shops, /이미지 파일만 추가할 수 있어요./)
  assert.match(shops, /12MB 이하 이미지로 다시 선택해주세요./)
  assert.match(shops, /초과한 \$\{selection\.overflowCount\}장은 제외했어요./)
  assert.match(shops, /pendingFiles\.length}\/\{MAX_SHOP_IMAGE_FILES\}/)
  assert.match(shops, /setPendingFileAsCover/)
  assert.match(shops, /setEditImageItemAsCover/)
  assert.match(shops, /대표 지정/)
  assert.match(shops, /removePendingFile/)
  assert.match(shops, /current\.filter\(\(_, index\) => index !== targetIndex\)/)
  assert.doesNotMatch(shops, /photoCandidateSearchUrl/)
  assert.doesNotMatch(shops, /buildPhotoCandidateSearchUrl/)
  assert.doesNotMatch(shops, /openPhotoCandidateSearch/)
  assert.doesNotMatch(shops, /readClipboardImage/)
  assert.doesNotMatch(shops, /navigator\.clipboard\.read/)
  assert.doesNotMatch(shops, /사진 후보 찾기/)
  assert.doesNotMatch(shops, /클립보드 사진 추가/)
  assert.doesNotMatch(shops, /클립보드 사진을 불러오지 못했습니다/)
  assert.match(shops, /isEditMode \? \(/)
  assert.doesNotMatch(shops, /remoteImageUrl/)
  assert.doesNotMatch(shops, /URL로 추가/)
  assert.doesNotMatch(shops, /getShopPhotoCandidates/)
  assert.doesNotMatch(shops, /photo-candidates/)
  assert.match(shops, /aria-label=\{`\$\{photo\.name\} 사진 제거`\}/)
  assert.match(shops, /onClick=\{\(\) => removePendingFile\(index\)\}/)
  assert.match(shops, /photo\.isCover \? \(/)
  assert.doesNotMatch(shops, /'갤러리'/)
  assert.doesNotMatch(styles, /\.admin-shop-photo-candidate-actions/)
  assert.doesNotMatch(styles, /\.admin-shop-photo-candidate-load/)
  assert.doesNotMatch(styles, /\.admin-shop-photo-candidate-clipboard/)
  assert.match(styles, /\.admin-shop-photo-add,\s*\.admin-shop-photo-card\s*\{[\s\S]*width:\s*78px;[\s\S]*height:\s*78px;/)
  assert.match(styles, /--admin-shop-border-photo:/)
  assert.match(styles, /\.admin-shop-photo-add,\s*\.admin-shop-photo-card\s*\{[\s\S]*border:\s*1px solid var\(--admin-shop-border-photo\);/)
  assert.match(styles, /\.admin-shop-photo-add\s*\{[\s\S]*border-color:\s*var\(--admin-shop-border-photo-strong\);/)
  assert.match(styles, /\.admin-shop-photo-strip\s*\{[\s\S]*scrollbar-width:\s*thin;/)
  assert.match(styles, /\.admin-shop-photo-strip::-webkit-scrollbar-thumb/)
  assert.match(shops, /className="admin-shop-photo-cover-badge"/)
  assert.match(shops, /<span className="admin-shop-photo-cover-badge">대표<\/span>/)
  assert.match(styles, /\.admin-shop-photo-cover-badge\s*\{[\s\S]*top:\s*6px;/)
  assert.match(styles, /\.admin-shop-photo-cover-badge\s*\{[\s\S]*left:\s*6px;/)
  assert.match(styles, /\.admin-shop-photo-cover-action\s*\{[\s\S]*background:\s*var\(--admin-shop-brand-bg-strong\);/)
  assert.match(styles, /@media \(hover: hover\) and \(pointer: fine\)/)
  assert.match(styles, /\.admin-shop-photo-card:hover \.admin-shop-photo-remove/)
  assert.match(styles, /\.admin-shop-photo-card:focus-within \.admin-shop-photo-remove/)
  assert.match(styles, /\.admin-shop-photo-remove\s*\{[\s\S]*width:\s*24px;[\s\S]*height:\s*24px;/)
  assert.match(shops, /validFiles\.slice\(0, nextSlotCount\)/)
  assert.match(shops, /createShopWithImages\(payload, pendingFiles\)/)
  assert.doesNotMatch(shops, /uploadShopPhotos/)
  assert.match(shopsApi, /createShopWithImages\(payload: ShopRequest, files: File\[\]\)/)
  assert.match(shopsApi, /status: params\.status/)
  assert.match(shopsApi, /files\.length === 0/)
  assert.match(shopsApi, /대표 이미지는 최소 1개가 필요합니다/)
  assert.match(shopsApi, /updateShopWithImages/)
  assert.doesNotMatch(shopsApi, /getShopPhotoCandidates/)
  assert.doesNotMatch(shopsApi, /photo-candidates/)
  assert.match(shopsApi, /formData\.set\('replaceGallery', 'true'\)/)
  assert.match(shopsApi, /formData\.append\('existingGalleryImageIds'/)
  assert.match(shopsApi, /requestForm<Shop>\(`\/api\/v1\/shops\/\$\{id\}`, formData, \{ method: 'PUT' \}\)/)
  assert.match(shopsApi, /formData\.set\('coverImage', files\[0\]\)/)
  assert.match(shopsApi, /slice\(1, 7\)[\s\S]*formData\.append\('galleryImages'/)
  assert.match(shopsApi, /payload\.floor != null/)
  assert.match(shopsApi, /payload\.visitTip != null/)
  assert.match(apiClient, /requestForm<T>\(path: string, body: FormData, init\?: RequestInit\)/)
  assert.match(apiClient, /export const API_BASE_URL/)
  assert.match(shops, /매장명/)
  assert.match(shops, /admin-shop-required/)
  assert.match(shops, /aria-label="필수">\*/)
  assert.doesNotMatch(shops, /<em className="admin-shop-required">필수<\/em>/)
  assert.match(shops, /매장명을 입력해주세요/)
  assert.match(shops, /주소 검색으로 위치를 선택해주세요/)
  assert.match(shops, /aria-invalid=\{!!fieldErrors\.name\}/)
  assert.match(shops, /aria-invalid=\{!!fieldErrors\.location\}/)
  assert.match(shops, /navigate\('\/admin\/shops\/location', \{ state: \{ fromAdminShopCreate: true \} \}\)/)
  assert.match(shops, /위치 추가/)
  assert.match(shops, /admin-shop-location-card-row/)
  assert.match(shops, /admin-shop-location-value/)
  assert.match(shops, /admin-shop-location-change/)
  assert.match(shops, /className="admin-shop-location-change"[\s\S]*onClick=\{openLocationSearch\}/)
  assert.doesNotMatch(shops, /선택한 위치를 변경하려면 눌러주세요/)
  assert.doesNotMatch(shops, /위치 확정/)
  assert.doesNotMatch(shops, /geocodeShopAddress/)
  assert.match(shops, /이치방쿠지 취급 매장/)
  assert.doesNotMatch(shops, /일번쿠지 취급/)
  assert.match(shops, /admin-shop-textarea-field/)
  assert.match(styles, /\.admin-shop-textarea-field\s*\{[\s\S]*gap:\s*var\(--ait-space-5\);/)
  assert.match(styles, /\.admin-shop-toggle\s*\{[\s\S]*column-gap:\s*var\(--ait-space-6\);/)
  assert.match(location, /주소 검색/)
  assert.match(location, /검색 결과에서 위치를 선택해주세요/)
  assert.match(location, /판교역로 235/)
  assert.match(location, /geocodeShopAddress/)
  assert.match(location, /writeAdminShopSelectedLocation/)
  assert.match(location, /useLocation/)
  assert.doesNotMatch(location, /useMemo/)
  assert.match(location, /canReturnToShopForm/)
  assert.match(location, /returnToShopForm/)
  assert.match(location, /navigate\(-1\)/)
  assert.match(location, /navigate\('\/admin\/shops\/new', \{ replace: true \}\)/)
  assert.match(draftStore, /sessionStorage/)
  assert.match(draftStore, /pendingShopFiles/)
  assert.match(draftStore, /pendingShopFileCount/)
  assert.match(draftStore, /readPendingAdminShopFileCount/)
  assert.doesNotMatch(shops, /경도\(px\)/)
  assert.doesNotMatch(shops, /위도\(py\)/)
  assert.doesNotMatch(shops, /지역 ID/)
  assert.match(naverMapLoaderSource(), /submodules=geocoder/)
})

test('admin rewards route keeps using the legacy shared console until reward redesign', () => {
  const rewards = adminRewardsSource()
  const adminPage = adminPageSource()

  assert.match(rewards, /<AdminPage initialSection="points" scope="rewards" skipUnlock onLock=\{lockAdmin\} \/>/)
  assert.match(rewards, /useAdminOutlet/)
  assert.match(adminPage, /type AdminPageProps/)
  assert.match(adminPage, /initialSection\?: AdminMobileSection/)
  assert.match(adminPage, /scope\?: AdminPageScope/)
  assert.match(adminPage, /skipUnlock\?: false/)
  assert.match(adminPage, /skipUnlock: true/)
  assert.match(adminPage, /onLock: \(\) => void/)
  assert.match(adminPage, /onLock\?: \(\) => void/)
  assert.match(adminPage, /const showShopSections = scope !== 'rewards'/)
  assert.match(adminPage, /const showPointSections = scope !== 'shops'/)
  assert.match(adminPage, /useState\(skipUnlock \|\| isAdminUnlocked\(\)\)/)
  assert.match(adminPage, /const lockAdmin = \(\) => \{\s*clearAdminSession\(\)\s*setIsUnlocked\(false\)\s*onLock\?\.\(\)\s*\}/)
  assert.match(adminPage, /if \(!isUnlocked\) \{/)
  assert.doesNotMatch(adminPage, /if \(!skipUnlock && !isUnlocked\)/)
})
