import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = (path: string) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const routerSource = () => source('../src/app/router.tsx')
const adminGateSource = () => source('../src/pages/admin/AdminAccessGate.tsx')
const adminHomeSource = () => source('../src/pages/admin/AdminHomePage.tsx')
const adminShopManageSource = () => source('../src/pages/admin/AdminShopManagePage.tsx')
const adminShopsSource = () => source('../src/pages/admin/AdminShopsPage.tsx')
const adminShopLocationSource = () => source('../src/pages/admin/AdminShopLocationPage.tsx')
const adminShopDraftStoreSource = () => source('../src/pages/admin/AdminShopDraftStore.ts')
const adminCssSource = () => source('../src/styles/admin-shop.css')
const appTopNavigationSource = () => source('../src/shared/ui/AppTopNavigation.tsx')
const shopsApiSource = () => source('../src/shared/api/shops.ts')
const adminApiSource = () => source('../src/shared/api/admin.ts')
const apiClientSource = () => source('../src/shared/api/client.ts')
const naverMapLoaderSource = () => source('../src/shared/lib/naverMapLoader.ts')
const tdsLayerGuideSource = () => source('../../docs/tds-compatible-ui-layer.md')
const designTokensGuideSource = () => source('../../docs/design-tokens.md')
const eslintConfigSource = () => source('../eslint.config.js')
const packageSource = () => source('../package.json')
const aitAllowlistSource = () => source('../scripts/assert-ait-usage-allowlist.mjs')

test('admin routes are split under a shared access gate', () => {
  const router = routerSource()
  const gate = adminGateSource()

  assert.match(router, /path:\s*'\/admin'/)
  assert.match(router, /element:\s*routeElement\(<AdminAccessGate \/>/)
  assert.match(router, /index:\s*true[\s\S]*routeElement\(<AdminHomePage \/>/)
  assert.match(router, /path:\s*'shops'[\s\S]*routeElement\(<AdminShopManagePage \/>/)
  assert.match(router, /path:\s*'shops\/new'[\s\S]*routeElement\(<AdminShopsPage \/>/)
  assert.match(router, /path:\s*'shops\/:shopId\/edit'[\s\S]*routeElement\(<AdminShopsPage \/>/)
  assert.match(router, /path:\s*'shops\/location'[\s\S]*routeElement\(<AdminShopLocationPage \/>/)
  assert.doesNotMatch(router, /path:\s*'\/admin\/shops'/)
  assert.doesNotMatch(router, /path:\s*'rewards'/)
  assert.match(gate, /isAdminRole\(readAuthSession\(\)\?\.role\)/)
  assert.match(gate, /<Navigate replace to="\/home" \/>/)
  assert.match(gate, /<Outlet \/>/)
  assert.doesNotMatch(gate, /관리자 코드/)
  assert.doesNotMatch(gate, /unlockAdminSession|unlockAdminPreview|admin-unlock-card|admin-preview-button/)
})

test('admin index is a hub for current and upcoming admin surfaces', () => {
  const router = routerSource()
  const home = adminHomeSource()
  const styles = adminCssSource()

  assert.match(router, /index:\s*true[\s\S]*routeElement\(<AdminHomePage \/>/)
  assert.match(home, /to=\{card\.href\}/)
  assert.match(home, /\/admin\/shops/)
  assert.match(home, /리뷰 검수/)
  assert.match(home, /사용자 관리/)
  assert.match(home, /admin-hub-card-icon/)
  assert.match(home, /admin-hub-card-copy/)
  assert.match(styles, /\.admin-home-shell\.admin-shop-crud-shell\s*\{[\s\S]*padding:\s*0 var\(--ait-space-5\) var\(--ait-space-8\);/)
  assert.match(styles, /\.admin-home-head\s*\{[\s\S]*padding:\s*var\(--ait-space-7\) 0 var\(--ait-space-3\);/)
  assert.match(styles, /\.admin-hub-grid\s*\{[\s\S]*grid-template-columns:\s*1fr;/)
  assert.match(styles, /\.admin-hub-card\s*\{[\s\S]*grid-template-columns:\s*44px minmax\(0, 1fr\);/)
  assert.match(styles, /\.admin-hub-card small\s*\{[\s\S]*overflow-wrap:\s*anywhere;/)
  assert.match(styles, /@media \(min-width: 720px\)[\s\S]*\.admin-hub-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/)
  assert.doesNotMatch(router, /AdminRewardsPage/)
})

test('admin shops route is a standalone TDS-style CRUD screen after role verification', () => {
  const manage = adminShopManageSource()
  const shops = adminShopsSource()
  const location = adminShopLocationSource()
  const draftStore = adminShopDraftStoreSource()
  const appTopNavigation = appTopNavigationSource()
  const styles = adminCssSource()
  const shopsApi = shopsApiSource()
  const apiClient = apiClientSource()
  const tdsLayerGuide = tdsLayerGuideSource()
  const designTokensGuide = designTokensGuideSource()
  const eslintConfig = eslintConfigSource()
  const packageJson = packageSource()
  const aitAllowlist = aitAllowlistSource()

  assert.doesNotMatch(manage, /AdminPage/)
  assert.doesNotMatch(manage, /useAdminOutlet/)
  assert.doesNotMatch(shops, /AdminPage/)
  assert.doesNotMatch(shops, /useAdminOutlet/)
  assert.match(shops, /AppTopNavigation/)
  assert.match(manage, /AppTopNavigation/)
  assert.doesNotMatch(shops, /AitNavigation/)
  assert.doesNotMatch(manage, /AitNavigation/)
  assert.doesNotMatch(shops, /AitTop/)
  assert.doesNotMatch(shops, /eyebrow/)
  assert.match(manage, /admin-shop-manage-shell/)
  assert.match(styles, /\.admin-shop-manage-shell\.admin-shop-crud-shell\s*\{[\s\S]*padding-bottom:\s*0;/)
  assert.match(manage, /title="매장 관리"/)
  assert.match(shops, /title=\{isEditMode \? '매장 수정' : '매장 등록'\}/)
  assert.doesNotMatch(shops, /admin-shop-screen-title/)
  assert.match(location, /className="route-navigation"[\s\S]*title="주소 검색"/)
  assert.doesNotMatch(location, /renderInToss/)
  assert.match(appTopNavigation, /showLogo\?: boolean/)
  assert.match(appTopNavigation, /renderInToss\?: boolean/)
  assert.match(appTopNavigation, /shouldUseTossNavigation && !renderInToss/)
  assert.match(appTopNavigation, /showLogo \?/)
  assert.match(styles, /\.admin-shop-crud-shell\s*\{[\s\S]*padding:\s*0 0 40px;/)
  assert.doesNotMatch(styles, /\.admin-shop-crud-shell \.ait-navigation\s*\{/)
  assert.doesNotMatch(styles, /\.admin-shell\b/)
  assert.doesNotMatch(styles, /\.admin-unlock-card\b/)
  assert.doesNotMatch(styles, /\.admin-unlock-form\b/)
  assert.doesNotMatch(styles, /\.admin-preview-button\b/)
  assert.doesNotMatch(shops, /임시저장/)
  assert.doesNotMatch(shops, /getShops\(\{ page: 0, size: 200 \}\)/)
  assert.match(manage, /keyword: appliedKeyword \|\| undefined/)
  assert.match(manage, /status: statusFilter === 'ALL' \? undefined : statusFilter/)
  assert.match(manage, /admin-shop-summary/)
  assert.match(manage, /totalSummaryQuery\.data\?\.totalElements/)
  assert.match(manage, /activeSummaryQuery\.data\?\.totalElements/)
  assert.doesNotMatch(manage, /filteredShops/)
  assert.match(manage, /SHOP_MANAGE_PAGE_SIZE = 20/)
  assert.match(manage, /page: currentPage/)
  assert.match(manage, /setCurrentPage\(0\)/)
  assert.match(manage, /ShopStatusFilter/)
  assert.match(manage, /statusFilter === 'ALL'/)
  assert.match(manage, /placeholder="매장명 또는 주소 검색"/)
  assert.match(manage, /admin-shop-status-filter/)
  assert.match(manage, /admin-shop-pagination/)
  assert.match(manage, /useNavigate/)
  assert.match(manage, /navigate\(`\$\{location\.pathname\}\$\{location\.search\}`, \{ replace: true, state: null \}\)/)
  assert.doesNotMatch(manage, /queryKey: \['shops', 'admin-shop-summary', appliedKeyword/)
  assert.match(manage, /등록 매장/)
  assert.match(manage, /영업 종료/)
  assert.match(manage, /검색 결과/)
  assert.match(manage, /전체 목록/)
  assert.match(manage, /\{resultLabel\} \{shopsQuery\.data\?\.totalElements \?\? 0\}건/)
  assert.match(manage, /매장 목록을 불러오고 있어요./)
  assert.match(manage, /조건에 맞는 매장이 없어요./)
  assert.match(manage, /매장을 삭제할까요?/)
  assert.match(styles, /grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\);/)
  assert.match(styles, /\.admin-shop-manage-list\s*\{[\s\S]*max-height:\s*min\(520px, 58dvh\);/)
  assert.match(styles, /\.admin-shop-manage-list\s*\{[\s\S]*overflow-y:\s*auto;/)
  assert.match(manage, /이전/)
  assert.match(manage, /다음/)
  assert.match(manage, /검증 필요/)
  assert.match(manage, /영업 종료/)
  assert.match(manage, /navigate\('\/admin\/shops\/new', \{ state: \{ returnTo: '\/admin\/shops' \} \}\)/)
  assert.match(manage, /to=\{`\/admin\/shops\/\$\{shop\.id\}\/edit`\}/)
  assert.match(manage, /deleteShop/)
  assert.match(manage, /buildShopDeletedNotice/)
  assert.match(manage, /\$\{shopName\} 매장을 삭제했어요\./)
  assert.match(manage, /await deleteShop\(shop\.id\)/)
  assert.doesNotMatch(manage, /window\.confirm/)
  assert.match(manage, /deleteTargetId/)
  assert.match(manage, /admin-shop-delete-confirm/)
  assert.match(manage, /confirmDelete\(shop\)/)
  assert.match(manage, /cancelDelete/)
  assert.match(manage, /매장 등록/)
  assert.match(manage, /수정/)
  assert.match(manage, /삭제/)
  assert.match(shops, /createShop/)
  assert.match(shops, /updateShop/)
  assert.match(shops, /getCategories/)
  assert.match(shops, /refetchOnMount: 'always'/)
  assert.match(shops, /queryClient\.invalidateQueries\(\{ queryKey: \['categories'\] \}\)/)
  assert.match(shops, /queryClient\.invalidateQueries\(\{ queryKey: \['shops', 'facets'\] \}\)/)
  assert.match(shops, /getWorks/)
  assert.match(shops, /getShopFacets/)
  assert.match(shops, /includeWorkTypes: true/)
  assert.match(shops, /workTypeFilter/)
  assert.match(shops, /workTypes=\{shopFacetQuery\.data\?\.workTypes \?\? \[\]\}/)
  assert.match(shops, /setWorkTypeFilter/)
  assert.match(shops, /categoryIds: form\.categoryIds/)
  assert.match(shops, /workIds: form\.workIds/)
  assert.match(draftStore, /readJson<Partial<AdminShopDraft>>/)
  assert.match(draftStore, /categoryIds: Array\.isArray\(draft\.categoryIds\) \? draft\.categoryIds : \[\]/)
  assert.match(draftStore, /workIds: Array\.isArray\(draft\.workIds\) \? draft\.workIds : \[\]/)
  assert.match(draftStore, /writeAdminShopDraft\(normalizedDraft\)/)
  assert.match(shops, /CatalogSelectionSection/)
  assert.match(shops, /buildShopSavedNotice/)
  assert.match(shops, /\$\{shopName\} 매장을 \$\{isEditMode \? '수정' : '등록'\}했어요\./)
  assert.doesNotMatch(shops, /새 매장을 등록했어요/)
  assert.doesNotMatch(shops, /매장을 수정했어요/)
  assert.match(shops, /updateShopWithImages/)
  assert.match(shops, /getShop\(editingShopId as number\)/)
  assert.match(shops, /buildEditableImageItems/)
  assert.match(shops, /API_BASE_URL/)
  assert.match(shops, /buildShopImageDisplayUrl/)
  assert.match(shops, /aniwhere\.link/)
  assert.match(shops, /\/img\/shop\//)
  assert.match(shops, /\/api\/v1\/shop-images\//)
  assert.match(shops, /buildUpdateImagePayload/)
  assert.match(shops, /editableImageItemToFile/)
  assert.match(shops, /existingGalleryImageIds/)
  assert.match(shops, /response\.headers\.get\('content-type'\)/)
  assert.match(shops, /contentType\.toLowerCase\(\)\.startsWith\('image\/'\)/)
  assert.match(shops, /기존 사진을 불러오지 못했어요. 다시 시도해주세요./)
  assert.match(shops, /failedImageIds/)
  assert.match(shops, /admin-shop-photo-error/)
  assert.match(shops, /사진 확인 필요/)
  assert.match(shops, /replaceGallery/)
  assert.match(shops, /대표사진은 1장 이상 필요해요./)
  assert.match(shops, /getShopSaveErrorMessage/)
  assert.match(shops, /AwsCredentialsProviderChain/)
  assert.match(shops, /Unable to load credentials/)
  assert.doesNotMatch(shops, /이미지 저장소 인증 정보/)
  assert.doesNotMatch(shops, /서버 S3 설정/)
  assert.match(shops, /사진을 저장하지 못했어요. 잠시 후 다시 시도해주세요./)
  assert.match(shops, /from '@aniwhere\/tds-mobile'/)
  assert.match(manage, /from '@aniwhere\/tds-mobile'/)
  assert.match(tdsLayerGuide, /Apps in Toss WebView, ads, local 테스트를 출시 기준으로 UI를 개발합니다/)
  assert.match(tdsLayerGuide, /page code는 `@toss\/tds-mobile`을 직접 import하지 않는다/)
  assert.match(eslintConfig, /no-restricted-imports/)
  assert.match(eslintConfig, /@toss\/tds-mobile/)
  assert.match(eslintConfig, /@aniwhere\/tds-mobile/)
  assert.match(packageJson, /assert-ait-usage-allowlist\.mjs/)
  assert.match(aitAllowlist, /allowedAitImportFiles/)
  assert.match(aitAllowlist, /new Set\(\[\]\)/)
  assert.match(aitAllowlist, /New Ait\* imports are not allowed/)
  assert.match(tdsLayerGuide, /Existing `Ait\*` imports are treated as migration debt/)
  assert.match(tdsLayerGuide, /Route migration should keep the allowlist empty and use the TDS facades instead/)
  assert.match(tdsLayerGuide, /main` 머지 후 자동으로 반영되는 배포 표면/)
  assert.match(tdsLayerGuide, /모든 client UI PR은 아래 검증을 통과해야 합니다/)
  assert.match(designTokensGuide, /Apps in Toss\/ads\/local 출시 기준 화면은 프로젝트 TDS facade를 통해 공식 `@toss\/tds-mobile` 컴포넌트를 먼저 사용한다/)
  assert.match(shops, /<Toast/)
  assert.match(manage, /<Toast/)
  assert.match(shops, /text=\{notice \?\? ''\}/)
  assert.match(manage, /text=\{notice \?\? ''\}/)
  assert.match(shops, /position="bottom"/)
  assert.match(manage, /position="bottom"/)
  assert.match(shops, /duration=\{SHOP_TOAST_VISIBLE_MS\}/)
  assert.match(manage, /duration=\{SHOP_TOAST_VISIBLE_MS\}/)
  assert.match(shops, /higherThanCTA/)
  assert.match(manage, /higherThanCTA/)
  assert.match(shops, /aria-live="polite"/)
  assert.match(manage, /aria-live="polite"/)
  assert.match(shops, /SHOP_TOAST_VISIBLE_MS = 3000/)
  assert.match(manage, /SHOP_TOAST_VISIBLE_MS = 3000/)
  assert.doesNotMatch(shops, /window\.setTimeout\(\(\) => setNotice\(null\), SHOP_TOAST_VISIBLE_MS\)/)
  assert.doesNotMatch(manage, /window\.setTimeout\(\(\) => setNotice\(null\), SHOP_TOAST_VISIBLE_MS\)/)
  assert.doesNotMatch(shops, /<p className=\{isNoticeError\(notice\) \? 'error-text' : 'success-text'\}/)
  assert.doesNotMatch(shops, /deleteShop/)
  assert.doesNotMatch(shops, /기존 매장 수정/)
  assert.match(shops, /admin-shop-photo-add/)
  assert.doesNotMatch(shops, /<h2>매장 사진<\/h2>/)
  assert.match(shops, /MAX_SHOP_IMAGE_FILES = 7/)
  assert.match(shops, /MAX_SHOP_IMAGE_FILE_SIZE_BYTES = 12 \* 1024 \* 1024/)
  assert.match(shops, /filterSelectableImageFiles/)
  assert.match(shops, /file\.type\.toLowerCase\(\)\.startsWith\('image\/'\)/)
  assert.match(shops, /file\.size <= MAX_SHOP_IMAGE_FILE_SIZE_BYTES/)
  assert.match(shops, /이미지 파일만 추가할 수 있어요./)
  assert.match(shops, /12MB 이하 이미지로 다시 선택해주세요./)
  assert.match(shops, /초과한 \$\{selection\.overflowCount\}장은 제외했어요./)
  assert.match(shops, /pendingFiles\.length}\/\{MAX_SHOP_IMAGE_FILES\}/)
  assert.match(shops, /setPendingFileAsCover/)
  assert.match(shops, /setEditImageItemAsCover/)
  assert.match(shops, /대표 지정/)
  assert.match(shops, /removePendingFile/)
  assert.match(shops, /current\.filter\(\(_, index\) => index !== targetIndex\)/)
  assert.doesNotMatch(shops, /photoCandidateSearchUrl/)
  assert.doesNotMatch(shops, /buildPhotoCandidateSearchUrl/)
  assert.doesNotMatch(shops, /openPhotoCandidateSearch/)
  assert.doesNotMatch(shops, /readClipboardImage/)
  assert.doesNotMatch(shops, /navigator\.clipboard\.read/)
  assert.doesNotMatch(shops, /사진 후보 찾기/)
  assert.doesNotMatch(shops, /클립보드 사진 추가/)
  assert.doesNotMatch(shops, /클립보드 사진을 불러오지 못했습니다/)
  assert.match(shops, /isEditMode \? \(/)
  assert.doesNotMatch(shops, /remoteImageUrl/)
  assert.doesNotMatch(shops, /URL로 추가/)
  assert.doesNotMatch(shops, /getShopPhotoCandidates/)
  assert.doesNotMatch(shops, /photo-candidates/)
  assert.match(shops, /aria-label=\{`\$\{photo\.name\} 사진 제거`\}/)
  assert.match(shops, /onClick=\{\(\) => removePendingFile\(index\)\}/)
  assert.match(shops, /photo\.isCover \? \(/)
  assert.doesNotMatch(shops, /'갤러리'/)
  assert.doesNotMatch(styles, /\.admin-shop-photo-candidate-actions/)
  assert.doesNotMatch(styles, /\.admin-shop-photo-candidate-load/)
  assert.doesNotMatch(styles, /\.admin-shop-photo-candidate-clipboard/)
  assert.match(styles, /\.admin-shop-photo-add,\s*\.admin-shop-photo-card\s*\{[\s\S]*width:\s*78px;[\s\S]*height:\s*78px;/)
  assert.match(styles, /--admin-shop-border-photo:/)
  assert.match(styles, /\.admin-shop-photo-add,\s*\.admin-shop-photo-card\s*\{[\s\S]*border:\s*1px solid var\(--admin-shop-border-photo\);/)
  assert.match(styles, /\.admin-shop-photo-add\s*\{[\s\S]*border-color:\s*var\(--admin-shop-border-photo-strong\);/)
  assert.match(styles, /\.admin-shop-photo-strip\s*\{[\s\S]*scrollbar-width:\s*thin;/)
  assert.match(styles, /\.admin-shop-photo-strip::-webkit-scrollbar-thumb/)
  assert.match(shops, /className="admin-shop-photo-cover-badge"/)
  assert.match(shops, /<span className="admin-shop-photo-cover-badge">대표<\/span>/)
  assert.match(styles, /\.admin-shop-photo-cover-badge\s*\{[\s\S]*top:\s*6px;/)
  assert.match(styles, /\.admin-shop-photo-cover-badge\s*\{[\s\S]*left:\s*6px;/)
  assert.match(styles, /\.admin-shop-photo-cover-action\s*\{[\s\S]*background:\s*var\(--admin-shop-brand-bg-strong\);/)
  assert.match(styles, /@media \(hover: hover\) and \(pointer: fine\)/)
  assert.match(styles, /\.admin-shop-photo-card:hover \.admin-shop-photo-remove/)
  assert.match(styles, /\.admin-shop-photo-card:focus-within \.admin-shop-photo-remove/)
  assert.match(styles, /\.admin-shop-photo-remove\s*\{[\s\S]*width:\s*24px;[\s\S]*height:\s*24px;/)
  assert.match(shops, /validFiles\.slice\(0, nextSlotCount\)/)
  assert.match(shops, /createShopWithImages\(payload, pendingFiles\)/)
  assert.doesNotMatch(shops, /uploadShopPhotos/)
  assert.match(shopsApi, /createShopWithImages\(payload: ShopRequest, files: File\[\]\)/)
  assert.match(shopsApi, /status: params\.status/)
  assert.match(shopsApi, /files\.length === 0/)
  assert.match(shopsApi, /대표 이미지는 최소 1개가 필요합니다/)
  assert.match(shopsApi, /updateShopWithImages/)
  assert.doesNotMatch(shopsApi, /getShopPhotoCandidates/)
  assert.doesNotMatch(shopsApi, /photo-candidates/)
  assert.match(shopsApi, /formData\.set\('replaceGallery', 'true'\)/)
  assert.match(shopsApi, /formData\.append\('existingGalleryImageIds'/)
  assert.match(shopsApi, /requestForm<Shop>\(`\/api\/v1\/shops\/\$\{id\}`, formData, \{ method: 'PUT' \}\)/)
  assert.match(shopsApi, /formData\.set\('coverImage', files\[0\]\)/)
  assert.match(shopsApi, /slice\(1, 7\)[\s\S]*formData\.append\('galleryImages'/)
  assert.match(shopsApi, /payload\.floor != null/)
  assert.match(shopsApi, /payload\.visitTip != null/)
  assert.match(apiClient, /requestForm<T>\(path: string, body: FormData, init\?: ApiRequestInit\)/)
  assert.match(apiClient, /export const API_BASE_URL/)
  assert.match(shops, /매장명/)
  assert.match(shops, /admin-shop-required/)
  assert.match(shops, /aria-label="필수">\*/)
  assert.doesNotMatch(shops, /<em className="admin-shop-required">필수<\/em>/)
  assert.match(shops, /매장명을 입력해주세요/)
  assert.match(shops, /주소 검색으로 위치를 선택해주세요/)
  assert.match(shops, /aria-invalid=\{!!fieldErrors\.name\}/)
  assert.match(shops, /aria-invalid=\{!!fieldErrors\.location\}/)
  assert.match(shops, /navigate\('\/admin\/shops\/location', \{[\s\S]*state: \{[\s\S]*returnTo: isEditMode && editingShopId != null \? `\/admin\/shops\/\$\{editingShopId\}\/edit` : '\/admin\/shops\/new',[\s\S]*shopManageReturnTo: shouldReturnToShopManage \? returnTo : undefined,[\s\S]*\},[\s\S]*\}\)/)
  assert.match(shops, /위치 추가/)
  assert.match(shops, /admin-shop-location-card-row/)
  assert.match(shops, /admin-shop-location-value/)
  assert.match(shops, /admin-shop-location-change/)
  assert.match(shops, /className="admin-shop-location-change"[\s\S]*onClick=\{openLocationSearch\}/)
  assert.doesNotMatch(shops, /선택한 위치를 변경하려면 눌러주세요/)
  assert.doesNotMatch(shops, /위치 확정/)
  assert.doesNotMatch(shops, /geocodeShopAddress/)
  assert.match(shops, /admin-shop-textarea-field/)
  assert.match(styles, /\.admin-shop-textarea-field\s*\{[\s\S]*gap:\s*var\(--ait-space-5\);/)
  assert.match(styles, /\.admin-shop-toggle\s*\{[\s\S]*column-gap:\s*var\(--ait-space-6\);/)
  assert.match(location, /주소 검색/)
  assert.match(location, /검색 결과에서 위치를 선택해주세요/)
  assert.match(location, /판교역로 235/)
  assert.match(location, /geocodeShopAddress/)
  assert.match(location, /writeAdminShopSelectedLocation/)
  assert.match(location, /useLocation/)
  assert.doesNotMatch(location, /useMemo/)
  assert.match(location, /const returnTo = locationState\?\.returnTo \?\? '\/admin\/shops\/new'/)
  assert.match(location, /returnToShopForm/)
  assert.match(location, /navigate\(returnTo, \{ replace: true, state: returnState \}\)/)
  assert.doesNotMatch(location, /navigate\(-1\)/)
  assert.match(draftStore, /sessionStorage/)
  assert.match(draftStore, /pendingShopFiles/)
  assert.match(draftStore, /pendingShopFileCount/)
  assert.match(draftStore, /readPendingAdminShopFileCount/)
  assert.doesNotMatch(shops, /경도\(px\)/)
  assert.doesNotMatch(shops, /위도\(py\)/)
  assert.doesNotMatch(shops, /지역 ID/)
  assert.match(naverMapLoaderSource(), /submodules=geocoder/)
})

test('legacy admin rewards route is removed from the active router', () => {
  const router = routerSource()

  assert.doesNotMatch(router, /AdminRewardsPage/)
  assert.doesNotMatch(router, /path:\s*'rewards'/)
})

test('admin API no longer keeps local shop photo storage fallback', () => {
  const adminApi = adminApiSource()
  const shopsApi = shopsApiSource()

  assert.doesNotMatch(adminApi, /SHOP_PHOTOS_STORAGE_KEY/)
  assert.doesNotMatch(adminApi, /getShopPhotos/)
  assert.doesNotMatch(adminApi, /uploadShopPhotos/)
  assert.doesNotMatch(adminApi, /removeShopPhoto/)
  assert.doesNotMatch(adminApi, /AdminShopPhoto/)
  assert.match(shopsApi, /formData\.set\('coverImage'/)
  assert.match(shopsApi, /formData\.append\('galleryImages'/)
})

test('admin shop primary buttons keep rounded block TDS button shape', () => {
  const manage = adminShopManageSource()
  const shops = adminShopsSource()

  assert.match(manage, /<Button\s+className="admin-shop-create-button"\s+display="block"[\s\S]*navigate\('\/admin\/shops\/new', \{ state: \{ returnTo: '\/admin\/shops' \} \}\)/)
  assert.doesNotMatch(manage, /<Button display="full" type="button" onClick=\{\(\) => navigate\('\/admin\/shops\/new'\)\}>/)
  assert.match(shops, /<Button\s+className="admin-shop-submit-button"\s+display="block"[\s\S]*type="submit"/)
  assert.doesNotMatch(shops, /<Button display="full" disabled=\{saveShopMutation\.isPending \|\| editShopQuery\.isLoading\} type="submit">/)
})

test('admin shop create and edit use a SearchField plus ListRow work selector', () => {
  const shops = adminShopsSource()
  const styles = adminCssSource()

  assert.match(shops, /import \{ Badge, Button, ListRow, SearchField, Toast \} from '@aniwhere\/tds-mobile'/)
  assert.match(shops, /WorkCatalogSearchSelectionSection/)
  assert.match(shops, /WorkTypeFilterSection/)
  assert.match(shops, /<WorkTypeFilterSection[\s\S]*selectedWorkType=\{workTypeFilter\}[\s\S]*workTypes=\{shopFacetQuery\.data\?\.workTypes \?\? \[\]\}[\s\S]*onChange=\{setWorkTypeFilter\}/)
  assert.match(shops, /aria-label="작품유형"/)
  assert.match(shops, /<strong>작품유형<\/strong>/)
  assert.doesNotMatch(shops, /작품유형 필터/)
  assert.match(shops, /admin-shop-work-type-options/)
  assert.match(shops, /admin-shop-catalog-option admin-shop-work-type-option/)
  assert.doesNotMatch(styles, /\.admin-shop-work-type-chip/)
  assert.match(shops, /workSearchQuery/)
  assert.match(shops, /getMatchingWorkOptions/)
  assert.match(shops, /compactSearchText/)
  assert.match(shops, /hasKoreanText/)
  assert.match(shops, /getWorkSearchFields/)
  assert.match(shops, /getHighlightedWorkNameParts/)
  assert.match(shops, /admin-shop-work-search-combobox/)
  assert.match(shops, /admin-shop-work-suggestion-panel/)
  assert.match(shops, /selectedOptions\.length > 0[\s\S]*admin-shop-selected-work-list[\s\S]*<SearchField/)
  assert.match(shops, /\{!isLoading && !isError && options\.length > 0 && hasSearchableQuery \?/)
  assert.match(shops, /<SearchField[\s\S]*className="admin-shop-work-search-field"/)
  assert.match(shops, /<SearchField[\s\S]*style=\{\{ padding: 0 \}\}/)
  assert.match(shops, /<ListRow[\s\S]*className="admin-shop-work-suggestion-row"/)
  assert.match(shops, /right=\{[\s\S]*<Badge className="admin-shop-work-suggestion-selected-badge" color="blue" size="small" variant="weak">[\s\S]*선택됨/)
  assert.match(shops, /data-selected=\{selected \? 'true' : undefined\}/)
  assert.match(shops, /<mark className="admin-shop-work-suggestion-highlight"/)
  assert.doesNotMatch(shops, /className="admin-shop-work-suggestion-button"[\s\S]{0,240}<small>/)
  assert.doesNotMatch(shops, /getWorkSearchSubtitle/)
  assert.doesNotMatch(shops, /aria-selected=\{selected\}/)
  assert.doesNotMatch(shops, /isLatinSearchQuery/)
  assert.doesNotMatch(shops, /titleEnglish/)
  assert.doesNotMatch(shops, /titleRomaji/)
  assert.match(shops, /admin-shop-selected-work-list/)
  assert.doesNotMatch(shops, /getPopularWorkOptions/)
  assert.doesNotMatch(shops, /admin-shop-work-panel-title/)
  assert.doesNotMatch(shops, /admin-shop-work-suggestion-rank/)
  assert.doesNotMatch(shops, /admin-shop-work-option-row/)
  assert.doesNotMatch(shops, /title="취급 작품"[\s\S]*<CatalogSelectionSection/)
  assert.match(styles, /\.admin-shop-work-search-shell/)
  assert.match(styles, /\.admin-shop-work-search-combobox/)
  assert.match(styles, /\.admin-shop-work-suggestion-panel/)
  assert.match(styles, /\.admin-shop-work-suggestion-row/)
  assert.match(styles, /margin-top:\s*-1px/)
  assert.match(styles, /border-top:\s*0/)
  assert.match(styles, /\.admin-shop-work-suggestion-row:not\(:last-child\)/)
  assert.match(styles, /\.admin-shop-work-suggestion-highlight/)
  assert.match(styles, /padding:\s*0/)
  assert.doesNotMatch(styles, /css-1k7tx0|css-12c4skh/)
  assert.match(styles, /\.admin-shop-work-suggestion-selected-badge/)
  assert.match(styles, /\.admin-shop-work-suggestion-row\[data-selected='true'\]/)
  assert.match(styles, /flex-wrap:\s*wrap/)
  assert.match(styles, /\.admin-shop-selected-work-chip span:last-child/)
  assert.doesNotMatch(styles, /\.admin-shop-work-panel-title/)
  assert.doesNotMatch(styles, /\.admin-shop-work-suggestion-rank/)
  assert.doesNotMatch(styles, /\.admin-shop-work-option-row/)
})

test('admin shop editor title sits above the photo strip', () => {
  const shops = adminShopsSource()
  const styles = adminCssSource()

  assert.match(shops, /<div className="admin-shop-editor-heading">[\s\S]*<h1>\{isEditMode \? '매장 수정' : '매장 등록'\}<\/h1>[\s\S]*<section className="admin-shop-editor-section admin-shop-photo-section">/)
  assert.match(styles, /\.admin-shop-editor-heading/)
})

test('admin location selection assigns a matching regionId from region catalog hints', () => {
  const location = adminShopLocationSource()

  assert.match(location, /getRegions/)
  assert.match(location, /matchRegionIdForLocation/)
  assert.match(location, /regionsQuery\.data/)
  assert.match(location, /query/)
  assert.match(location, /candidate\.roadAddress/)
  assert.match(location, /candidate\.jibunAddress/)
  assert.match(location, /\[\.\.\.regions\]\.sort/)
  assert.match(location, /return rightLength - leftLength/)
  assert.match(location, /regionId: matchedRegionId/)
})

test('admin shop editor returns to the existing manage history entry after save', () => {
  const manage = adminShopManageSource()
  const shops = adminShopsSource()
  const location = adminShopLocationSource()
  const draftStore = adminShopDraftStoreSource()

  assert.match(draftStore, /ADMIN_SHOP_MANAGE_NOTICE_STORAGE_KEY/)
  assert.match(draftStore, /readAdminShopManageNotice/)
  assert.match(draftStore, /writeAdminShopManageNotice/)
  assert.match(draftStore, /clearAdminShopManageNotice/)
  assert.match(manage, /readAdminShopManageNotice/)
  assert.match(manage, /clearAdminShopManageNotice/)
  assert.match(manage, /navigate\('\/admin\/shops\/new', \{ state: \{ returnTo: '\/admin\/shops' \} \}\)/)
  assert.match(manage, /to=\{`\/admin\/shops\/\$\{shop\.id\}\/edit`\}[\s\S]*state=\{\{ returnTo: '\/admin\/shops' \}\}/)
  assert.match(shops, /useLocation/)
  assert.match(shops, /const shouldReturnToShopManage = returnTo === '\/admin\/shops'/)
  assert.match(shops, /writeAdminShopManageNotice\(savedNotice\)[\s\S]*navigate\(-1\)/)
  assert.match(shops, /navigate\('\/admin\/shops', \{[\s\S]*replace: true,[\s\S]*state: \{ notice: savedNotice \},[\s\S]*\}\)/)
  assert.match(shops, /const handleBackToShopManage = \(\) => \{[\s\S]*navigate\(-1\)[\s\S]*navigate\('\/admin\/shops', \{ replace: true \}\)/)
  assert.match(shops, /shopManageReturnTo: shouldReturnToShopManage \? returnTo : undefined/)
  assert.match(location, /shopManageReturnTo\?: string/)
  assert.match(location, /const returnState = locationState\?\.shopManageReturnTo/)
  assert.match(location, /navigate\(returnTo, \{ replace: true, state: returnState \}\)/)
})
