import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = (path: string) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const routerSource = () => source('../src/app/router.tsx')
const adminGateSource = () => source('../src/pages/admin/AdminAccessGate.tsx')
const adminHomeSource = () => source('../src/pages/admin/AdminHomePage.tsx')
const adminShopManageSource = () => source('../src/pages/admin/AdminShopManagePage.tsx')
const adminShopsSource = () => source('../src/pages/admin/AdminShopsPage.tsx')
const adminShopLocationSource = () => source('../src/pages/admin/AdminShopLocationPage.tsx')
const adminShopDraftStoreSource = () => source('../src/pages/admin/AdminShopDraftStore.ts')
const adminRewardsSource = () => source('../src/pages/admin/AdminRewardsPage.tsx')
const adminOutletSource = () => source('../src/pages/admin/adminOutlet.ts')
const adminPageSource = () => source('../src/pages/AdminPage.tsx')
const adminCssSource = () => source('../src/styles/admin-shop.css')
const aitNavigationSource = () => source('../src/shared/ui/ait/AitNavigation.tsx')
const shopsApiSource = () => source('../src/shared/api/shops.ts')
const apiClientSource = () => source('../src/shared/api/client.ts')
const naverMapLoaderSource = () => source('../src/shared/lib/naverMapLoader.ts')

test('admin routes are split under a shared access gate', () => {
  const router = routerSource()
  const gate = adminGateSource()
  const outlet = adminOutletSource()

  assert.match(router, /path:\s*'\/admin'/)
  assert.match(router, /path:\s*'\/admin\/shops'[\s\S]*<AdminShopManagePage \/>/)
  assert.match(router, /path:\s*'\/admin\/shops\/new'[\s\S]*<AdminShopsPage \/>/)
  assert.match(router, /path:\s*'\/admin\/shops\/:shopId\/edit'[\s\S]*<AdminShopsPage \/>/)
  assert.match(router, /path:\s*'\/admin\/shops\/location'[\s\S]*<AdminShopLocationPage \/>/)
  assert.match(router, /element:\s*<AdminAccessGate \/>/)
  assert.match(router, /index:\s*true[\s\S]*<AdminHomePage \/>/)
  assert.match(router, /path:\s*'rewards'[\s\S]*<AdminRewardsPage \/>/)
  assert.match(gate, /<Outlet context=\{\{ lockAdmin \}\} \/>/)
  assert.match(gate, /unlockAdminSession/)
  assert.match(gate, /unlockAdminPreview/)
  assert.match(gate, /const unlocked = isAdminUnlocked\(\)/)
  assert.match(gate, /setIsUnlocked\(unlocked\)/)
  assert.match(outlet, /useOutletContext<AdminOutletContext>/)
})

test('admin hub focuses on shop management and point rewards only', () => {
  const home = adminHomeSource()
  const styles = adminCssSource()

  assert.match(home, /to="\/admin\/shops"/)
  assert.match(home, /to="\/admin\/rewards"/)
  assert.doesNotMatch(home, /사장님|셀프|사업자|제보/)
  assert.match(styles, /\.admin-hub-grid/)
  assert.match(styles, /\.admin-hub-card/)
})

test('admin shops route is a standalone TDS-style CRUD screen after role verification', () => {
  const manage = adminShopManageSource()
  const shops = adminShopsSource()
  const location = adminShopLocationSource()
  const draftStore = adminShopDraftStoreSource()
  const aitNavigation = aitNavigationSource()
  const styles = adminCssSource()
  const shopsApi = shopsApiSource()
  const apiClient = apiClientSource()

  assert.doesNotMatch(manage, /AdminPage/)
  assert.doesNotMatch(manage, /useAdminOutlet/)
  assert.doesNotMatch(shops, /AdminPage/)
  assert.doesNotMatch(shops, /useAdminOutlet/)
  assert.match(shops, /AitNavigation/)
  assert.match(manage, /AitNavigation/)
  assert.doesNotMatch(shops, /AitTop/)
  assert.doesNotMatch(shops, /eyebrow/)
  assert.match(manage, /title="매장 관리"/)
  assert.match(shops, /title=\{isEditMode \? '매장 수정' : '매장 등록'\}/)
  assert.doesNotMatch(shops, /admin-shop-screen-title/)
  assert.match(location, /className="route-navigation"[\s\S]*title="주소 검색"/)
  assert.doesNotMatch(location, /renderInToss/)
  assert.match(aitNavigation, /showLogo\?: boolean/)
  assert.match(aitNavigation, /renderInToss\?: boolean/)
  assert.match(aitNavigation, /shouldUseTossNavigation && !renderInToss/)
  assert.match(aitNavigation, /showLogo &&/)
  assert.match(styles, /\.admin-shop-crud-shell\s*\{[\s\S]*padding:\s*0 0 40px;/)
  assert.doesNotMatch(styles, /\.admin-shop-crud-shell \.ait-navigation\s*\{/)
  assert.doesNotMatch(shops, /임시저장/)
  assert.doesNotMatch(shops, /getShops\(\{ page: 0, size: 200 \}\)/)
  assert.match(manage, /keyword: appliedKeyword \|\| undefined/)
  assert.match(manage, /SHOP_MANAGE_PAGE_SIZE = 20/)
  assert.match(manage, /page: currentPage/)
  assert.match(manage, /setCurrentPage\(0\)/)
  assert.match(manage, /ShopStatusFilter/)
  assert.match(manage, /statusFilter === 'ALL'/)
  assert.match(manage, /placeholder="매장명 또는 주소 검색"/)
  assert.match(manage, /admin-shop-status-filter/)
  assert.match(manage, /admin-shop-pagination/)
  assert.match(manage, /전체 매장/)
  assert.match(manage, /영업 종료/)
  assert.match(manage, /총 \{filteredShops\.length\}건/)
  assert.match(styles, /grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\);/)
  assert.match(styles, /\.admin-shop-manage-list\s*\{[\s\S]*max-height:\s*min\(520px, 58dvh\);/)
  assert.match(styles, /\.admin-shop-manage-list\s*\{[\s\S]*overflow-y:\s*auto;/)
  assert.match(manage, /이전/)
  assert.match(manage, /다음/)
  assert.match(manage, /검증 필요/)
  assert.match(manage, /영업 종료/)
  assert.match(manage, /to="\/admin\/shops\/new"/)
  assert.match(manage, /to=\{`\/admin\/shops\/\$\{shop\.id\}\/edit`\}/)
  assert.match(manage, /deleteShop/)
  assert.doesNotMatch(manage, /window\.confirm/)
  assert.match(manage, /deleteTargetId/)
  assert.match(manage, /admin-shop-delete-confirm/)
  assert.match(manage, /confirmDelete\(shop\)/)
  assert.match(manage, /cancelDelete/)
  assert.match(manage, /매장 등록/)
  assert.match(manage, /수정/)
  assert.match(manage, /삭제/)
  assert.match(shops, /createShop/)
  assert.match(shops, /updateShop/)
  assert.match(shops, /updateShopWithImages/)
  assert.match(shops, /getShop\(editingShopId as number\)/)
  assert.match(shops, /buildEditableImageItems/)
  assert.match(shops, /buildUpdateImagePayload/)
  assert.match(shops, /editableImageItemToFile/)
  assert.match(shops, /replaceGallery/)
  assert.match(shops, /대표사진은 최소 1장 유지해주세요/)
  assert.match(shops, /getShopSaveErrorMessage/)
  assert.match(shops, /AwsCredentialsProviderChain/)
  assert.match(shops, /Unable to load credentials/)
  assert.match(shops, /이미지 저장소 인증 정보가 없어 사진을 저장하지 못했습니다/)
  assert.match(shops, /className=\{`admin-shop-toast/)
  assert.match(manage, /className=\{`admin-shop-toast/)
  assert.match(shops, /role="status"/)
  assert.match(manage, /role="status"/)
  assert.match(shops, /SHOP_TOAST_VISIBLE_MS = 2800/)
  assert.match(shops, /window\.setTimeout\(\(\) => setNotice\(null\), SHOP_TOAST_VISIBLE_MS\)/)
  assert.match(manage, /SHOP_TOAST_VISIBLE_MS = 2800/)
  assert.match(manage, /window\.setTimeout\(\(\) => setNotice\(null\), SHOP_TOAST_VISIBLE_MS\)/)
  assert.doesNotMatch(shops, /<p className=\{isNoticeError\(notice\) \? 'error-text' : 'success-text'\}/)
  assert.match(styles, /\.admin-shop-toast\s*\{[\s\S]*position:\s*fixed;/)
  assert.match(styles, /\.admin-shop-toast\s*\{[\s\S]*bottom:\s*calc\(env\(safe-area-inset-bottom, 0px\) \+ 92px\);/)
  assert.match(styles, /\.admin-shop-toast\s*\{[\s\S]*pointer-events:\s*none;/)
  assert.doesNotMatch(shops, /deleteShop/)
  assert.doesNotMatch(shops, /기존 매장 수정/)
  assert.match(shops, /admin-shop-photo-add/)
  assert.doesNotMatch(shops, /<h2>매장 사진<\/h2>/)
  assert.match(shops, /MAX_SHOP_IMAGE_FILES = 7/)
  assert.match(shops, /pendingFiles\.length}\/\{MAX_SHOP_IMAGE_FILES\}/)
  assert.match(shops, /removePendingFile/)
  assert.match(shops, /current\.filter\(\(_, index\) => index !== targetIndex\)/)
  assert.match(shops, /photoCandidateSearchUrl/)
  assert.match(shops, /buildPhotoCandidateSearchUrl/)
  assert.match(shops, /openPhotoCandidateSearch/)
  assert.match(shops, /readClipboardImage/)
  assert.match(shops, /navigator\.clipboard\.read/)
  assert.match(shops, /사진 후보 찾기/)
  assert.match(shops, /클립보드 사진 추가/)
  assert.match(shops, /클립보드 사진을 불러오지 못했습니다/)
  assert.match(shops, /isEditMode \? \(/)
  assert.doesNotMatch(shops, /remoteImageUrl/)
  assert.doesNotMatch(shops, /URL로 추가/)
  assert.doesNotMatch(shops, /getShopPhotoCandidates/)
  assert.doesNotMatch(shops, /photo-candidates/)
  assert.match(shops, /aria-label=\{`\$\{photo\.name\} 사진 제거`\}/)
  assert.match(shops, /onClick=\{\(\) => removePendingFile\(index\)\}/)
  assert.match(shops, /photo\.isCover \? <span>대표사진<\/span> : null/)
  assert.doesNotMatch(shops, /'갤러리'/)
  assert.match(styles, /\.admin-shop-photo-candidate-actions/)
  assert.match(styles, /\.admin-shop-photo-candidate-load/)
  assert.match(styles, /\.admin-shop-photo-candidate-clipboard/)
  assert.match(styles, /\.admin-shop-photo-add,\s*\.admin-shop-photo-card\s*\{[\s\S]*width:\s*78px;[\s\S]*height:\s*78px;/)
  assert.match(styles, /\.admin-shop-photo-add,\s*\.admin-shop-photo-card\s*\{[\s\S]*border:\s*1px solid rgba\(15, 23, 42, 0\.14\);/)
  assert.match(styles, /\.admin-shop-photo-add\s*\{[\s\S]*border-color:\s*rgba\(15, 23, 42, 0\.24\);/)
  assert.match(styles, /\.admin-shop-photo-card span\s*\{[\s\S]*align-self:\s*end;/)
  assert.match(styles, /\.admin-shop-photo-card span\s*\{[\s\S]*justify-self:\s*stretch;/)
  assert.match(styles, /\.admin-shop-photo-card span\s*\{[\s\S]*background:\s*rgba\(78, 89, 104, 0\.86\);/)
  assert.match(styles, /\.admin-shop-photo-card span\s*\{[\s\S]*text-align:\s*center;/)
  assert.match(styles, /\.admin-shop-photo-remove\s*\{[\s\S]*width:\s*24px;[\s\S]*height:\s*24px;/)
  assert.match(shops, /files\.slice\(0, MAX_SHOP_IMAGE_FILES\)/)
  assert.match(shops, /createShopWithImages\(payload, pendingFiles\)/)
  assert.doesNotMatch(shops, /uploadShopPhotos/)
  assert.match(shopsApi, /createShopWithImages\(payload: ShopRequest, files: File\[\]\)/)
  assert.match(shopsApi, /updateShopWithImages/)
  assert.doesNotMatch(shopsApi, /getShopPhotoCandidates/)
  assert.doesNotMatch(shopsApi, /photo-candidates/)
  assert.match(shopsApi, /formData\.set\('replaceGallery', 'true'\)/)
  assert.match(shopsApi, /requestForm<Shop>\(`\/api\/v1\/shops\/\$\{id\}`, formData, \{ method: 'PUT' \}\)/)
  assert.match(shopsApi, /formData\.set\('coverImage', files\[0\]\)/)
  assert.match(shopsApi, /slice\(1, 7\)[\s\S]*formData\.append\('galleryImages'/)
  assert.match(apiClient, /requestForm<T>\(path: string, body: FormData, init\?: RequestInit\)/)
  assert.match(shops, /매장명/)
  assert.match(shops, /admin-shop-required/)
  assert.match(shops, /aria-label="필수">\*/)
  assert.doesNotMatch(shops, /<em className="admin-shop-required">필수<\/em>/)
  assert.match(shops, /매장명은 필수입니다/)
  assert.match(shops, /message\.includes\('필수'\)/)
  assert.match(shops, /주소 검색으로 위치를 선택해주세요/)
  assert.match(shops, /aria-invalid=\{!!fieldErrors\.name\}/)
  assert.match(shops, /aria-invalid=\{!!fieldErrors\.location\}/)
  assert.match(shops, /navigate\('\/admin\/shops\/location', \{ state: \{ fromAdminShopCreate: true \} \}\)/)
  assert.match(shops, /위치 추가/)
  assert.match(shops, /admin-shop-location-card-row/)
  assert.match(shops, /admin-shop-location-value/)
  assert.match(shops, /admin-shop-location-change/)
  assert.match(shops, /className="admin-shop-location-change"[\s\S]*onClick=\{openLocationSearch\}/)
  assert.doesNotMatch(shops, /선택한 위치를 변경하려면 눌러주세요/)
  assert.doesNotMatch(shops, /위치 확정/)
  assert.doesNotMatch(shops, /geocodeShopAddress/)
  assert.match(shops, /이치방쿠지 취급 매장/)
  assert.doesNotMatch(shops, /일번쿠지 취급/)
  assert.match(shops, /admin-shop-textarea-field/)
  assert.match(styles, /\.admin-shop-textarea-field\s*\{[\s\S]*gap:\s*var\(--ait-space-5\);/)
  assert.match(styles, /\.admin-shop-toggle\s*\{[\s\S]*column-gap:\s*var\(--ait-space-6\);/)
  assert.match(location, /주소 검색/)
  assert.match(location, /검색 결과에서 위치를 선택해주세요/)
  assert.match(location, /판교역로 235/)
  assert.match(location, /geocodeShopAddress/)
  assert.match(location, /writeAdminShopSelectedLocation/)
  assert.match(location, /useLocation/)
  assert.match(location, /canReturnToShopForm/)
  assert.match(location, /returnToShopForm/)
  assert.match(location, /navigate\(-1\)/)
  assert.match(location, /navigate\('\/admin\/shops\/new', \{ replace: true \}\)/)
  assert.match(draftStore, /sessionStorage/)
  assert.match(draftStore, /pendingShopFiles/)
  assert.doesNotMatch(shops, /경도\(px\)/)
  assert.doesNotMatch(shops, /위도\(py\)/)
  assert.doesNotMatch(shops, /지역 ID/)
  assert.match(naverMapLoaderSource(), /submodules=geocoder/)
})

test('admin rewards route keeps using the legacy shared console until reward redesign', () => {
  const rewards = adminRewardsSource()
  const adminPage = adminPageSource()

  assert.match(rewards, /<AdminPage initialSection="points" scope="rewards" skipUnlock onLock=\{lockAdmin\} \/>/)
  assert.match(rewards, /useAdminOutlet/)
  assert.match(adminPage, /type AdminPageProps/)
  assert.match(adminPage, /initialSection\?: AdminMobileSection/)
  assert.match(adminPage, /scope\?: AdminPageScope/)
  assert.match(adminPage, /skipUnlock\?: false/)
  assert.match(adminPage, /skipUnlock: true/)
  assert.match(adminPage, /onLock: \(\) => void/)
  assert.match(adminPage, /onLock\?: \(\) => void/)
  assert.match(adminPage, /const showShopSections = scope !== 'rewards'/)
  assert.match(adminPage, /const showPointSections = scope !== 'shops'/)
  assert.match(adminPage, /useState\(skipUnlock \|\| isAdminUnlocked\(\)\)/)
  assert.match(adminPage, /const lockAdmin = \(\) => \{\s*clearAdminSession\(\)\s*setIsUnlocked\(false\)\s*onLock\?\.\(\)\s*\}/)
  assert.match(adminPage, /if \(!isUnlocked\) \{/)
  assert.doesNotMatch(adminPage, /if \(!skipUnlock && !isUnlocked\)/)
})
