import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = (path: string) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const apiTypesSource = () => source('../src/shared/api/types.ts')
const shopsApiSource = () => source('../src/shared/api/shops.ts')
const searchApiSource = () => (fs.existsSync(new URL('../src/shared/api/search.ts', import.meta.url)) ? source('../src/shared/api/search.ts') : '')
const worksApiSource = () => source('../src/shared/api/works.ts')
const shopReviewsApiSource = () => source('../src/shared/api/shopReviews.ts')
const authApiSource = () => source('../src/shared/api/auth.ts')
const usersApiSource = () => source('../src/shared/api/users.ts')
const apiClientSource = () => source('../src/shared/api/client.ts')
const publicTdsSource = () => source('../src/shared/ui/tdsMobile/public.tsx')
const appsInTossTdsSource = () => source('../src/shared/ui/tdsMobile/apps-in-toss.tsx')
const backendContractSource = () => source('../../docs/backend-api-contract.md')

test('client API types expose the current Swagger response models', () => {
  const types = apiTypesSource()

  assert.match(types, /code\?: string/)
  assert.match(types, /export type ShopFacetResponse = \{/)
  assert.match(types, /export type FacetWorkTypeItem = \{/)
  assert.match(types, /workTypes: FacetWorkTypeItem\[\]/)
  assert.match(types, /regionIds\?: number\[\]/)
  assert.match(types, /workIds\?: number\[\]/)
  assert.match(types, /includeRegions\?: boolean/)
  assert.match(types, /authorUserId: number/)
  assert.match(types, /likeCount: number/)
  assert.match(types, /averageRating: number \| null/)
  assert.match(types, /reviewCount: number/)
  assert.match(types, /favoriteCount: number/)
  assert.match(types, /export type ShopSort = 'NEWEST' \| 'REVIEW_COUNT_DESC' \| 'FAVORITE_COUNT_DESC'/)
  assert.match(types, /export type NearbyShopParams = \{[\s\S]*lat: number[\s\S]*lng: number/)
  assert.match(types, /export type FacetSortItem = \{/)
  assert.match(types, /sorts: FacetSortItem\[\]/)
  assert.match(types, /includeSorts\?: boolean/)
  assert.match(types, /export type ShopReview = \{/)
  assert.match(types, /authorEmojiIconFilename: string \| null/)
  assert.match(types, /export type WorkSummary = \{[\s\S]*type\?: WorkType \| null/)
  assert.match(types, /likedByMe: boolean/)
  assert.match(types, /export type UpdateShopReviewPayload = \{[\s\S]*existingImageIds\?: number\[\]/)
  assert.match(types, /export type LoginResult = \{/)
  assert.match(types, /isNewUser: boolean/)
  assert.match(types, /export type UserSummary = \{/)
  assert.match(types, /emojiIconFilename: string \| null/)
  assert.match(types, /role: string/)
  assert.match(types, /export type NicknameAvailabilityResult = \{/)
  assert.match(types, /export type UpdateNicknamePayload = \{[\s\S]*emojiIconFilename\?: string \| null/)
  assert.match(types, /export type UpdateUserRolePayload = \{/)
  assert.match(types, /export type SearchAutocompleteScope = 'shop' \| 'work'/)
  assert.match(types, /export type SearchAutocompleteKind = 'SHOP' \| 'WORK'/)
  assert.match(types, /export type SearchAutocompleteItem = \{/)
  assert.match(types, /label: string/)
  assert.match(types, /shopId: number \| null/)
  assert.match(types, /workId: number \| null/)
  assert.match(types, /export type SearchAutocompleteResponse = \{/)
  assert.doesNotMatch(types, /export type Post = \{/)
  assert.doesNotMatch(types, /export type Comment = \{/)
})

test('client API functions cover Swagger paths added for facets, favorites, auth, users, search, and shop reviews', () => {
  const shops = shopsApiSource()
  const search = searchApiSource()
  const works = worksApiSource()
  const shopReviews = shopReviewsApiSource()
  const auth = authApiSource()
  const users = usersApiSource()
  const client = apiClientSource()

  assert.match(shops, /regionIds:\s*params\.regionIds/)
  assert.match(shops, /categoryIds:\s*params\.categoryIds/)
  assert.match(shops, /workIds:\s*params\.workIds/)
  assert.match(shops, /export function getShopFacets/)
  assert.match(shops, /includeRegions:\s*params\.includeRegions/)
  assert.match(shops, /includeWorkTypes:\s*params\.includeWorkTypes/)
  assert.match(shops, /includeSorts:\s*params\.includeSorts/)
  assert.match(shops, /\/api\/v1\/shops\/facets/)
  assert.match(shops, /export function getNearbyShops/)
  assert.match(shops, /lat:\s*params\.lat/)
  assert.match(shops, /lng:\s*params\.lng/)
  assert.match(shops, /\/api\/v1\/shops\/nearby/)
  assert.match(shops, /export function addFavoriteShop/)
  assert.match(shops, /method:\s*'POST'/)
  assert.match(shops, /export function removeFavoriteShop/)
  assert.match(shops, /method:\s*'DELETE'/)

  assert.match(search, /export function getSearchAutocomplete/)
  assert.match(search, /q:\s*params\.q/)
  assert.match(search, /scope:\s*params\.scope/)
  assert.match(search, /limit:\s*params\.limit/)
  assert.match(search, /request<SearchAutocompleteResponse>\(`\/api\/v1\/search\/autocomplete\$\{query\}`\)/)

  assert.match(works, /export function addFavoriteWork/)
  assert.match(works, /type:\s*params\.type/)
  assert.match(works, /\/api\/v1\/works\/\$\{workId\}\/favorite/)
  assert.match(works, /export function removeFavoriteWork/)

  assert.match(shopReviews, /export function listShopReviews/)
  assert.match(shopReviews, /\/api\/v1\/shops\/\$\{shopId\}\/reviews/)
  assert.match(shopReviews, /export function createShopReview/)
  assert.match(shopReviews, /export function updateShopReview/)
  assert.match(shopReviews, /function reviewMutationQuery/)
  assert.match(shopReviews, /replaceImages:\s*options\?\.replaceImages/)
  assert.match(shopReviews, /existingImageIds:\s*options\?\.existingImageIds/)
  assert.match(shopReviews, /requestForm<ShopReview>\(`\$\{shopReviewPath\(shopId\)\}\$\{query\}`/)
  assert.match(shopReviews, /requestForm<ShopReview>\(`\$\{shopReviewDetailPath\(shopId, reviewId\)\}\$\{query\}`/)
  assert.doesNotMatch(shopReviews, /formData\.append\('rating'/)
  assert.doesNotMatch(shopReviews, /formData\.append\('content'/)
  assert.match(shopReviews, /appendReviewImageFields/)
  assert.match(shopReviews, /export function listMyReviews/)
  assert.match(shopReviews, /\/api\/v1\/users\/me\/reviews/)
  assert.match(shopReviews, /export function deleteShopReview/)
  assert.match(shopReviews, /export function likeShopReview/)
  assert.match(shopReviews, /export function unlikeShopReview/)
  assert.match(shopReviews, /shopReviewDetailPath\(shopId, reviewId\)/)
  assert.match(shopReviews, /\/likes/)
  assert.match(shopReviews, /export function updateShopReviewStatus/)
  assert.doesNotMatch(shopReviews, /\/api\/v1\/posts/)

  assert.match(auth, /export function tossLogin/)
  assert.match(auth, /\/api\/v1\/auth\/toss\/login/)
  assert.match(auth, /request<LoginResult>\('\/api\/v1\/auth\/toss\/login',\s*\{\s*method:\s*'POST'/s)
  assert.match(auth, /export function refreshAuth/)
  assert.match(auth, /export function logout/)

  assert.match(users, /export function getMyProfile/)
  assert.match(users, /export function listMyFavoriteShops/)
  assert.match(users, /\/api\/v1\/users\/me\/favorite-shops/)
  assert.match(users, /export function checkNicknameAvailability/)
  assert.match(users, /export function updateMyNickname/)
  assert.match(users, /export function updateUserRole/)
  assert.match(users, /\/api\/v1\/admin\/users\/\$\{userId\}\/role/)
  assert.match(users, /export function updateUserRole[\s\S]*method:\s*'PATCH'/)
  assert.match(users, /export function listUsers/)

  assert.match(client, /Authorization/)
  assert.match(client, /authToken/)
  assert.match(client, /getStoredAccessToken/)
  assert.match(client, /authToken === undefined \? getStoredAccessToken\(\) : authToken/)
  assert.doesNotMatch(client, /authToken \?\? getStoredAccessToken\(\)/)
})

test('backend API contract notes keep shop facets aligned with deployed Swagger', () => {
  const contract = backendContractSource()

  assert.match(contract, /GET \/api\/v1\/shops\/facets` provides search facet payload \(`regions`, `categories`, `workTypes`, `sorts`\)/)
  assert.match(contract, /accepts optional `includeRegions`, `includeCategories`, `includeWorkTypes`, and `includeSorts`/)
  assert.match(contract, /Current deployed work type facets checked from `GET \/api\/v1\/shops\/facets`: `ANIMATION` \(`애니메이션`\), `GAME` \(`게임`\)/)
  assert.match(contract, /Current deployed category masters checked from `GET \/api\/v1\/categories`: `가챠`, `굿즈`, `제일복권`, `피규어`/)
  assert.match(contract, /GET \/api\/v1\/shops` accepts `sort=NEWEST\|REVIEW_COUNT_DESC\|FAVORITE_COUNT_DESC`/)
  assert.match(contract, /ShopReview` includes `authorEmojiIconFilename`, `likeCount`, and `likedByMe`/)
  assert.match(contract, /PATCH \/api\/v1\/shops\/\{shopId\}\/reviews\/\{reviewId\}` accepts optional `replaceImages`/)
  assert.match(contract, /existingImageIds`/)
  assert.match(contract, /does not expose a review report endpoint yet/)
  assert.match(contract, /GET \/api\/v1\/shops\/nearby` accepts required `lat` and `lng`/)
  assert.match(contract, /GET \/api\/v1\/users\/me\/favorite-shops` returns the authenticated user's favorite `Shop\[\]`/)
  assert.match(contract, /PATCH \/api\/v1\/users\/me\/nickname` accepts optional `emojiIconFilename`/)
  assert.match(contract, /UserSummary` includes optional `emojiIconFilename`/)
  assert.match(contract, /GET \/api\/v1\/search\/autocomplete` accepts required `q` and `scope=shop\|work`/)
  assert.match(contract, /plus optional `limit` defaulting to 8 and capped by the server/)
  assert.match(contract, /SearchAutocompleteItem` returns `label`, `kind=SHOP\|WORK`, and optional `shopId` or `workId`/)
  assert.match(contract, /does not expose `keyword`, selected filter IDs, `status`, `type`, or map bounds/)
})

test('public TDS BottomSheet renders the dimmer only when it can close', () => {
  const publicTds = publicTdsSource()

  assert.match(publicTds, /!disableDimmer && onClose != null/)
  assert.match(publicTds, /<button\b(?=[^>]*className="ait-bottom-sheet-dimmer")(?=[^>]*onClick=\{onClose\})[^>]*\/?>/)
  assert.match(publicTds, /Header: BottomSheetHeader/)
  assert.match(publicTds, /HeaderDescription: BottomSheetHeaderDescription/)
})

test('admin local queue tolerates unavailable storage and empty point API responses', () => {
  const adminApi = source('../src/shared/api/admin.ts')

  assert.match(adminApi, /try \{[\s\S]*window\.localStorage\.setItem\(key, JSON\.stringify\(value\)\)[\s\S]*\} catch \{/)
  assert.match(adminApi, /async function readResponseJson/)
  assert.match(adminApi, /const result = response\.ok \? await readResponseJson\(response\) : null/)
})

test('TDS mobile facade exposes onboarding primitives in public and Apps in Toss builds', () => {
  const publicTds = publicTdsSource()
  const appsInTossTds = appsInTossTdsSource()

  assert.match(publicTds, /export const Asset/)
  assert.match(publicTds, /Image: AssetImage/)
  assert.match(publicTds, /Lottie: AssetLottie/)
  assert.match(publicTds, /\{'\u20A9'\}/)
  assert.match(publicTds, /export const Modal/)
  assert.match(publicTds, /Overlay: ModalOverlay/)
  assert.match(publicTds, /Content: ModalContent/)
  assert.match(publicTds, /export const Menu/)
  assert.match(publicTds, /Trigger: MenuTrigger/)
  assert.match(publicTds, /DropdownItem: MenuDropdownItem/)
  assert.match(publicTds, /handleDropdownClickCapture/)
  assert.match(publicTds, /target\?\.closest\('\[role="menuitem"\], \[role="menuitemcheckbox"\]'\)/)
  assert.match(publicTds, /export const Result/)
  assert.match(publicTds, /Button: ResultButton/)
  assert.match(publicTds, /Icon: AssetIcon/)
  assert.match(publicTds, /export function TextField/)
  assert.match(publicTds, /role=\{readOnly \? 'img' : 'radiogroup'\}/)
  assert.match(publicTds, /role=\{readOnly \? undefined : 'radio'\}/)
  assert.match(publicTds, /aria-checked=\{active\}/)
  assert.match(publicTds, /tabIndex=\{!readOnly && nextValue === Math\.max\(1, roundedValue\) \? 0 : -1\}/)
  assert.doesNotMatch(publicTds, /role=\{readOnly \? 'img' : 'slider'\}/)
  assert.doesNotMatch(publicTds, /aria-valuenow=\{roundedValue\}/)
  assert.match(appsInTossTds, /Asset/)
  assert.match(appsInTossTds, /Menu/)
  assert.match(appsInTossTds, /Modal/)
  assert.match(appsInTossTds, /Result/)
  assert.match(appsInTossTds, /TextField/)
})
