import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const explorePageSource = () => fs.readFileSync(new URL('../src/pages/ExplorePage.tsx', import.meta.url), 'utf8')
const exploreTopSearchSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/ExploreTopSearch.tsx', import.meta.url), 'utf8')
const mapSearchFieldShellSource = () =>
  fs.readFileSync(new URL('../src/shared/ui/MapSearchFieldShell.tsx', import.meta.url), 'utf8')
const searchCopySource = () => fs.readFileSync(new URL('../src/shared/lib/searchCopy.ts', import.meta.url), 'utf8')
const mapQuickChipsSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapQuickChips.tsx', import.meta.url), 'utf8')
const appliedFilterChipsSource = () =>
  fs.readFileSync(new URL('../src/shared/ui/AppliedFilterChips.tsx', import.meta.url), 'utf8')
const mapOverlayControlsSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapOverlayControls.tsx', import.meta.url), 'utf8')
const mapAssistantPanelSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapAssistantPanel.tsx', import.meta.url), 'utf8')
const mapResultsSheetSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapResultsSheet.tsx', import.meta.url), 'utf8')
const mapPeekSheetSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapPeekSheet.tsx', import.meta.url), 'utf8')
const mapDetailSummaryCardSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapDetailSummaryCard.tsx', import.meta.url), 'utf8')
const mapDetailInfoCardSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapDetailInfoCard.tsx', import.meta.url), 'utf8')
const mapDetailMediaSectionSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapDetailMediaSection.tsx', import.meta.url), 'utf8')
const mapDetailSupplementSectionsSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapDetailSupplementSections.tsx', import.meta.url), 'utf8')
const appCssSource = () =>
  [
    '../src/App.css',
    '../src/styles/explore-search.css',
    '../src/styles/admin-shop.css',
  ]
    .map((path) => fs.readFileSync(new URL(path, import.meta.url), 'utf8'))
    .join('\n')
const adminShopCssSource = () => fs.readFileSync(new URL('../src/styles/admin-shop.css', import.meta.url), 'utf8')
const exploreSearchCssSource = () => fs.readFileSync(new URL('../src/styles/explore-search.css', import.meta.url), 'utf8')
const shopMapSource = () => fs.readFileSync(new URL('../src/shared/ui/ShopMap.tsx', import.meta.url), 'utf8')
const shopFiltersSource = () => fs.readFileSync(new URL('../src/shared/lib/shopFilters.ts', import.meta.url), 'utf8')
const shopFacetQuerySource = () =>
  fs.readFileSync(new URL('../src/shared/lib/shopFacetQuery.ts', import.meta.url), 'utf8')

const cssRuleBodies = (css: string, selector: string) => {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const matches = css.matchAll(new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\}`, 'g'))

  return Array.from(matches, (match) => match[1])
}

test('ExplorePage shares the search bar and filter sheet pattern with SearchPage', () => {
  const source = explorePageSource()
  const topSearchSource = exploreTopSearchSource()
  const shellSource = mapSearchFieldShellSource()
  const copySource = searchCopySource()

  assert.match(source, /SearchFilterSheet/)
  assert.match(source, /selectedFilters=\{selectedFilters\}/)
  assert.match(source, /onApplyFilters=\{applyFilters\}/)
  assert.match(source, /<AppTopNavigation/)
  assert.doesNotMatch(source, /title="지도"/)
  assert.match(source, /onBack=\{handleExploreBack\}/)
  assert.doesNotMatch(topSearchSource, /map-search-home-button/)
  assert.doesNotMatch(source, /onHomeClick=/)
  assert.doesNotMatch(topSearchSource, /import \{ SearchField \} from '@aniwhere\/tds-mobile'/)
  assert.doesNotMatch(topSearchSource, /<SearchField/)
  assert.match(topSearchSource, /<div className="map-search-row search-screen-toolrow">/)
  assert.match(topSearchSource, /import \{ MapSearchFieldButton \} from '\.\.\/\.\.\/shared\/ui\/MapSearchFieldShell'/)
  assert.match(topSearchSource, /<MapSearchFieldButton value=\{value\} onClick=\{onSearchClick\}/)
  assert.match(shellSource, /<button className="search-screen-bar map-search-field" type="button" onClick=\{onClick\}>/)
  assert.match(copySource, /SHOP_SEARCH_PLACEHOLDER = '작품, 매장명, 지역으로 검색'/)
  assert.match(shellSource, /SHOP_SEARCH_PLACEHOLDER/)
  assert.match(source, /value=\{currentKeyword\}/)
  assert.doesNotMatch(topSearchSource, /매장, 작품, 지역 검색/)
  assert.match(topSearchSource, /className="search-filter-button map-filter-button"/)
  assert.match(topSearchSource, /aria-label=\{appliedFilterCount > 0 \? `/)
})

test('ExplorePage removes the map hamburger navigation trigger from the top search row', () => {
  const source = explorePageSource()

  assert.doesNotMatch(source, /global-nav-trigger-map/)
  assert.doesNotMatch(source, /<GlobalNavigationMenu triggerClassName="global-nav-trigger global-nav-trigger-map"/)
})

test('ExplorePage binds the filter trigger ref only to the visible top search instance', () => {
  const source = explorePageSource()
  const topSearchSource = exploreTopSearchSource()

  assert.match(source, /<ExploreTopSearch/)
  assert.match(topSearchSource, /ref=\{attachTriggerRef \? filterTriggerRef : null\}/)
  assert.match(source, /const isExploreTopHidden = sheetMode === 'expanded'/)
  assert.match(source, /!isExploreTopHidden \? \(/)
  assert.match(source, /attachTriggerRef\s+filterTriggerRef=\{filterTriggerRef\}/)
  assert.doesNotMatch(source, /attachTriggerRef=\{isListSheetOpen\}/)
  assert.doesNotMatch(source, /const topSearch = \(/)
  assert.doesNotMatch(source, /ref=\{filterTriggerRef\}/)
  assert.doesNotMatch(source, /const renderTopSearch = /)
})

test('ExplorePage removes hidden top controls from interaction when detail is expanded', () => {
  const source = explorePageSource()
  const styles = appCssSource()
  const hiddenRows = cssRuleBodies(styles, '.map-explore-top-hidden .map-search-row')
  const hiddenChips = cssRuleBodies(styles, '.map-explore-top-hidden .map-chip-toolbar')
  const hiddenAreaSearch = cssRuleBodies(styles, '.map-explore-top-hidden .map-area-search-button')

  assert.match(source, /aria-hidden=\{isExploreTopHidden\}/)
  assert.match(source, /!isExploreTopHidden \? \([\s\S]*?<ExploreTopSearch/)
  assert.ok(hiddenRows.some((rule) => /pointer-events:\s*none;/.test(rule)))
  assert.ok(hiddenChips.some((rule) => /pointer-events:\s*none;/.test(rule)))
  assert.ok(hiddenAreaSearch.some((rule) => /pointer-events:\s*none;/.test(rule)))
})

test('ExplorePage extracts map quick chips and overlay controls into focused components', () => {
  const source = explorePageSource()
  const quickChipsSource = mapQuickChipsSource()
  const overlayControlsSource = mapOverlayControlsSource()

  assert.match(source, /<MapQuickChips/)
  assert.match(source, /<MapOverlayControls/)
  assert.match(quickChipsSource, /aria-pressed=\{isActive\}/)
  assert.match(quickChipsSource, /onToggle\(item\.id\)/)
  assert.match(overlayControlsSource, /map-list-fab-list-icon map-control-icon/)
  assert.match(overlayControlsSource, /map-location-target-icon map-control-icon/)
  assert.doesNotMatch(source, /const chipToolbar = \(/)
})

test('Explore location button uses a distinct target icon and transient fallback message', () => {
  const source = explorePageSource()
  const overlayControlsSource = mapOverlayControlsSource()
  const styles = appCssSource()
  const targetIconRules = cssRuleBodies(styles, '.map-location-target-icon')
  const targetIconButtonRules = cssRuleBodies(styles, '.map-location-fab .map-location-target-icon')
  const toastRules = cssRuleBodies(styles, '.map-location-error-toast')

  assert.match(overlayControlsSource, /className="map-location-target-icon map-control-icon"/)
  assert.match(overlayControlsSource, /<circle cx="12" cy="12" r="5"/)
  assert.match(source, /function getLocationErrorMessage\(error: unknown\)/)
  assert.match(source, /showLocationError\(getLocationErrorMessage\(error\)\)/)
  assert.match(source, /viewParam === 'list' \? 'list' : 'map'/)
  assert.match(source, /nearbyRequest \? 'ready' : 'idle'/)
  assert.match(source, /const \[focusMode, setFocusMode\] = useState<FocusMode>\(nearbyRequest \? 'user'/)
  assert.match(overlayControlsSource, /map-location-fab \$\{locationState === 'ready' \? 'map-location-fab-active' : ''\}/)
  assert.match(source, /window\.setTimeout\(\(\) => \{[\s\S]*?setLocationError\(null\)/)
  assert.match(source, /className="map-location-error-toast"/)
  assert.doesNotMatch(source, /map-inline-error map-inline-error-overlay">\{locationError\}/)
  assert.ok(targetIconRules.some((rule) => /stroke:\s*currentcolor;/.test(rule)))
  assert.ok(targetIconButtonRules.some((rule) => /width:\s*24px;/.test(rule) && /height:\s*24px;/.test(rule)))
  assert.ok(toastRules.some((rule) => /pointer-events:\s*none;/.test(rule)))
})

test('ExplorePage extracts the assistant panel into a focused component', () => {
  const source = explorePageSource()
  const assistantPanelSource = mapAssistantPanelSource()

  assert.match(source, /<MapAssistantPanel/)
  assert.match(source, /const isMapAssistantEnabled = false/)
  assert.match(source, /visible=\{isMapAssistantEnabled && !isListSheetOpen && sheetMode !== 'expanded' && sheetMode !== 'review'\}/)
  assert.match(source, /const showAssistantReturn =\s+isMapAssistantEnabled &&/)
  assert.match(assistantPanelSource, /className="map-llm-panel"/)
  assert.match(assistantPanelSource, /messages\.map/)
  assert.match(assistantPanelSource, /suggestions\.map/)
  assert.doesNotMatch(source, /className="map-llm-panel"/)
  assert.doesNotMatch(source, /assistantMessages\.map/)
})

test('MapAssistantPanel announces toggle state and blocks duplicate pending submissions', () => {
  const source = mapAssistantPanelSource()

  assert.match(source, /aria-label=\{open \? 'AI 탐색 닫기' : 'AI 탐색 열기'\}/)
  assert.match(source, /const canSubmitInput = !isPending && input\.trim\(\)\.length > 0/)
  assert.match(source, /if \(isPending\) \{\s*return\s*\}/)
  assert.match(source, /disabled=\{isPending\}/)
  assert.match(source, /disabled=\{!canSubmitInput\}/)
  assert.match(source, /if \(!canSubmitInput\) \{\s*return\s*\}/)
})

test('ExplorePage extracts the list results sheet into a focused component', () => {
  const source = explorePageSource()
  const resultsSheetSource = mapResultsSheetSource()

  assert.match(source, /<MapResultsSheet/)
  assert.match(source, /const isFullListView = routeViewMode === 'list' && selectedShopId == null/)
  assert.match(source, /if \(isFullListView\) \{[\s\S]*?<MapResultsSheet/)
  assert.match(source, /visible=\{isFullListView\}/)
  assert.doesNotMatch(resultsSheetSource, /import \{ BottomSheet \} from '@aniwhere\/tds-mobile'/)
  assert.match(resultsSheetSource, /if \(!visible\) \{\s*return null\s*\}/)
  assert.match(resultsSheetSource, /<section[\s\S]*className="map-results-list-panel"[\s\S]*aria-label="검색 결과"/)
  assert.match(resultsSheetSource, /className="search-result-head"/)
  assert.match(resultsSheetSource, /<strong>매장목록<\/strong>/)
  assert.match(resultsSheetSource, /<small>\{totalShops\}곳<\/small>/)
  assert.doesNotMatch(resultsSheetSource, /aria-labelledby="map-results-list-title"/)
  assert.doesNotMatch(resultsSheetSource, /role="dialog"/)
  assert.match(resultsSheetSource, /visibleShops\.map/)
  assert.match(resultsSheetSource, /getResultCardPhotos/)
  assert.doesNotMatch(resultsSheetSource, /topSearch/)
  assert.doesNotMatch(source, /className="map-results-list-panel"/)
  assert.doesNotMatch(source, /visibleShops\.map\([\s\S]*?<button className="map-results-card"/)
})

test('ExplorePage extracts the peek bottom sheet into a focused component', () => {
  const source = explorePageSource()
  const peekSheetSource = mapPeekSheetSource()

  assert.match(source, /<MapPeekSheet/)
  assert.match(source, /id="map-place-detail"/)
  assert.match(peekSheetSource, /className=\{\[/)
  assert.match(peekSheetSource, /map-bottom-sheet-peek/)
  assert.doesNotMatch(peekSheetSource, /Ait|ait-|alt-/)
  assert.match(peekSheetSource, /role="button"/)
  assert.match(peekSheetSource, /tabIndex=\{0\}/)
  assert.match(peekSheetSource, /aria-controls="map-place-detail"/)
  assert.match(peekSheetSource, /aria-expanded=\{false\}/)
  assert.match(peekSheetSource, /event\.key === 'Enter' \|\| event\.key === ' '/)
  assert.match(peekSheetSource, /event\.preventDefault\(\)/)
  assert.match(peekSheetSource, /onPointerDown/)
  assert.doesNotMatch(peekSheetSource, /onOpenDirections/)
  assert.doesNotMatch(peekSheetSource, /map-sheet-peek-route/)
  assert.doesNotMatch(peekSheetSource, /StatusPill/)
  assert.doesNotMatch(peekSheetSource, /<p>/)
  assert.match(peekSheetSource, /className="map-sheet-peek-address"/)
  assert.match(peekSheetSource, /className="map-sheet-peek-categories"/)
  assert.match(peekSheetSource, /const visibleCategories = shop\.categories\.slice\(0, 3\)/)
  assert.match(peekSheetSource, /visibleCategories\.map/)
  assert.match(peekSheetSource, /className="map-sheet-peek-score"/)
  assert.match(peekSheetSource, /className="map-sheet-peek-rating"/)
  assert.match(peekSheetSource, /const averageRating = shop\.averageRating \?\? 0/)
  assert.match(peekSheetSource, /averageRating\.toFixed\(1\)/)
  assert.match(peekSheetSource, /리뷰 \{shop\.reviewCount\}개/)
  assert.doesNotMatch(source, /map-bottom-sheet-peek/)
})

test('ExplorePage extracts the expanded detail summary actions into a focused component', () => {
  const source = explorePageSource()
  const summarySource = mapDetailSummaryCardSource()
  const styles = appCssSource()

  assert.match(source, /<MapDetailSummaryCard/)
  assert.match(source, /workTypeLabels=\{detailWorkTypeLabels\}/)
  assert.match(source, /<MapDetailTabs/)
  assert.match(summarySource, /map-sheet-identity-card/)
  assert.match(summarySource, /workTypeLabels: string\[\]/)
  assert.match(summarySource, /map-sheet-identity-rating/)
  assert.match(summarySource, /map-sheet-keyword-row/)
  assert.match(summarySource, /\.\.\.workTypeLabels,/)
  assert.match(summarySource, /map-place-tabs/)
  assert.doesNotMatch(summarySource, /map-sheet-ai-summary/)
  assert.doesNotMatch(summarySource, /description:/)
  assert.match(summarySource, /onTabChange\('info'\)/)
  assert.match(summarySource, /리뷰 \{reviewCount\}/)
  assert.doesNotMatch(summarySource, /reviewCount\}개/)
  assert.match(summarySource, /onTabChange\('info'\)[\s\S]*onTabChange\('review'\)[\s\S]*onTabChange\('photos'\)[\s\S]*onTabChange\('works'\)/)
  assert.match(summarySource, /취급작품/)
  assert.match(summarySource, /onTabChange\('works'\)/)
  assert.doesNotMatch(source, /className="map-place-action-grid"/)
  assert.ok(cssRuleBodies(styles, '.map-place-tabs').some((rule) => /padding:\s*0 var\(--map-sheet-expanded-inline\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-place-tabs button').some((rule) => /min-width:\s*0;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-place-tabs button').some((rule) => /white-space:\s*nowrap;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-place-tabs button').some((rule) => /font-size:\s*var\(--ait-font-size-body-md\);/.test(rule)))
})

test('Explore detail summary toggles shop favorites through the Swagger favorite endpoints', () => {
  const source = explorePageSource()
  const summarySource = mapDetailSummaryCardSource()
  const styles = appCssSource()

  assert.match(source, /import \{ addFavoriteShop, getNearbyShops, getShop, getShopFacets, getShops, removeFavoriteShop \} from '\.\.\/shared\/api\/shops'/)
  assert.match(source, /import \{ getStoredAccessToken, readAuthSession \} from '\.\.\/shared\/lib\/authSession'/)
  assert.match(source, /import \{ Toast \} from '@aniwhere\/tds-mobile'/)
  assert.match(source, /const \[favoriteShopIdOverrides, setFavoriteShopIdOverrides\] = useState<Map<number, boolean>>\(\(\) => new Map\(\)\)/)
  assert.match(source, /const favoriteShopIds = useMemo\(\(\) =>/)
  assert.match(source, /const \[favoriteToast, setFavoriteToast\] = useState<string \| null>\(null\)/)
  assert.match(source, /const favoriteShopMutation = useMutation\(/)
  assert.match(source, /nextFavorite \? addFavoriteShop\(shopId, authToken\) : removeFavoriteShop\(shopId, authToken\)/)
  assert.match(source, /setFavoriteShopIdOverrides\(\(current\) =>/)
  assert.match(source, /onSuccess: async \(_result, variables\) =>/)
  assert.match(source, /await queryClient\.invalidateQueries\(\{ queryKey: \['users', 'me', 'favorite-shops'\] \}\)/)
  assert.match(source, /if \(authToken == null\)/)
  assert.match(source, /favoriteShopMutation\.mutate\(\{ shopId: detailShop\.id, nextFavorite: !isFavoriteDetailShop \}\)/)
  assert.match(source, /<Toast[\s\S]*?open=\{favoriteToast != null\}/)
  assert.match(source, /isFavorite=\{isFavoriteDetailShop\}/)
  assert.match(source, /isFavoritePending=\{favoriteShopMutation\.isPending\}/)
  assert.match(source, /onToggleFavorite=\{handleToggleFavoriteShop\}/)
  assert.match(summarySource, /isFavorite: boolean/)
  assert.match(summarySource, /isFavoritePending: boolean/)
  assert.match(summarySource, /onToggleFavorite: \(\) => void/)
  assert.match(summarySource, /className="map-place-favorite-button"/)
  assert.match(summarySource, /aria-pressed=\{isFavorite\}/)
  assert.match(summarySource, /disabled=\{isFavoritePending\}/)
  assert.match(summarySource, /className="map-place-favorite-icon"/)
  assert.ok(cssRuleBodies(styles, '.map-place-favorite-button').some((rule) => /width:\s*38px;/.test(rule)))
  assert.match(summarySource, /className="map-place-share-button"/)
  assert.match(summarySource, /aria-label="매장 공유하기"/)
  assert.ok(cssRuleBodies(styles, '.map-place-share-button').some((rule) => /width:\s*38px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-place-favorite-icon').some((rule) => /stroke:\s*currentcolor;/.test(rule)))
})

test('Explore list and map surfaces mark shops already saved as favorites', () => {
  const source = explorePageSource()
  const results = mapResultsSheetSource()
  const shopMap = shopMapSource()
  const styles = appCssSource()

  assert.match(source, /enabled: authToken != null/)
  assert.match(source, /favoriteShopsQuery\.data\?\.map\(\(shop\) => shop\.id\)/)
  assert.match(source, /favoriteShopIds=\{favoriteShopIds\}/)
  assert.match(results, /favoriteShopIds\?: Set<number>/)
  assert.match(results, /const isFavoriteShop = favoriteShopIds\?\.has\(shop\.id\) === true/)
  assert.match(results, /className="map-results-card-favorite"/)
  assert.match(results, /aria-label="관심 매장"/)
  assert.match(shopMap, /favoriteShopIds\?: Set<number>/)
  assert.match(shopMap, /const isFavorite = favoriteShopIds\.has\(group\.shop\.id\)/)
  assert.match(shopMap, /createShopMarkerIcon\(group\.shop, isActive, isFavorite\)/)
  assert.match(shopMap, /map-naver-shop-chip-favorite/)
  assert.ok(cssRuleBodies(styles, '.map-results-card-favorite').some((rule) => /color:\s*var\(--ait-color-red-700\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-naver-shop-chip-favorite').some((rule) => /color:\s*var\(--ait-color-red-700\);/.test(rule)))
})

test('Explore directions prefer the Naver Maps app scheme in Apps in Toss with web fallback', () => {
  const source = explorePageSource()
  const directions = fs.readFileSync(new URL('../src/shared/lib/naverDirections.ts', import.meta.url), 'utf8')

  assert.match(source, /import \{ openURL \} from '@apps-in-toss\/web-framework'/)
  assert.match(source, /buildNaverAppDirectionUrl/)
  assert.match(source, /buildNaverAppSearchUrl/)
  assert.match(source, /const naverAppDirectionUrl =/)
  assert.match(source, /const naverAppSearchUrl =/)
  assert.match(source, /async function openExternalMapUrl/)
  assert.match(source, /isAppsInTossRuntime\(\)/)
  assert.match(source, /await openURL\(primaryUrl\)/)
  assert.match(source, /fallbackUrl != null/)
  assert.match(source, /window\.open\(fallbackUrl/)
  assert.match(directions, /const NAVER_MAP_APP_NAME = 'aniwhere'/)
  assert.match(directions, /nmap:\/\/route\/public/)
  assert.match(directions, /nmap:\/\/search/)
  assert.match(directions, /appname/)
})

test('Explore share fallback reports failure when Clipboard API is unavailable', () => {
  const source = explorePageSource()

  assert.match(source, /if \(!navigator\.clipboard\) \{[\s\S]*throw new Error\('Clipboard API unavailable'\)/)
  assert.match(source, /await navigator\.clipboard\.writeText\(shareUrl\.toString\(\)\)/)
  assert.doesNotMatch(source, /navigator\.clipboard\?\.writeText/)
})

test('ExplorePage extracts the expanded detail info rows into a focused component', () => {
  const source = explorePageSource()
  const infoSource = mapDetailInfoCardSource()
  const styles = appCssSource()

  assert.match(source, /<MapDetailInfoCard/)
  assert.match(source, /description=\{detailDescription\}/)
  assert.match(source, /workTypeLabels=\{detailWorkTypeLabels\}/)
  assert.match(source, /getWorks/)
  assert.match(source, /const workCatalogById = useMemo/)
  assert.match(source, /const workTypeLabelsByShopId = useMemo/)
  assert.match(infoSource, /map-sheet-info-list-v3/)
  assert.doesNotMatch(infoSource, /@aniwhere\/tds-mobile/)
  assert.match(infoSource, /MapDetailRow/)
  assert.match(infoSource, /'map-sheet-ai-summary'[\s\S]*?'map-sheet-ai-summary-priority'/)
  assert.match(infoSource, /visibleAiSummary \? \([\s\S]*?'map-sheet-ai-summary-priority'[\s\S]*?\) : null\}\s*<ul className="map-sheet-info-list-v2 map-sheet-info-list-v3">/)
  assert.match(infoSource, /AI가 요약한 정보/)
  assert.match(infoSource, /const visibleAiSummary/)
  assert.match(infoSource, /const aiSummaryPreviewLimit = 72/)
  assert.match(infoSource, /const shouldShowVisitTip/)
  assert.match(infoSource, /description\?: string \| null/)
  assert.match(infoSource, /<li/)
  assert.match(infoSource, /'map-sheet-detail-row-v3--has-icon'/)
  assert.match(infoSource, /<span className="map-sheet-detail-icon">/)
  assert.match(infoSource, /<div className="map-sheet-detail-copy">/)
  assert.doesNotMatch(infoSource, /right=\{right\}/)
  assert.doesNotMatch(infoSource, /<Button/)
  assert.doesNotMatch(infoSource, /descriptionAction/)
  assert.match(infoSource, /<strong>\{description\}<\/strong>/)
  assert.match(infoSource, /const addressFloorLabel = floorLabel/)
  assert.match(infoSource, /<MapDetailRow[\s\S]*?className="map-sheet-detail-row-address"[\s\S]*?label="주소"[\s\S]*?className="map-sheet-address-inline"/)
  assert.match(infoSource, /className="map-sheet-address-link"[\s\S]*?aria-label=\{`\$\{shop\.address\} 길찾기`\}[\s\S]*?onClick=\{onOpenDirections\}[\s\S]*?\{shop\.address\}/)
  assert.match(infoSource, /addressFloorLabel \? <span className="map-sheet-address-meta">\{addressFloorLabel\}<\/span> : null/)
  assert.doesNotMatch(infoSource, /네이버지도/)
  assert.doesNotMatch(infoSource, /distanceLabel\]\.filter/)
  assert.doesNotMatch(infoSource, /label="위치"/)
  assert.doesNotMatch(infoSource, /map-sheet-ai-summary-standalone/)
  assert.match(infoSource, /formatRelativeUpdated/)
  assert.match(infoSource, /const updatedLabel = formatRelativeUpdated\(shop\.updatedAt\)/)
  assert.match(infoSource, /MapDetailRow icon="calendar" label="최근 업데이트"/)
  assert.match(infoSource, /MapDetailRow icon="clock" label="영업 상태"/)
  assert.doesNotMatch(infoSource, /icon="building"[\s\S]*?label="위치"/)
  assert.match(infoSource, /workTypeLabels: string\[\]/)
  assert.match(infoSource, /label="카테고리"/)
  assert.match(infoSource, /label="작품유형"/)
  assert.doesNotMatch(infoSource, /label="취급 정보"/)
  assert.match(infoSource, /workTypeLabels\.join\(' · '\)/)
  assert.match(infoSource, /shop\.categories\.length > 0 \? \(/)
  assert.match(infoSource, /workTypeLabels\.length > 0 \? \(/)
  assert.doesNotMatch(infoSource, /등록된 카테고리가 없어요/)
  assert.doesNotMatch(infoSource, /연결된 작품유형 정보가 없어요/)
  assert.doesNotMatch(infoSource, /map-sheet-info-header/)
  assert.doesNotMatch(infoSource, /map-place-address-button/)
  assert.doesNotMatch(infoSource, /map-place-address-action/)
  assert.doesNotMatch(infoSource, /map-place-directions-button/)
  assert.doesNotMatch(infoSource, /updatedNote/)
  assert.doesNotMatch(source, /function MapDetailRow/)
  assert.doesNotMatch(source, /className="section map-sheet-info-card/)
  assert.doesNotMatch(infoSource, /<ListRow/)
  assert.doesNotMatch(infoSource, /from '\.\.\/\.\.\/shared\/ui\/ait/)
  assert.ok(cssRuleBodies(appCssSource(), '.map-sheet-info-list-v2').some((rule) => /list-style:\s*none;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-shell-detail').some((rule) => /--map-sheet-expanded-inline:\s*20px;/.test(rule)))
  assert.equal(cssRuleBodies(styles, '.map-sheet-info-header').length, 0)
  assert.ok(cssRuleBodies(styles, '.map-sheet-info-list-v3').some((rule) => /padding:\s*4px 0 4px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-row-v3').some((rule) => /padding:\s*12px var\(--map-sheet-expanded-inline\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-row-v3:first-of-type').some((rule) => /padding-inline:\s*var\(--map-sheet-expanded-inline\);/.test(rule)))
  assert.match(styles, /@supports selector\(:has\(\.map-sheet-detail-icon\)\)/)
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-row-v3').some((rule) => /gap:\s*var\(--ait-space-3\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-row-v3 > :has(.map-sheet-detail-icon)').some((rule) => /width:\s*100%;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-icon').some((rule) => /height:\s*36px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-icon').some((rule) => /width:\s*36px;/.test(rule)))
  assert.doesNotMatch(
    cssRuleBodies(styles, '.map-sheet-detail-row-address').join('\n'),
    /align-items:\s*center;|padding:/,
  )
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-row-address .map-sheet-detail-copy').some((rule) => /width:\s*100%;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-detail-copy').some((rule) => /gap:\s*var\(--ait-space-1\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-address-inline').some((rule) => /display:\s*flex;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-address-inline').some((rule) => /flex-wrap:\s*wrap;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-address-meta').some((rule) => /border-radius:\s*var\(--ait-radius-full\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-address-link').some((rule) => /text-decoration:\s*underline;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-address-link').some((rule) => /color:\s*var\(--ait-color-brand-pressed\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-address-link').some((rule) => /overflow-wrap:\s*anywhere;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-ai-summary').some((rule) => /margin:\s*14px var\(--map-sheet-expanded-inline\) 12px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-ai-summary').some((rule) => /padding:\s*16px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-ai-summary p').some((rule) => /-webkit-line-clamp:\s*2;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-sheet-ai-summary-expanded p').some((rule) => /-webkit-line-clamp:\s*unset;/.test(rule)))
})

test('Explore detail media uses uploaded shop photos only instead of fabricated external placeholders', () => {
  const source = explorePageSource()
  const mediaSource = mapDetailMediaSectionSource()

  assert.match(source, /function buildDetailMediaItems\(shop: Shop\): DetailMediaItem\[\] \{[\s\S]*?return \[\.\.\.\(shop\.images \?\? \[\]\)\]/)
  assert.match(source, /const detailPreviewMediaItems = detailMediaItems\.slice\(0, 4\)/)
  assert.match(mediaSource, /detailMediaItems\.length > 0/)
  assert.doesNotMatch(source, /picsum\.photos/)
  assert.doesNotMatch(mediaSource, /picsum\.photos/)
  assert.doesNotMatch(source, /aniwhere-\$\{shop\.id\}/)
  assert.doesNotMatch(source, /uploadedPhotos/)
  assert.doesNotMatch(source, /localImages/)
  assert.doesNotMatch(source, /getShopPhotos/)
  assert.match(mediaSource, /aria-label="사진"/)
  assert.doesNotMatch(mediaSource, /aria-label="매장 사진"/)
})

test('ExplorePage extracts the expanded detail media section into a focused component', () => {
  const source = explorePageSource()
  const mediaSource = mapDetailMediaSectionSource()

  assert.match(source, /<MapDetailMediaSection/)
  assert.match(source, /const detailShopMediaItems = useMemo\(\(\) => \(detailShop \? buildDetailMediaItems\(detailShop\) : \[\]\), \[detailShop\]\)/)
  assert.match(source, /const detailReviewMediaItems = useMemo\(/)
  assert.match(source, /const detailMediaItems = useMemo\(\(\) => \[\.\.\.detailShopMediaItems, \.\.\.detailReviewMediaItems\]\.sort/)
  assert.match(source, /detailMediaItems=\{detailPreviewMediaItems\}/)
  assert.match(source, /onOpenMediaItem=\{openDetailMediaItem\}/)
  assert.match(source, /onOpenMoreMedia=\{\(\) => setDetailTab\('photos'\)\}/)
  assert.match(source, /totalMediaCount=\{detailMediaItems\.length\}/)
  assert.match(source, /<MapDetailTabs/)
  assert.match(source, /className="map-sheet-expanded-drag-handle"/)
  assert.doesNotMatch(source, /const detailReviewPhotoCount =/)
  assert.match(source, /const detailPhotoCount = detailMediaItems\.length/)
  assert.match(source, /detailTab === 'photos' && detailPhotoCount <= 0/)
  assert.match(mediaSource, /map-sheet-media-grid/)
  assert.match(mediaSource, /detailMediaItems\.length > 0/)
  assert.match(mediaSource, /onOpenMediaItem\?: \(item: MapDetailMediaItem, index: number\) => void/)
  assert.match(mediaSource, /onOpenMoreMedia\?: \(\) => void/)
  assert.match(mediaSource, /const visibleMediaItems = totalMediaCount >= 5 \? detailMediaItems\.slice\(0, 4\) : detailMediaItems/)
  assert.match(mediaSource, /const hiddenMediaCount = totalMediaCount >= 5 \? totalMediaCount - \(visibleMediaItems\.length - 1\) : 0/)
  assert.match(mediaSource, /const isMoreTile = totalMediaCount >= 5 && index === visibleMediaItems\.length - 1/)
  assert.match(mediaSource, /if \(isMoreTile\) \{[\s\S]*?onOpenMoreMedia\?\.\(\)[\s\S]*?return[\s\S]*?\}[\s\S]*?onOpenMediaItem\?\.\(item, index\)/)
  assert.match(mediaSource, /<PhotoMoreOverlay count=\{hiddenMediaCount\} \/>/)
  assert.match(mediaSource, /더보기 \{count\}개/)
  assert.match(mediaSource, /map-photo-more-overlay/)
  assert.match(mediaSource, /className="map-photo-more-icon"/)
  assert.match(mediaSource, /<circle cx="12" cy="12\.5" r="3"/)
  assert.doesNotMatch(mediaSource, /map-sheet-expanded-drag-handle/)
  assert.doesNotMatch(mediaSource, /shop\.links\.length/)
  assert.doesNotMatch(mediaSource, /shop\.works\.length,\s*4/)
  assert.doesNotMatch(source, /className=\{`map-sheet-media/)
  assert.doesNotMatch(source, /map-sheet-media-grid/)
  assert.ok(cssRuleBodies(appCssSource(), '.map-sheet-media-grid').some((rule) => /margin:\s*0;/.test(rule)))
  assert.ok(cssRuleBodies(appCssSource(), '.map-sheet-media-tile').some((rule) => /aspect-ratio:\s*3 \/ 4;/.test(rule)))
})

test('Explore detail sheet hides duplicate chrome controls in Toss navigation runtime', () => {
  const source = explorePageSource()
  const mediaSource = mapDetailMediaSectionSource()

  assert.match(source, /const usesTossNavigation = useMemo\(\(\) => isAppsInTossRuntime\(\), \[\]\)/)
  assert.match(source, /!usesTossNavigation \? \([\s\S]*?<AppTopNavigation/)
  assert.doesNotMatch(source, /showTopbarControls=/)
  assert.doesNotMatch(mediaSource, /GlobalNavigationMenu/)
  assert.doesNotMatch(mediaSource, /showTopbarControls/)
})

test('Explore detail selection pushes history so native back closes the sheet first', () => {
  const source = explorePageSource()

  assert.match(source, /const replaceSearchParams = \(next: URLSearchParams\) => \{\s*setSearchParams\(next, \{ replace: true \}\)/)
  assert.match(source, /const pushSearchParams = \(next: URLSearchParams\) => \{\s*setSearchParams\(next\)/)
  assert.match(source, /if \(selectedShopId == null\) \{\s*pushSearchParams\(next\)\s*\} else \{\s*replaceSearchParams\(next\)/)
  assert.match(source, /next\.delete\('shopId'\)[\s\S]*?replaceSearchParams\(next\)/)
  assert.doesNotMatch(source, /syncSearchParams/)
})

test('Explore detail back returns to the originating search route when opened from search results', () => {
  const source = explorePageSource()

  assert.match(source, /type ExploreLocationState = \{\s*returnTo\?: string/)
  assert.match(source, /function isSafeExploreReturnTo\(returnTo: string \| undefined\)/)
  assert.match(source, /const safeRouteReturnTo = isSafeExploreReturnTo\(routeState\?\.returnTo\)/)
  assert.match(source, /const shouldReturnToSourceList = safeRouteReturnTo != null && isListSheetOpen/)
  assert.doesNotMatch(source, /navigate\(routeState\.returnTo/)
  assert.match(source, /if \(selectedShopId != null && safeRouteReturnTo\) \{\s*navigate\(safeRouteReturnTo, \{ replace: true \}\)/)
})

test('Explore list-map view switches replace history so removed chips do not resurrect', () => {
  const source = explorePageSource()

  assert.match(source, /const moveViewMode = \(nextViewMode: ViewMode\) => \{[\s\S]*?next\.set\('view', nextViewMode\)[\s\S]*?replaceSearchParams\(next\)[\s\S]*?\}/)
  assert.doesNotMatch(source, /next\.set\('view', nextViewMode\)\s*pushSearchParams\(next\)/)
  assert.match(source, /if \(isListSheetOpen\) \{\s*handleSwitchView\('map'\)/)
  assert.match(source, /setFocusMode\('idle'\)/)
  assert.match(source, /restoreViewport=\{mapViewport\}/)
})

test('Explore list toggle stays available over a selected shop peek and opens the full list route', () => {
  const source = explorePageSource()
  const overlayControlsSource = mapOverlayControlsSource()
  const styles = exploreSearchCssSource()
  const peekListButtonRules = cssRuleBodies(styles, '.map-surface-sheet-peek .map-list-fab')

  assert.match(source, /<MapOverlayControls[\s\S]*?showListToggle=\{sheetMode !== 'expanded' && sheetMode !== 'review'\}/)
  assert.match(overlayControlsSource, /showListToggle: boolean/)
  assert.match(overlayControlsSource, /\{showListToggle \? \(/)
  assert.match(source, /if \(selectedShopId != null\) \{\s*restoreListView\(\)\s*return\s*\}/)
  assert.match(source, /<ShopMap\s+shops=\{mappableShops\}/)
  assert.doesNotMatch(source, /!\s*isListSheetOpen\s*\?\s*\([\s\S]*?<ShopMap/)
  assert.ok(peekListButtonRules.some((rule) => /z-index:\s*1080;/.test(rule)))
  assert.doesNotMatch(source, /if \(selectedShopId != null\) \{\s*return\s*\}/)
})

test('Explore list view is a full search and results surface instead of a map bottom sheet', () => {
  const source = explorePageSource()
  const styles = exploreSearchCssSource()
  const fullListStart = source.indexOf('if (isFullListView)')
  const fullListEnd = source.indexOf('\n  return (', fullListStart + 1)
  const fullListBranch = source.slice(fullListStart, fullListEnd)

  assert.match(source, /if \(isFullListView\) \{[\s\S]*'map-list-view'/)
  assert.match(source, /if \(isFullListView\) \{[\s\S]*<ExploreTopSearch/)
  assert.match(source, /next\.set\('view', routeViewMode\)[\s\S]*return `\$\{location\.pathname\}\?\$\{next\.toString\(\)\}`/)
  assert.match(source, /\}, \[location\.pathname, routeViewMode, searchParams\]\)/)
  assert.match(source, /next\.set\('returnTo', searchReturnTo\)/)
  assert.match(source, /if \(isFullListView\) \{[\s\S]*onSearchClick=\{\(\) => navigate\(searchHref\)\}/)
  assert.match(source, /if \(isFullListView\) \{[\s\S]*<MapResultsSheet/)
  assert.match(source, /if \(isFullListView\) \{[\s\S]*<MapOverlayControls/)
  assert.doesNotMatch(fullListBranch, /<ShopMap/)
  assert.doesNotMatch(fullListBranch, /<MapQuickChips/)
  assert.doesNotMatch(fullListBranch, /map-chip-status/)
  assert.ok(cssRuleBodies(styles, '.map-list-view').some((rule) => /height:\s*100dvh;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-list-view').some((rule) => /display:\s*flex;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-list-view-top').some((rule) => /flex:\s*0 0 auto;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-list-panel').some((rule) => /flex:\s*1 1 auto;/.test(rule)))
  assert.equal(cssRuleBodies(styles, '.map-results-sheet-v2').length, 0)
})

test('Explore detail shop changes replace history instead of stacking visited shops', () => {
  const source = explorePageSource()

  assert.match(source, /const sheetMode: SheetMode =\s+selectedShopId && sheetParam === 'review' \? 'review' : selectedShopId && sheetParam === 'expanded' \? 'expanded' : 'peek'/)
  assert.match(source, /selectedShopId == null[\s\S]*?pushSearchParams\(next\)[\s\S]*?replaceSearchParams\(next\)/)
  assert.doesNotMatch(source, /setSheetMode/)
})

test('Explore list detail back preserves the previous list entry and restores scroll state', () => {
  const source = explorePageSource()

  assert.match(source, /const previousSelectedShopIdRef = useRef<number \| null>\(selectedShopId\)/)
  assert.match(source, /const previousSelectedShopId = previousSelectedShopIdRef\.current/)
  assert.match(source, /previousSelectedShopIdRef\.current = selectedShopId/)
  assert.match(source, /previousSelectedShopId != null && selectedShopId == null && isFullListView && selectionOrigin === 'list'/)
  assert.match(source, /pendingListRestoreRef\.current = true/)
  assert.match(source, /setVisibleListCount\(Math\.max\(PAGE_SIZE, listVisibleCountRef\.current\)\)/)
  assert.match(source, /if \(sheetMode === 'expanded' && selectionOrigin === 'list'\) \{[\s\S]*?navigate\(-1\)[\s\S]*?return/)
  assert.doesNotMatch(source, /if \(sheetMode === 'expanded' && selectionOrigin === 'list'\) \{[\s\S]*?restoreListView\(\)/)
})

test('Explore expanded detail state is encoded in history for native back folding', () => {
  const source = explorePageSource()

  assert.match(source, /const sheetParam = searchParams\.get\('sheet'\)/)
  assert.match(source, /selectedShopId && sheetParam === 'expanded' \? 'expanded' : 'peek'/)
  assert.match(source, /next\.set\('sheet', 'expanded'\)/)
  assert.match(source, /next\.delete\('sheet'\)/)
  assert.match(source, /if \(selectedShopId != null && sheetParam !== 'expanded'\) \{[\s\S]*?pushSearchParams\(next\)/)
  assert.doesNotMatch(source, /setSheetMode/)
})

test('Explore detail can open the review tab from profile review deep links', () => {
  const source = explorePageSource()
  const supplementSource = mapDetailSupplementSectionsSource()

  assert.match(source, /function parseDetailTab\(value: string \| null\): MapDetailTab \| null/)
  assert.match(source, /const detailTabParam = parseDetailTab\(searchParams\.get\('tab'\)\)/)
  assert.match(source, /const detailFocusParam = searchParams\.get\('focus'\)/)
  assert.match(source, /const detailReviewFocusId = Number\(searchParams\.get\('reviewId'\) \?\? ''\) \|\| null/)
  assert.match(source, /const shouldFocusRouteReview = detailFocusParam === 'review'/)
  assert.match(source, /useState<MapDetailTab>\(\(\) => detailTabParam \?\? 'info'\)/)
  assert.match(source, /setDetailTab\(detailTabParam\)/)
  assert.match(source, /target\.scrollIntoView\(\{ block: 'start', behavior: 'smooth' \}\)/)
  assert.match(source, /target\.focus\(\{ preventScroll: true \}\)/)
  assert.match(source, /next\.delete\('reviewId'\)/)
  assert.match(supplementSource, /id="map-place-review"[\s\S]*tabIndex=\{-1\}/)
  assert.match(supplementSource, /data-review-id=\{review\.id\}/)
})

test('ExplorePage extracts the expanded detail supplement sections into a focused component', () => {
  const source = explorePageSource()
  const supplementSource = mapDetailSupplementSectionsSource()

  assert.match(source, /<MapDetailSupplementSections/)
  assert.match(supplementSource, /map-place-review-card/)
  assert.match(supplementSource, /리뷰 남기기/)
  assert.doesNotMatch(supplementSource, /리뷰작성하기/)
  assert.match(supplementSource, /map-photo-viewer-review-link/)
  assert.match(supplementSource, /리뷰 보기/)
  assert.match(supplementSource, /map-sheet-work-feed/)
  assert.match(supplementSource, /map-sheet-work-row/)
  assert.match(supplementSource, /map-sheet-work-cover/)
  assert.match(supplementSource, /map-sheet-work-more/)
  assert.match(supplementSource, /visibleWorks = isWorkFeedExpanded \? shop\.works : shop\.works\.slice\(0, WORK_FEED_PREVIEW_LIMIT\)/)
  assert.match(supplementSource, /to=\{`\/explore\?view=list&scope=work&keyword=\$\{encodeURIComponent\(work\.name\)\}`\}/)
  assert.match(supplementSource, /이 작품으로 매장 더 보기/)
  assert.doesNotMatch(supplementSource, /map-sheet-token-cloud/)
  assert.match(supplementSource, /map-sheet-photo-feed/)
  assert.match(supplementSource, /<img src=\{item\.src\} alt=\{item\.alt\} loading="eager" decoding="async" \/>/)
  assert.doesNotMatch(supplementSource, /map-place-review-photo-strip/)
  assert.match(supplementSource, /MapPhotoViewer/)
  assert.match(supplementSource, /map-photo-viewer-track/)
  assert.match(supplementSource, /review\.images\.map/)
  assert.match(supplementSource, /activeTab === 'works'/)
  assert.match(supplementSource, /activeTab === 'photos'/)
  assert.doesNotMatch(source, /map-place-review-card/)
  assert.doesNotMatch(source, /map-sheet-link-section-v2/)
  assert.doesNotMatch(source, /map-sheet-recommend-section/)
  assert.ok(cssRuleBodies(appCssSource(), '.map-sheet-work-feed').some((rule) => /display:\s*flex;/.test(rule)))
  assert.ok(cssRuleBodies(appCssSource(), '.map-sheet-work-row').some((rule) => /grid-template-columns:\s*44px minmax\(0, 1fr\) auto;/.test(rule)))
  assert.ok(cssRuleBodies(appCssSource(), '.map-sheet-work-cover').some((rule) => /width:\s*44px;/.test(rule)))
  assert.ok(cssRuleBodies(appCssSource(), '.map-sheet-photo-item').some((rule) => /transform:\s*translateZ\(0\);/.test(rule)))
})
test('ExplorePage exposes map viewport search after the map moves', () => {
  const source = explorePageSource()

  assert.match(source, /onViewportChange=\{handleMapViewportChange\}/)
  assert.match(source, /getNearbyShops/)
  assert.match(source, /const \[mapAreaSearchCenter, setMapAreaSearchCenter\]/)
  assert.match(source, /queryKey: \['shops', 'nearby-map-area', mapAreaSearchCenter\]/)
  assert.match(source, /getNearbyShops\(\{ lat: mapAreaSearchCenter\.latitude, lng: mapAreaSearchCenter\.longitude \}\)/)
  assert.match(source, /setMapAreaSearchCenter\(mapViewport\.center\)/)
  assert.match(source, /mapViewportFilter/)
  assert.match(source, /이 지역 매장 검색/)
})

test('ExplorePage sends selected filters to the shop API instead of local-only chips', () => {
  const source = explorePageSource()

  assert.match(source, /import \{ keepPreviousData, useMutation, useQueries, useQuery, useQueryClient \} from '@tanstack\/react-query'/)
  assert.match(source, /parseShopFilters\(searchParams\)/)
  assert.match(source, /toShopSearchParams\(selectedFilters\)/)
  assert.match(source, /const currentSearchScope = searchParams\.get\('scope'\) === 'work' \? 'work' : 'shop'/)
  assert.match(source, /const currentKeyword = searchParams\.get\('keyword'\)\?\.trim\(\) \?\? ''/)
  assert.match(source, /const exploreSearchParams = useMemo/)
  assert.match(source, /currentSearchScope === 'work'[\s\S]*\{ workKeyword: currentKeyword \}[\s\S]*\{ keyword: currentKeyword \}/)
  assert.match(source, /queryKey: \['shops', 'explore-map-source', exploreSearchParams\]/)
  assert.match(source, /getShops\(\{ page: 0, size: MAP_FETCH_SIZE, \.\.\.exploreSearchParams \}\)/)
  assert.match(source, /placeholderData: keepPreviousData/)
  assert.match(source, /const appliedFilterCount = countShopFilters\(selectedFilters\)/)
  assert.doesNotMatch(source, /countShopFilters\(selectedFilters\) \+ \(mapViewportFilter \? 1 : 0\)/)
  assert.match(source, /selectedSearchParams\.regionIds\.length > 0/)
  assert.match(source, /selectedSearchParams\.regionIds\.includes\(shop\.regionId\)/)
  assert.match(source, /writeShopFilters\(searchParams, nextFilters\)/)
  assert.doesNotMatch(source, /const nextViewportFilter = mapViewport\?\.bounds \?\? mapViewportFilter/)
  assert.doesNotMatch(source, /setMapViewportFilter\(nextViewportFilter\)/)
  assert.match(source, /viewportBounds=\{mapViewport\?\.bounds \?\? mapViewportFilter\}/)
  assert.match(source, /id: 'favorite'/)
  assert.doesNotMatch(source, /next\.append\('sort', 'reviewCount,desc'\)/)
})

test('ExplorePage keeps the map mounted while filter chips refetch shop results', () => {
  const source = explorePageSource()

  assert.match(source, /<ShopMap\s+shops=\{mappableShops\}/)
  assert.doesNotMatch(source, /shopsQuery\.isLoading && allShops\.length === 0 \? \(/)
  assert.doesNotMatch(source, /<div className="map-empty">\s*<p>매장 지도를 준비하고 있습니다\.<\/p>/)
})

test('ExplorePage closes a selected POI sheet when applied filters remove that shop from results', () => {
  const source = explorePageSource()

  assert.match(source, /const selectedShopIsInFilteredResults =\s*selectedShopId == null \|\| shopsWithDistance\.some\(\(shop\) => shop\.id === selectedShopId\)/)
  assert.match(source, /selectedShopId == null \|\|\s*appliedFilterCount === 0 \|\|\s*activeShopsQueryIsPlaceholder \|\|\s*!activeShopsQueryIsSuccess \|\|\s*selectedShopIsInFilteredResults/)
  assert.match(source, /next\.delete\('shopId'\)[\s\S]*?next\.delete\('sheet'\)/)
  assert.match(source, /if \(selectionOrigin === 'list'\) \{\s*next\.set\('view', 'list'\)/)
  assert.match(source, /setSearchParams\(next, \{ replace: true \}\)/)
})

test('ExplorePage shows removable applied filters without opening the filter sheet', () => {
  const source = explorePageSource()
  const resultsSheetSource = mapResultsSheetSource()
  const chipSource = appliedFilterChipsSource()
  const filtersSource = shopFiltersSource()
  const facetQuerySource = shopFacetQuerySource()
  const styles = appCssSource()

  assert.match(source, /import \{ [^}]*getShop, getShopFacets, getShops[^}]* \} from '\.\.\/shared\/api\/shops'/)
  assert.match(source, /import \{ AppliedFilterChips \} from '\.\.\/shared\/ui\/AppliedFilterChips'/)
  assert.match(source, /const hasAppliedFilterChips = appliedFilterCount > 0/)
  assert.match(source, /const appliedFacetParams = \{ includeRegions: true, includeCategories: true, includeWorkTypes: true, includeSorts: true \}/)
  assert.match(source, /queryKey: shopFacetQueryKey\(appliedFacetParams\)/)
  assert.match(source, /queryFn: \(\) => getShopFacets\(appliedFacetParams\)/)
  assert.match(source, /refetchOnMount: 'always'/)
  assert.match(source, /SHOP_FACET_STALE_TIME_MS/)
  assert.match(source, /SHOP_FACET_GC_TIME_MS/)
  assert.match(facetQuerySource, /export function shopFacetQueryKey/)
  assert.doesNotMatch(source, /explore-applied-filter-facets/)
  assert.doesNotMatch(source, /includeMapArea=\{mapViewportFilter != null\}/)
  assert.match(source, /removeAppliedFilterChip/)
  assert.match(source, /className="map-chip-composite-row"/)
  assert.match(source, /appliedFilters=\{renderAppliedFilterChips\(\)\}/)
  assert.match(resultsSheetSource, /appliedFilters: ReactNode/)
  assert.match(resultsSheetSource, /aria-label="검색 결과"/)
  assert.match(resultsSheetSource, /<div className="search-result-head">[\s\S]*<div className="map-results-sheet-top">[\s\S]*\{appliedFilters\}/)
  assert.doesNotMatch(source, /<div className="map-list-view-top">[\s\S]{0,420}\{renderAppliedFilterChips\(\)\}/)
  assert.doesNotMatch(resultsSheetSource, /map-results-sheet-title/)
  assert.doesNotMatch(resultsSheetSource, /\{topSearch\}/)
  assert.doesNotMatch(source, /removeAppliedFilterChip[\s\S]{0,260}setIsFilterSheetOpen\(true\)/)
  assert.match(chipSource, /buildAppliedShopFilterChips/)
  assert.doesNotMatch(chipSource, /includeMapArea/)
  assert.doesNotMatch(filtersSource, /facet: 'mapArea'/)
  assert.ok(cssRuleBodies(styles, '.map-chip-composite-row').some((rule) => /display:\s*flex;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-composite-row .map-chip-toolbar').some((rule) => /flex:\s*0 0 auto;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-applied-filter-chips').some((rule) => /flex:\s*1 1 auto;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-applied-filter-chips').some((rule) => /padding-top:\s*0;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.applied-filter-chip').some((rule) => /min-height:\s*38px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status').some((rule) => /min-height:\s*38px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-sheet-top .applied-filter-chip-rail').some((rule) => /margin-top:\s*calc\(var\(--ait-space-2\) \* -1\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-explore-top .applied-filter-chip-rail').some((rule) => /pointer-events:\s*auto;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-explore-top-hidden .applied-filter-chip-rail').some((rule) => /pointer-events:\s*none;/.test(rule)))
  assert.doesNotMatch(styles, /--ait-color-brand-weak/)
  assert.doesNotMatch(styles, /--ait-color-brand-strong/)
})

test('Explore controls separate list, location, zoom, and AI actions for mobile reachability', () => {
  const styles = appCssSource()
  const listRules = cssRuleBodies(styles, '.map-list-fab')
  const locationRules = cssRuleBodies(styles, '.map-location-fab')
  const aiRules = cssRuleBodies(styles, '.map-llm-fab')

  assert.ok(listRules.some((rule) => /left:\s*50%;/.test(rule)))
  assert.ok(listRules.some((rule) => /right:\s*auto;/.test(rule)))
  assert.ok(listRules.some((rule) => /bottom:\s*calc\(var\(--map-control-bottom/.test(rule)))
  assert.ok(listRules.some((rule) => /transform:\s*translateX\(-50%\);/.test(rule)))
  assert.ok(listRules.some((rule) => /border-radius:\s*var\(--ait-radius-full\);/.test(rule)))
  assert.ok(locationRules.some((rule) => /right:\s*var\(--map-control-right/.test(rule)))
  assert.ok(locationRules.some((rule) => /bottom:\s*calc\(var\(--map-control-bottom/.test(rule)))
  assert.ok(aiRules.some((rule) => /bottom:\s*calc\(\s*var\(--map-control-bottom/.test(rule)))
})

test('Explore map search and filter controls stay visually separated to avoid accidental taps', () => {
  const styles = appCssSource()
  const topRowRules = cssRuleBodies(styles, '.map-search-row.search-screen-toolrow')
  const fieldRules = cssRuleBodies(styles, '.map-search-row .search-screen-bar.map-search-field')
  const filterRules = cssRuleBodies(styles, '.map-search-row .map-filter-button')

  assert.ok(topRowRules.some((rule) => /gap:\s*var\(--ait-space-4\);/.test(rule)))
  assert.ok(topRowRules.some((rule) => /background:\s*transparent;/.test(rule)))
  assert.ok(fieldRules.some((rule) => /border-radius:\s*var\(--ait-radius-full\);/.test(rule)))
  assert.ok(fieldRules.some((rule) => /background:\s*var\(--ait-color-surface-raised\);/.test(rule)))
  assert.ok(filterRules.some((rule) => /width:\s*46px;/.test(rule)))
  assert.ok(filterRules.some((rule) => /border:\s*1px solid var\(--ait-color-border-strong\);/.test(rule)))
})

test('Explore map overlay controls avoid competing raised layers', () => {
  const styles = appCssSource()
  const areaSearchRules = cssRuleBodies(styles, '.map-area-search-button')

  assert.ok(areaSearchRules.some((rule) => /background:\s*var\(--ait-color-surface-raised\);/.test(rule)))
  assert.ok(areaSearchRules.some((rule) => /color:\s*var\(--text-strong\);/.test(rule)))
  assert.doesNotMatch(styles, /\.map-surface-sheet-open\s+\.map-list-fab\s*\{[\s\S]*?display:\s*none;/)
})

test('Explore and shared app CSS do not use box shadows', () => {
  const styles = appCssSource()

  assert.doesNotMatch(styles, /box-shadow/)
})

test('Explore peek sheet keeps map controls clear of the selected shop summary', () => {
  const source = explorePageSource()
  const styles = exploreSearchCssSource()
  const peekSurfaceRules = cssRuleBodies(styles, '.map-surface-app-v2.map-surface-sheet-peek')
  const peekLocationRules = cssRuleBodies(styles, '.map-surface-sheet-peek .map-location-fab')
  const listRules = cssRuleBodies(styles, '.map-list-fab')
  const zoomRules = cssRuleBodies(styles, '.map-zoom-control')

  assert.match(source, /sheetMode === 'peek' && detailShop \? 'map-surface-sheet-peek' : ''/)
  assert.ok(peekSurfaceRules.some((rule) => /--map-control-bottom:\s*clamp\(260px,\s*42dvh,\s*360px\);/.test(rule)))
  assert.ok(peekLocationRules.some((rule) => /display:\s*none;/.test(rule)))
  assert.ok(listRules.some((rule) => /bottom:\s*calc\(var\(--map-control-bottom/.test(rule)))
  assert.ok(zoomRules.some((rule) => /bottom:\s*var\(--map-control-bottom/.test(rule)))
  assert.equal(cssRuleBodies(styles, '.map-surface-sheet-peek .map-list-fab').some((rule) => /display:\s*none;/.test(rule)), false)
  assert.ok(cssRuleBodies(styles, '.map-surface-sheet-peek .map-list-fab').some((rule) => /bottom:\s*calc\(var\(--map-control-bottom/.test(rule)))
})

test('Explore full list view reserves space around the map toggle button', () => {
  const styles = exploreSearchCssSource()
  const overlayControls = mapOverlayControlsSource()
  const listViewRules = cssRuleBodies(styles, '.map-list-view')
  const panelRules = cssRuleBodies(styles, '.map-results-list-panel')
  const listButtonRules = cssRuleBodies(styles, '.map-list-view .map-list-fab')
  const listPanelRules = cssRuleBodies(styles, '.map-list-view .map-results-sheet-list')
  const floatingButtonRules = cssRuleBodies(styles, '.map-list-fab')

  assert.ok(listViewRules.some((rule) => /--map-control-bottom:\s*max\(80px,\s*calc\(env\(safe-area-inset-bottom\) \+ 72px\)\);/.test(rule)))
  assert.ok(panelRules.some((rule) => /overflow:\s*hidden;/.test(rule)))
  assert.ok(panelRules.some((rule) => /border-radius:\s*0;/.test(rule)))
  assert.match(overlayControls, /className="map-list-fab-label"/)
  assert.match(overlayControls, /isListSheetOpen \? ['"]지도보기['"] : ['"]목록보기['"]/)
  assert.ok(floatingButtonRules.some((rule) => /left:\s*50%;/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /right:\s*auto;/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /transform:\s*translateX\(-50%\);/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /width:\s*auto;/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /height:\s*42px;/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /min-width:\s*102px;/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /padding:\s*0 14px;/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /border:\s*0;/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /background:\s*var\(--tDarkFillButtonBackground,\s*#4e5968\);/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /color:\s*var\(--ait-color-text-inverse\);/.test(rule)))
  assert.ok(floatingButtonRules.some((rule) => /font-size:\s*var\(--ait-font-size-body-lg\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-list-fab-map').some((rule) => /background:\s*var\(--tDarkFillButtonBackground,\s*#4e5968\);/.test(rule)))
  assert.ok(listButtonRules.some((rule) => /bottom:\s*max\(28px,\s*calc\(env\(safe-area-inset-bottom\) \+ 20px\)\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-list-fab-label').some((rule) => /white-space:\s*nowrap;/.test(rule)))
  assert.ok(listPanelRules.some((rule) => /flex:\s*1 1 auto;/.test(rule)))
  assert.ok(listPanelRules.some((rule) => /scrollbar-gutter:\s*stable;/.test(rule)))
  assert.ok(listPanelRules.some((rule) => /padding-right:\s*var\(--ait-space-1\);/.test(rule)))
  assert.equal(listPanelRules.some((rule) => /padding-right:\s*var\(--ait-space-4\);/.test(rule)), false)
  assert.ok(listPanelRules.some((rule) => /padding-bottom:\s*max\(104px,\s*calc\(env\(safe-area-inset-bottom\) \+ 96px\)\);/.test(rule)))
})

test('Explore list cards use available shop summary fields in a carrot-style dense card', () => {
  const source = explorePageSource()
  const resultsSheet = mapResultsSheetSource()
  const styles = exploreSearchCssSource()

  assert.match(source, /import \{ keepPreviousData, useMutation, useQueries, useQuery, useQueryClient \} from '@tanstack\/react-query'/)
  assert.match(source, /const listReviewQueries = useQueries\(/)
  assert.match(source, /queryFn: \(\) => listShopReviews\(shop\.id, \{ page: 0, size: 20, sort: 'NEWEST' \}, authToken\)/)
  assert.match(source, /const listReviewPhotosByShopId = useMemo\(/)
  assert.match(source, /reviewPhotosByShopId=\{listReviewPhotosByShopId\}/)
  assert.match(source, /workTypeLabelsByShopId=\{workTypeLabelsByShopId\}/)
  assert.match(resultsSheet, /export type MapResultReviewPhoto =/)
  assert.match(resultsSheet, /workTypeLabelsByShopId\?: Record<number, string\[]>/)
  assert.match(resultsSheet, /getShopCategoryLabels\(shop, workTypeLabelsByShopId\?\.\[shop\.id\]\)/)
  assert.match(resultsSheet, /reviewPhotosByShopId\?: Record<number, MapResultReviewPhoto\[]>/)
  assert.match(resultsSheet, /function getResultCardPhotos\(shop: MapResultShop, reviewPhotos: MapResultReviewPhoto\[] = \[\]\)/)
  assert.match(resultsSheet, /\[\.\.\.shopPhotos, \.\.\.reviewPhotos\]\.sort/)
  assert.match(resultsSheet, /const averageRating = shop\.averageRating \?\? 0/)
  assert.match(resultsSheet, /averageRating\.toFixed\(1\)/)
  assert.match(resultsSheet, /shop\.reviewCount/)
  assert.match(resultsSheet, /className="map-results-card-score"/)
  assert.match(resultsSheet, /className="map-results-card-review-count"/)
  assert.match(resultsSheet, /function getShopCategoryLabels\(shop: Shop, workTypeLabels: string\[\] = \[\]\)/)
  assert.match(resultsSheet, /shop\.categories\.map\(\(category\) => category\.name\)/)
  assert.match(resultsSheet, /\.\.\.workTypeLabels,/)
  assert.match(resultsSheet, /categoryLabels\.slice\(0, 3\)\.map/)
  assert.match(resultsSheet, /shop\.address/)
  assert.match(resultsSheet, /shop\.images/)
  assert.match(resultsSheet, /const photos = getResultCardPhotos\(shop, reviewPhotosByShopId\?\.\[shop\.id\]\)/)
  assert.match(resultsSheet, /<ShopPhotoStrip photos=\{photos\} shopName=\{shop\.name\} \/>/)
  assert.match(resultsSheet, /className="map-photo-more-icon"/)
  assert.match(resultsSheet, /<circle cx="12" cy="12\.5" r="3"/)
  assert.match(resultsSheet, /더보기 \{count\}개/)
  assert.match(resultsSheet, /className="map-results-card-media"/)
  assert.doesNotMatch(resultsSheet, /getShopSummaryNote/)
  assert.doesNotMatch(resultsSheet, /shop\.visitTip/)
  assert.doesNotMatch(resultsSheet, /shop\.description/)
  assert.doesNotMatch(resultsSheet, /className="map-results-card-note"/)
  assert.doesNotMatch(resultsSheet, /latestReview/)
  assert.doesNotMatch(resultsSheet, /formatRelativeUpdated/)

  assert.ok(cssRuleBodies(styles, '.map-results-card').some((rule) => /width:\s*100%;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card').some((rule) => /box-sizing:\s*border-box;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card').some((rule) => /flex:\s*0 0 auto;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card').some((rule) => /gap:\s*var\(--ait-space-2\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-head').some((rule) => /display:\s*flex;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-head').some((rule) => /width:\s*100%;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-score').some((rule) => /align-items:\s*flex-end;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-rating').some((rule) => /align-items:\s*center;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-review-count').some((rule) => /font-size:\s*var\(--ait-font-size-body-sm\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-meta').some((rule) => /flex-wrap:\s*wrap;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-meta span').some((rule) => /border-radius:\s*var\(--ait-radius-full\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-media').some((rule) => /display:\s*flex;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-media').some((rule) => /overflow-x:\s*auto;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-photo-frame').some((rule) => /3\.5/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-results-card-photo-frame').some((rule) => /aspect-ratio:\s*1 \/ 1;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-photo-more-overlay').some((rule) => /backdrop-filter:\s*blur\(3px\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-photo-more-icon').some((rule) => /stroke:\s*currentcolor;/.test(rule)))
  assert.equal(cssRuleBodies(styles, '.map-results-card-note').length, 0)
})

test('Explore map chip rail only captures pointer events on actual controls', () => {
  const styles = appCssSource()
  const topRules = cssRuleBodies(styles, '.map-explore-top')
  const routeNavigationRules = cssRuleBodies(styles, '.map-route-navigation')
  const chipToolbarRules = cssRuleBodies(styles, '.map-chip-toolbar')
  const chipScrollRules = cssRuleBodies(styles, '.map-chip-scroll')
  const chipStatusRules = cssRuleBodies(styles, '.map-chip-status')

  assert.ok(topRules.some((rule) => /pointer-events:\s*none;/.test(rule)))
  assert.ok(routeNavigationRules.some((rule) => /pointer-events:\s*auto;/.test(rule)))
  assert.ok(chipToolbarRules.some((rule) => /align-self:\s*flex-start;/.test(rule)))
  assert.ok(chipScrollRules.some((rule) => /width:\s*fit-content;/.test(rule)))
  assert.ok(chipScrollRules.some((rule) => /flex:\s*0 1 auto;/.test(rule)))
  assert.ok(chipStatusRules.some((rule) => /pointer-events:\s*auto;/.test(rule)))
})

test('ExplorePage does not fabricate category filter chips without a facet API', () => {
  const source = explorePageSource()
  const quickChipsSource = mapQuickChipsSource()

  assert.doesNotMatch(source, /const categories = useMemo/)
  assert.doesNotMatch(source, /setFilter/)
  assert.doesNotMatch(source, /role="tablist"/)
  assert.doesNotMatch(source, /category && !shop\.categories\.includes/)
  assert.match(source, /MAP_QUICK_CHIPS/)
  assert.match(quickChipsSource, /className=\{`map-chip-status/)
  assert.match(quickChipsSource, /aria-pressed=\{isActive\}/)
  assert.match(source, /onToggle=\{toggleMapQuickChip\}/)
  assert.doesNotMatch(source, /className=\{`map-chip-status[\s\S]{0,280}setIsFilterSheetOpen\(true\)/)
  assert.match(quickChipsSource, /\.filter\(\(item\) => item\.hidden !== true\)/)
  assert.match(source, /id: 'favorite'/)
  assert.match(source, /if \(chipId === 'favorite'\)/)
  assert.doesNotMatch(source, /mappableShops\.length\}/)
})

test('Explore map quick chips expose the favorite action while keeping open status and review sorting out of the rail', () => {
  const source = explorePageSource()
  const quickChipsSource = mapQuickChipsSource()
  const styles = appCssSource()

  assert.match(source, /id: 'hours'[\s\S]*label: '영업중'[\s\S]*icon: 'time'[\s\S]*hidden: true/)
  assert.match(source, /id: 'favorite'[\s\S]*label: '관심매장'[\s\S]*icon: 'star'/)
  assert.doesNotMatch(source, /id: 'reviewCount'/)
  assert.doesNotMatch(source, /label: '리뷰많은순'/)
  assert.match(quickChipsSource, /\.filter\(\(item\) => item\.hidden !== true\)/)
  assert.match(source, /const \[favoriteQuickChipActive, setFavoriteQuickChipActive\] = useState\(false\)/)
  assert.match(source, /favorite: favoriteQuickChipActive/)
  assert.doesNotMatch(source, /reviewCount: selectedSearchParams/)
  assert.doesNotMatch(source, /next\.append\('sort', 'reviewCount,desc'\)/)
  assert.match(source, /queryFn: \(\) => listMyFavoriteShops\(authToken\)/)
  assert.match(source, /enabled: authToken != null/)
  assert.doesNotMatch(source, /favoriteQuickChipActive && !favoriteShopIds\.has\(shop\.id\)/)
  assert.match(quickChipsSource, /type MapQuickChipIconName = 'time' \| 'star'/)
  assert.match(quickChipsSource, /function MapQuickChipIcon/)
  assert.match(quickChipsSource, /item\.ariaLabel \?\? item\.label/)
  assert.match(quickChipsSource, /map-chip-status-icon/)
  assert.match(quickChipsSource, /map-chip-status-icon-time/)
  assert.match(quickChipsSource, /map-chip-status-icon-star/)
  assert.doesNotMatch(quickChipsSource, /map-chip-status-icon-review/)
  assert.match(quickChipsSource, /map-chip-status-\$\{item\.icon\}/)
  assert.ok(cssRuleBodies(styles, '.map-chip-status-icon').some((rule) => /width:\s*20px;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-icon').some((rule) => /fill:\s*currentcolor;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-icon-mark').some((rule) => /stroke:\s*var\(--ait-color-gray-0\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-icon-time').some((rule) => /color:\s*var\(--ait-color-gray-500\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-icon-star').some((rule) => /color:\s*var\(--map-chip-accent\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-star').some((rule) => /--map-chip-accent:\s*#ff6b6b;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-active').some((rule) => /outline:\s*2px solid color-mix\(in srgb, var\(--map-chip-accent\) 28%, transparent\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-active').some((rule) => /background:\s*color-mix\(in srgb, var\(--map-chip-accent\) 14%, var\(--ait-color-gray-0\)\);/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.map-chip-status-label-hidden').some((rule) => /clip:\s*rect\(0 0 0 0\);/.test(rule)))
})

test('Explore styles stay isolated from admin route styles', () => {
  const styles = appCssSource()
  const adminStyles = adminShopCssSource()
  const exploreStyles = exploreSearchCssSource()

  assert.match(styles, /\.map-llm-fab/)
  assert.doesNotMatch(adminStyles, /map-llm-/)
  assert.doesNotMatch(exploreStyles, /word-break:\s*break-word;/)
})

test('Explore map buttons use consistent icon sizing and refresh affordance', () => {
  const source = explorePageSource()
  const styles = appCssSource()
  const filterIconRules = cssRuleBodies(styles, '.map-search-row .map-filter-button svg')
  const areaIconRules = cssRuleBodies(styles, '.map-area-search-icon')
  const controlIconRules = cssRuleBodies(styles, '.map-control-icon')

  assert.match(source, /className="map-area-search-icon"/)
  assert.ok(filterIconRules.some((rule) => /width:\s*22px;/.test(rule) && /height:\s*22px;/.test(rule)))
  assert.ok(areaIconRules.some((rule) => /width:\s*16px;/.test(rule) && /height:\s*16px;/.test(rule)))
  assert.ok(controlIconRules.some((rule) => /width:\s*22px;/.test(rule) && /height:\s*22px;/.test(rule)))
})

test('Explore map CSS follows style rules for changed icon and control declarations', () => {
  const styles = appCssSource()
  const searchIconRules = cssRuleBodies(styles, '.map-search-field svg')
  const areaIconRules = cssRuleBodies(styles, '.map-area-search-icon')
  const aiFabRules = cssRuleBodies(styles, '.map-llm-fab')

  assert.ok(searchIconRules.some((rule) => /stroke:\s*currentcolor;/.test(rule)))
  assert.ok(areaIconRules.some((rule) => /stroke:\s*currentcolor;/.test(rule)))
  assert.ok(aiFabRules.some((rule) => /bottom:\s*calc\(var\(--map-control-bottom, 96px\) \+ var\(--map-control-stack-height, 98px\) \+ var\(--map-control-size, 48px\) \+ \(var\(--map-control-gap, 10px\) \* 2\)\);/.test(rule)))
})

test('Explore map controls remain visible before map ready and use centered list icon', () => {
  const source = explorePageSource()
  const mapSource = shopMapSource()
  const overlayControlsSource = mapOverlayControlsSource()
  const styles = appCssSource()
  const zoomButtonRules = cssRuleBodies(styles, '.map-zoom-button')
  const zoomIconRules = cssRuleBodies(styles, '.map-zoom-icon')
  const listIconRules = cssRuleBodies(styles, '.map-list-fab-icon')
  const listControlIconRules = cssRuleBodies(styles, '.map-list-fab .map-control-icon')
  const chipIconRules = cssRuleBodies(styles, '.map-chip-status-icon')

  assert.doesNotMatch(source, /&& mapReady \? \(/)
  assert.doesNotMatch(source, /<strong>\{isListSheetOpen \?/)
  assert.match(mapSource, /className="map-zoom-icon"/)
  assert.match(overlayControlsSource, /className="map-list-fab-list-icon map-control-icon"/)
  assert.ok(listIconRules.some((rule) => /align-items:\s*center;/.test(rule)))
  assert.ok(listIconRules.some((rule) => /width:\s*19px;/.test(rule) && /height:\s*19px;/.test(rule)))
  assert.ok(listControlIconRules.some((rule) => /width:\s*19px;/.test(rule) && /height:\s*19px;/.test(rule)))
  assert.ok(chipIconRules.some((rule) => /width:\s*20px;/.test(rule) && /height:\s*20px;/.test(rule)))
  assert.ok(zoomButtonRules.some((rule) => /font-size:\s*0;/.test(rule)))
  assert.ok(zoomIconRules.some((rule) => /width:\s*24px;/.test(rule) && /height:\s*24px;/.test(rule)))
})
