import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const routerSource = () => fs.readFileSync(new URL('../src/app/router.tsx', import.meta.url), 'utf8')
const redirectSource = () => fs.readFileSync(new URL('../src/app/ShopRouteRedirect.tsx', import.meta.url), 'utf8')
const exploreSource = () => fs.readFileSync(new URL('../src/pages/ExplorePage.tsx', import.meta.url), 'utf8')
const supplementSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapDetailSupplementSections.tsx', import.meta.url), 'utf8')
const reviewStationSource = () => fs.readFileSync(new URL('../src/pages/explore/MapReviewStation.tsx', import.meta.url), 'utf8')
const tdsFacadeSource = () => fs.readFileSync(new URL('../src/shared/ui/tdsMobile/apps-in-toss.tsx', import.meta.url), 'utf8')
const stylesSource = () => fs.readFileSync(new URL('../src/styles/explore-search.css', import.meta.url), 'utf8')

test('legacy shop detail routes redirect into the explore detail sheet instead of loading ShopPage UI', () => {
  const router = routerSource()
  const redirect = redirectSource()

  assert.doesNotMatch(router, /ShopPage/)
  assert.match(router, /path: '\/shop\/detail\/:shopId'[\s\S]*?<ShopRouteRedirect/)
  assert.match(redirect, /`\/explore\?shopId=\$\{parsedShopId\}&sheet=expanded`/)
})

test('explore review station creates Swagger shop reviews from the selected shop sheet', () => {
  const explore = exploreSource()
  const supplement = supplementSource()
  const station = reviewStationSource()
  const tdsFacade = tdsFacadeSource()
  const styles = stylesSource()

  assert.match(explore, /import \{ createShopReview, deleteShopReview, listShopReviews, updateShopReview \} from '\.\.\/shared\/api\/shopReviews'/)
  assert.match(explore, /type SheetMode = 'peek' \| 'expanded' \| 'review'/)
  assert.match(explore, /sheetParam === 'review'/)
  assert.match(explore, /const reviewListQuery = useQuery\(\{/)
  assert.match(explore, /queryFn: \(\) => listShopReviews/)
  assert.match(explore, /const reviewUpdateMutation = useMutation\(\{/)
  assert.match(explore, /return updateShopReview\(shopId, reviewId, payload, authToken\)/)
  assert.match(explore, /const reviewDeleteMutation = useMutation\(\{/)
  assert.match(explore, /return deleteShopReview\(shopId, reviewId, authToken\)/)
  assert.match(explore, /<MapReviewStation/)
  assert.match(explore, /review=\{editingReview\}/)
  assert.match(explore, /reviewUpdateMutation\.mutate\(\{[\s\S]*?reviewId: editingReview\.id,[\s\S]*?payload,/)
  assert.match(explore, /reviewCreateMutation\.mutate\(\{ shopId: detailShop\.id, payload: payload as CreateShopReviewPayload \}\)/)
  assert.match(supplement, /reviewPage\?: PageResponse<ShopReview> \| null/)
  assert.match(supplement, /currentUserId != null && review\.authorUserId === currentUserId/)
  assert.match(supplement, /onEditReview\?\.\(review\)/)
  assert.match(supplement, /onDeleteReview\?\.\(deleteConfirmReview\)/)
  assert.match(supplement, /<Modal[\s\S]*?리뷰를 삭제할까요\?/)
  assert.match(station, /import \{ useBlocker \} from 'react-router-dom'/)
  assert.match(station, /import \{ Button, IconButton, Modal, Rating, Top \} from '@aniwhere\/tds-mobile'/)
  assert.match(station, /review\?: ShopReview \| null/)
  assert.match(station, /const existingReviewImages = review\?\.images \?\? \[\]/)
  assert.match(station, /existingReviewImages\.length > 0/)
  assert.match(station, /isEditing \? '리뷰 수정하기' : '리뷰 작성하기'/)
  assert.match(station, /accept="image\/\*"/)
  assert.match(station, /MAX_REVIEW_IMAGES = 5/)
  assert.match(station, /const hasDraft = isEditing \? hasChanges : rating > 0 \|\| normalizedContent\.length > 0 \|\| images\.length > 0/)
  assert.match(station, /useBlocker\(\(\{ currentLocation, nextLocation \}\) =>/)
  assert.match(station, /<IconButton[\s\S]*?name="icon-arrow-left-mono"[\s\S]*?onClick=\{requestClose\}/)
  assert.match(station, /<Top[\s\S]*?Top\.TitleParagraph[\s\S]*?리뷰 수정하기[\s\S]*?리뷰 작성하기/)
  assert.match(station, /const isLeaveConfirmOpen = leaveConfirmOpen \|\| blocker\.state === 'blocked'/)
  assert.match(station, /<Modal open=\{isLeaveConfirmOpen\}/)
  assert.match(station, /allowNavigationRef\.current = true/)
  assert.match(station, /onSubmit\(\{[\s\S]*rating,[\s\S]*content: normalizedContent,[\s\S]*images\.length > 0 \? \{ images: images\.map\(\(image\) => image\.file\) \} : \{\}/)
  assert.doesNotMatch(station, /map-review-station-back"/)
  assert.doesNotMatch(station, /map-review-station-title/)
  assert.match(tdsFacade, /IconButton/)
  assert.match(tdsFacade, /Modal/)
  assert.match(tdsFacade, /Rating/)
  assert.match(styles, /\.map-review-station\b/)
  assert.match(styles, /\.map-surface-sheet-review \.map-zoom-control/)
  assert.match(styles, /\.map-review-station \{[\s\S]*?z-index:\s*1300;/)
  assert.match(styles, /\.map-review-leave-modal\b/)
  assert.match(styles, /\.map-place-review-actions\b/)
  assert.match(styles, /\.map-review-existing-photos\b/)
  assert.doesNotMatch(styles, /shop-detail-favorite-button/)
})
