import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const routerSource = () => fs.readFileSync(new URL('../src/app/router.tsx', import.meta.url), 'utf8')
const redirectSource = () => fs.readFileSync(new URL('../src/app/ShopRouteRedirect.tsx', import.meta.url), 'utf8')
const exploreSource = () => fs.readFileSync(new URL('../src/pages/ExplorePage.tsx', import.meta.url), 'utf8')
const supplementSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapDetailSupplementSections.tsx', import.meta.url), 'utf8')
const reviewStationSource = () => fs.readFileSync(new URL('../src/pages/explore/MapReviewStation.tsx', import.meta.url), 'utf8')
const tdsFacadeSource = () => fs.readFileSync(new URL('../src/shared/ui/tdsMobile/apps-in-toss.tsx', import.meta.url), 'utf8')
const stylesSource = () => fs.readFileSync(new URL('../src/styles/explore-search.css', import.meta.url), 'utf8')

test('legacy shop detail routes redirect into the explore detail sheet instead of loading ShopPage UI', () => {
  const router = routerSource()
  const redirect = redirectSource()

  assert.doesNotMatch(router, /ShopPage/)
  assert.match(router, /path: '\/shop\/detail\/:shopId'[\s\S]*?<ShopRouteRedirect/)
  assert.match(redirect, /`\/explore\?shopId=\$\{parsedShopId\}&sheet=expanded`/)
})

test('explore review station creates Swagger shop reviews from the selected shop sheet', () => {
  const explore = exploreSource()
  const supplement = supplementSource()
  const station = reviewStationSource()
  const tdsFacade = tdsFacadeSource()
  const styles = stylesSource()

  assert.match(explore, /import \{ createShopReview, deleteShopReview, listShopReviews, updateShopReview \} from '\.\.\/shared\/api\/shopReviews'/)
  assert.match(explore, /type SheetMode = 'peek' \| 'expanded' \| 'review'/)
  assert.match(explore, /sheetParam === 'review'/)
  assert.match(explore, /const reviewListQuery = useQuery\(\{/)
  assert.match(explore, /queryFn: \(\) => listShopReviews/)
  assert.match(explore, /const reviewUpdateMutation = useMutation\(\{/)
  assert.match(explore, /return updateShopReview\(shopId, reviewId, payload, authToken\)/)
  assert.match(explore, /const reviewDeleteMutation = useMutation\(\{/)
  assert.match(explore, /return deleteShopReview\(shopId, reviewId, authToken\)/)
  assert.match(explore, /const openCreateReviewStation = \(\) => openReviewStation\(null\)/)
  assert.match(explore, /const openEditReviewStation = \(review: ShopReview\) => openReviewStation\(review\)/)
  assert.match(explore, /onStartReview=\{openCreateReviewStation\}/)
  assert.match(explore, /onEditReview=\{openEditReviewStation\}/)
  assert.doesNotMatch(explore, /onStartReview=\{openReviewStation\}/)
  assert.match(explore, /<MapReviewStation/)
  assert.match(explore, /review=\{editingReview\}/)
  assert.match(explore, /reviewUpdateMutation\.mutate\(\{[\s\S]*?reviewId: editingReview\.id,[\s\S]*?payload,/)
  assert.match(explore, /reviewCreateMutation\.mutate\(\{ shopId: detailShop\.id, payload: payload as CreateShopReviewPayload \}\)/)
  assert.match(supplement, /reviewPage\?: PageResponse<ShopReview> \| null/)
  assert.match(supplement, /currentUserId != null && review\.authorUserId === currentUserId/)
  assert.match(supplement, /onEditReview\?\.\(review\)/)
  assert.match(supplement, /onDeleteReview\?\.\(deleteConfirmReview\)/)
  assert.match(supplement, /<Modal[\s\S]*?리뷰를 삭제할까요\?/)
  assert.match(station, /import \{ useBlocker \} from 'react-router-dom'/)
  assert.match(station, /import \{ Button, Modal, Rating \} from '@aniwhere\/tds-mobile'/)
  assert.match(station, /review\?: ShopReview \| null/)
  assert.match(station, /const existingReviewImages = review\?\.images \?\? \[\]/)
  assert.match(station, /existingReviewImages\.length > 0/)
  assert.match(station, /<header className="map-review-shop-summary">/)
  assert.doesNotMatch(station, /shopCategoryLabel/)
  assert.match(station, /const submitLabel = isEditing \? '수정 완료' : '작성 완료'/)
  assert.match(station, /\{submitLabel\}/)
  assert.match(station, /<span className="map-review-rating-question">방문이 어떠셨나요\?<\/span>/)
  assert.match(station, /placeholder="리뷰를 10자 이상 작성해 주세요\."/)
  assert.match(station, /accept="image\/\*"/)
  assert.match(station, /MAX_REVIEW_IMAGES = 5/)
  assert.match(station, /const handleRatingChange = \(nextRating: number\) => \{[\s\S]*?setLocalError\(null\)/)
  assert.match(station, /const handleContentChange = \(nextContent: string\) => \{[\s\S]*?setLocalError\(null\)/)
  assert.match(station, /onValueChange=\{handleRatingChange\}/)
  assert.match(station, /onChange=\{\(event\) => handleContentChange\(event\.target\.value\)\}/)
  assert.match(station, /const canSubmit =[\s\S]*?rating > 0 && normalizedContent\.length > 0/)
  assert.match(station, /normalizedContent\.length < MIN_REVIEW_CONTENT_LENGTH/)
  assert.match(station, /const hasDraft = isEditing \? hasChanges : rating > 0 \|\| normalizedContent\.length > 0 \|\| images\.length > 0/)
  assert.match(station, /useBlocker\(\(\{ currentLocation, nextLocation \}\) =>/)
  assert.doesNotMatch(station, /<IconButton/)
  assert.doesNotMatch(station, /icon-arrow-left-mono/)
  assert.doesNotMatch(station, /<Top/)
  assert.match(station, /리뷰 작성을 그만할까요\?/)
  assert.match(station, /지금까지 입력한 내용은 저장되지 않아요\./)
  assert.match(station, /그만하기/)
  assert.doesNotMatch(station, /작성 중인 리뷰를 나갈까요/)
  assert.match(station, /const isLeaveConfirmOpen = blocker\.state === 'blocked'/)
  assert.match(station, /<Modal open=\{isLeaveConfirmOpen\}/)
  assert.match(station, /allowNavigationRef\.current = true/)
  assert.match(station, /onSubmit\(\{[\s\S]*rating,[\s\S]*content: normalizedContent,[\s\S]*images\.length > 0 \? \{ images: images\.map\(\(image\) => image\.file\) \} : \{\}/)
  assert.doesNotMatch(station, /map-review-station-back"/)
  assert.doesNotMatch(station, /map-review-station-title/)
  assert.match(tdsFacade, /Modal/)
  assert.match(tdsFacade, /Rating/)
  assert.match(styles, /\.map-review-station\b/)
  assert.match(styles, /\.map-surface-sheet-review \.map-zoom-control/)
  assert.match(styles, /\.map-review-station \{[\s\S]*?z-index:\s*1300;/)
  assert.match(styles, /\.map-review-shop-summary \{[\s\S]*?justify-content:\s*center;/)
  assert.match(styles, /\.map-review-shop-summary strong \{[\s\S]*?font-size:\s*var\(--ait-font-size-title-md\);/)
  assert.doesNotMatch(styles, /\.map-review-shop-summary span/)
  assert.doesNotMatch(styles, /\.map-review-photo-help/)
  assert.match(styles, /\.map-review-rating-field \{[\s\S]*?justify-items:\s*center;/)
  assert.match(styles, /\.map-review-leave-modal\b/)
  assert.match(styles, /\.map-place-review-actions\b/)
  assert.match(styles, /\.map-review-existing-photos\b/)
  assert.doesNotMatch(styles, /shop-detail-favorite-button/)
})
