import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const routerSource = () => fs.readFileSync(new URL('../src/app/router.tsx', import.meta.url), 'utf8')
const redirectSource = () => fs.readFileSync(new URL('../src/app/ShopRouteRedirect.tsx', import.meta.url), 'utf8')
const exploreSource = () => fs.readFileSync(new URL('../src/pages/ExplorePage.tsx', import.meta.url), 'utf8')
const supplementSource = () =>
  fs.readFileSync(new URL('../src/pages/explore/MapDetailSupplementSections.tsx', import.meta.url), 'utf8')
const reviewStationSource = () => fs.readFileSync(new URL('../src/pages/explore/MapReviewStation.tsx', import.meta.url), 'utf8')
const tdsFacadeSource = () => fs.readFileSync(new URL('../src/shared/ui/tdsMobile/apps-in-toss.tsx', import.meta.url), 'utf8')
const stylesSource = () => fs.readFileSync(new URL('../src/styles/explore-search.css', import.meta.url), 'utf8')

test('legacy shop detail routes redirect into the explore detail sheet instead of loading ShopPage UI', () => {
  const router = routerSource()
  const redirect = redirectSource()

  assert.doesNotMatch(router, /ShopPage/)
  assert.match(router, /path: '\/shop\/detail\/:shopId'[\s\S]*?<ShopRouteRedirect/)
  assert.match(redirect, /`\/explore\?shopId=\$\{parsedShopId\}&sheet=expanded`/)
})

test('explore review station creates Swagger shop reviews from the selected shop sheet', () => {
  const explore = exploreSource()
  const supplement = supplementSource()
  const station = reviewStationSource()
  const tdsFacade = tdsFacadeSource()
  const styles = stylesSource()

  assert.match(explore, /createShopReview/)
  assert.match(explore, /deleteShopReview/)
  assert.match(explore, /likeShopReview/)
  assert.match(explore, /listShopReviews/)
  assert.match(explore, /unlikeShopReview/)
  assert.match(explore, /updateShopReview/)
  assert.match(explore, /from '\.\.\/shared\/api\/shopReviews'/)
  assert.match(explore, /type SheetMode = 'peek' \| 'expanded' \| 'review'/)
  assert.match(explore, /sheetParam === 'review'/)
  assert.match(explore, /const reviewListQuery = useQuery\(\{/)
  assert.match(explore, /queryFn: \(\) => listShopReviews/)
  assert.match(explore, /const reviewUpdateMutation = useMutation\(\{/)
  assert.match(explore, /return updateShopReview\(shopId, reviewId, payload, authToken\)/)
  assert.match(explore, /const reviewDeleteMutation = useMutation\(\{/)
  assert.match(explore, /return deleteShopReview\(shopId, reviewId, authToken\)/)
  assert.match(explore, /const reviewLikeMutation = useMutation\(\{/)
  assert.match(explore, /nextLiked \? likeShopReview\(shopId, reviewId, authToken\) : unlikeShopReview\(shopId, reviewId, authToken\)/)
  assert.match(explore, /setFavoriteToast\('리뷰 신고 기능은 준비 중이에요\.'\)/)
  assert.match(explore, /const openCreateReviewStation = \(\) => openReviewStation\(null\)/)
  assert.match(explore, /const openEditReviewStation = \(review: ShopReview\) => openReviewStation\(review\)/)
  assert.match(explore, /onStartReview=\{openCreateReviewStation\}/)
  assert.match(explore, /onEditReview=\{openEditReviewStation\}/)
  assert.doesNotMatch(explore, /onStartReview=\{openReviewStation\}/)
  assert.match(explore, /<MapReviewStation/)
  assert.match(explore, /review=\{editingReview\}/)
  assert.match(explore, /reviewUpdateMutation\.mutate\(\{[\s\S]*?reviewId: editingReview\.id,[\s\S]*?payload,/)
  assert.match(explore, /reviewCreateMutation\.mutate\(\{ shopId: detailShop\.id, payload: payload as CreateShopReviewPayload \}\)/)
  assert.match(supplement, /reviewPage\?: PageResponse<ShopReview> \| null/)
  assert.match(supplement, /currentUserNickname\?: string \| null/)
  assert.match(supplement, /currentUserId != null && review\.authorUserId === currentUserId/)
  assert.match(supplement, /function formatReviewEditedDate\(value: string\)/)
  assert.match(supplement, /function formatReviewEditedLabel\(value: string\)/)
  assert.match(supplement, /const relativeLabel = formatReviewDate\(value\)/)
  assert.match(supplement, /formatReviewEditedLabel\(review\.updatedAt \?\? review\.createdAt\)/)
  assert.match(supplement, /function isReviewEdited\(review: ShopReview\)/)
  assert.match(supplement, /className="map-place-review-owner-badge"/)
  assert.match(supplement, /내가 쓴 리뷰예요/)
  assert.match(supplement, /에 수정됨/)
  assert.match(supplement, /currentUserEmojiIconFilename\?: string \| null/)
  assert.match(supplement, /review\.authorEmojiIconFilename \?\? \(isMyReview \? currentUserEmojiIconFilename : null\)/)
  assert.match(supplement, /className="map-place-review-avatar"/)
  assert.match(supplement, /className="map-place-review-avatar map-place-review-avatar-fallback"/)
  assert.match(supplement, /onEditReview\(review\)/)
  assert.match(supplement, /onDeleteReview\?\.\(deleteConfirmReview\)/)
  assert.match(supplement, /onToggleReviewLike\?\.\(review, !review\.likedByMe\)/)
  assert.match(supplement, /review\.likedByMe \? '유용해요 취소' : '유용해요'/)
  assert.match(supplement, /review\.likeCount > 0 \? \(/)
  assert.match(supplement, /const isReviewEmpty = !isReviewLoading && reviewErrorMessage == null && reviews\.length === 0/)
  assert.match(supplement, /map-place-review-card-empty/)
  assert.doesNotMatch(supplement, /아직 등록된 리뷰가 없어요/)
  assert.doesNotMatch(supplement, /첫 도움을 기다리고 있어요/)
  assert.doesNotMatch(supplement, /방문 리뷰 \$\{shop\.reviewCount\}개/)
  assert.match(explore, /currentUserNickname=\{currentUser\?\.nickname \?\? null\}/)
  assert.match(supplement, /import \{ Button, Menu, Modal, Rating, Result \} from '@aniwhere\/tds-mobile'/)
  assert.match(supplement, /const reviewPromptName = currentUserNickname\?\.trim\(\) \|\| '방문자'/)
  assert.doesNotMatch(supplement, /const myReview =/)
  assert.match(supplement, /<Result/)
  assert.match(supplement, /title=\{[\s\S]*?<span className="map-place-review-prompt-title">[\s\S]*?<strong>\{reviewPromptName\}님<\/strong>[\s\S]*?<strong>\{shop\.name\}<\/strong>[\s\S]*?다녀오셨나요\?[\s\S]*?<\/span>[\s\S]*?\}/)
  assert.match(supplement, /description="리뷰를 남기면, 검토 후 포인트를 지급해드려요!"/)
  assert.match(supplement, /<Result\.Button/)
  assert.doesNotMatch(supplement, /TOSS_REWARD_COIN_LOTTIE_URL/)
  assert.doesNotMatch(supplement, /Asset\.Lottie/)
  assert.match(supplement, /<span className="map-place-review-coin-icon" aria-hidden="true">[\s\S]*?₩[\s\S]*?<\/span>/)
  assert.match(supplement, /<Result\.Button\s+type="button"\s+onClick=\{onStartReview\}>/)
  assert.match(supplement, /리뷰 남기기/)
  assert.doesNotMatch(supplement, /내 리뷰 수정하기/)
  assert.doesNotMatch(supplement, /이미 남긴 리뷰를 수정할 수 있어요/)
  assert.doesNotMatch(supplement, /평균 별점/)
  assert.doesNotMatch(supplement, /shop\.averageRating/)
  assert.match(supplement, /Menu\.Trigger/)
  assert.match(supplement, /리뷰 신고하기/)
  assert.match(supplement, /onReportReview\?\.\(review\)/)
  assert.match(supplement, /isMyReview\?: boolean/)
  assert.match(supplement, /isMyReview \? \([\s\S]*?수정하기[\s\S]*?삭제하기[\s\S]*?\) : \(/)
  assert.doesNotMatch(supplement, /<div className="map-place-review-actions"/)
  assert.doesNotMatch(supplement, /map-place-review-photo-strip/)
  assert.match(supplement, /const reviewPhotoItems = useMemo/)
  assert.match(supplement, /리뷰를 남기면, 검토 후 포인트를 지급해드려요!/)
  assert.match(supplement, /<Modal[\s\S]*?리뷰를 삭제할까요\?/)
  assert.match(station, /import \{ useBlocker \} from 'react-router-dom'/)
  assert.match(station, /import \{ Button, Modal, Rating \} from '@aniwhere\/tds-mobile'/)
  assert.match(station, /review\?: ShopReview \| null/)
  assert.match(station, /const existingReviewImages = review\?\.images \?\? \[\]/)
  assert.match(station, /const \[hiddenExistingImageIds, setHiddenExistingImageIds\] = useState<Set<string>>\(\(\) => new Set\(\)\)/)
  assert.match(station, /const visibleExistingReviewImages = existingReviewImages\.filter/)
  assert.match(station, /const attachedImageCount = visibleExistingReviewImages\.length \+ images\.length/)
  assert.match(station, /const remainingImageSlots = Math\.max\(0, MAX_REVIEW_IMAGES - attachedImageCount\)/)
  assert.match(station, /const handleRemoveExistingImage = \(targetId: string\) =>/)
  assert.doesNotMatch(station, /<header className="map-review-shop-summary">/)
  assert.match(station, /<span className="map-review-rating-question">[\s\S]*?<strong>\{shop\.name\}<\/strong>\s*<span>의 방문은 어떠셨나요\?<\/span>[\s\S]*?<\/span>/)
  assert.doesNotMatch(station, /shopCategoryLabel/)
  assert.match(station, /const submitLabel = isEditing \? '수정 완료' : '작성 완료'/)
  assert.match(station, /\{submitLabel\}/)
  assert.doesNotMatch(station, /<span className="map-review-rating-question">방문이 어떠셨나요\?<\/span>/)
  assert.match(station, /placeholder="리뷰를 10자 이상 작성해 주세요\."/)
  assert.match(station, /accept="image\/\*"/)
  assert.match(station, /visibleExistingReviewImages\.map\(\(image, index\) =>/)
  assert.match(station, /map-review-photo-preview map-review-photo-preview-existing/)
  assert.match(station, /aria-label=\{`기존 리뷰 사진 삭제`\}/)
  assert.match(station, /disabled=\{attachedImageCount >= MAX_REVIEW_IMAGES\}/)
  assert.match(station, /\{attachedImageCount\}\/\{MAX_REVIEW_IMAGES\}/)
  assert.doesNotMatch(station, /map-review-existing-photos/)
  assert.match(station, /MAX_REVIEW_IMAGES = 5/)
  assert.match(station, /const handleRatingChange = \(nextRating: number\) => \{[\s\S]*?setLocalError\(null\)/)
  assert.match(station, /const handleContentChange = \(nextContent: string\) => \{[\s\S]*?setLocalError\(null\)/)
  assert.match(station, /onValueChange=\{handleRatingChange\}/)
  assert.match(station, /variant="full"/)
  assert.match(station, /onChange=\{\(event\) => handleContentChange\(event\.target\.value\)\}/)
  assert.match(station, /MAX_REVIEW_CONTENT_LENGTH = 800/)
  assert.match(station, /<div className="map-review-content-box">[\s\S]*?<textarea[\s\S]*?<span className="map-review-content-counter">[\s\S]*?\{content\.length\}\/\{MAX_REVIEW_CONTENT_LENGTH\}[\s\S]*?<\/span>[\s\S]*?<\/div>/)
  assert.match(station, /\{content\.length\}\/\{MAX_REVIEW_CONTENT_LENGTH\}/)
  assert.match(station, /const canSubmit =[\s\S]*?rating > 0 && normalizedContent\.length > 0/)
  assert.match(station, /normalizedContent\.length < MIN_REVIEW_CONTENT_LENGTH/)
  assert.match(station, /const hasDraft = isEditing \? hasChanges : rating > 0 \|\| normalizedContent\.length > 0 \|\| attachedImageCount > 0/)
  assert.match(station, /useBlocker\(\(\{ currentLocation, nextLocation \}\) =>/)
  assert.doesNotMatch(station, /<IconButton/)
  assert.doesNotMatch(station, /icon-arrow-left-mono/)
  assert.doesNotMatch(station, /<Top/)
  assert.match(station, /리뷰 작성을 그만할까요\?/)
  assert.match(station, /지금까지 입력한 내용은 저장되지 않아요\./)
  assert.match(station, /그만하기/)
  assert.doesNotMatch(station, /작성 중인 리뷰를 나갈까요/)
  assert.match(station, /const isLeaveConfirmOpen = blocker\.state === 'blocked'/)
  assert.match(station, /<Modal open=\{isLeaveConfirmOpen\}/)
  assert.match(station, /allowNavigationRef\.current = true/)
  assert.match(station, /onSubmit\(\{[\s\S]*rating,[\s\S]*content: normalizedContent,[\s\S]*images\.length > 0 \? \{ images: images\.map\(\(image\) => image\.file\) \} : \{\}/)
  assert.doesNotMatch(station, /map-review-station-back"/)
  assert.doesNotMatch(station, /map-review-station-title/)
  assert.match(tdsFacade, /Modal/)
  assert.match(tdsFacade, /Menu/)
  assert.match(tdsFacade, /Rating/)
  assert.match(tdsFacade, /Result/)
  assert.match(styles, /\.map-review-station\b/)
  assert.match(styles, /\.map-surface-sheet-review \.map-zoom-control/)
  assert.match(styles, /\.map-review-station \{[\s\S]*?z-index:\s*1300;/)
  assert.doesNotMatch(styles, /\.map-review-shop-summary\b/)
  assert.match(styles, /\.map-review-rating-question strong \{[\s\S]*?font-weight:\s*900;/)
  assert.doesNotMatch(styles, /\.map-review-photo-help/)
  assert.match(styles, /\.map-review-station-body \{[\s\S]*?gap:\s*var\(--ait-space-9\);[\s\S]*?padding:\s*max\(14px, env\(safe-area-inset-top\)\) var\(--ait-space-8\) 96px;/)
  assert.match(styles, /\.map-review-rating-field \{[\s\S]*?justify-items:\s*center;/)
  assert.match(styles, /\.map-review-rating-field \{[\s\S]*?gap:\s*var\(--ait-space-12\) !important;/)
  assert.match(styles, /\.map-review-rating-field \{[\s\S]*?padding:\s*var\(--ait-space-8\) 0 var\(--ait-space-2\);/)
  assert.match(styles, /\.map-place-review-result \{[\s\S]*?gap:\s*var\(--ait-space-2\);[\s\S]*?padding:\s*var\(--ait-space-6\) var\(--ait-space-5\);/)
  assert.match(styles, /\.map-place-review-card-empty \{[\s\S]*?justify-content:\s*center;/)
  assert.match(styles, /\.map-place-review-card-empty \{[\s\S]*?min-height:\s*clamp\(280px,\s*46dvh,\s*430px\);/)
  assert.match(styles, /\.map-place-review-card \.map-place-review-result \{[\s\S]*?padding:\s*var\(--ait-space-6\) var\(--ait-space-5\) !important;/)
  assert.match(styles, /\.map-place-review-prompt-title \{[\s\S]*?overflow:\s*hidden;[\s\S]*?font-size:\s*var\(--ait-font-size-body-md\);[\s\S]*?text-overflow:\s*ellipsis;[\s\S]*?white-space:\s*nowrap;/)
  assert.match(styles, /\.map-place-review-prompt-title strong \{[\s\S]*?color:\s*var\(--ait-color-gray-900\);/)
  assert.match(styles, /\.map-place-review-result \.ait-result-description \{[\s\S]*?font-size:\s*var\(--ait-font-size-body-sm\);[\s\S]*?line-height:\s*1\.4;/)
  assert.match(styles, /\.map-place-review-result \.ait-result-button \{[^}]*min-height:\s*42px;[^}]*gap:\s*var\(--ait-space-2\);[^}]*font-size:\s*var\(--ait-font-size-body-sm\);[^}]*\}/)
  assert.match(styles, /\.map-place-review-result \.tds-mobile-button__content \{[^}]*gap:\s*var\(--ait-space-2\);[^}]*\}/)
  assert.match(styles, /\.map-review-content-field \{[\s\S]*?margin-bottom:\s*var\(--ait-space-6\);/)
  assert.match(styles, /\.map-review-content-box \{[\s\S]*?position:\s*relative;/)
  assert.match(styles, /\.map-review-textarea \{[\s\S]*?height:\s*196px;[\s\S]*?min-height:\s*196px;[\s\S]*?padding:\s*16px 16px 34px;/)
  assert.match(styles, /\.map-review-content-counter \{[\s\S]*?position:\s*absolute;[\s\S]*?right:\s*16px;[\s\S]*?bottom:\s*14px;/)
  assert.doesNotMatch(styles, /\.map-review-photo-head\b/)
  assert.match(styles, /\.map-review-photo-strip \{[\s\S]*?align-items:\s*center;[\s\S]*?gap:\s*var\(--ait-space-4\);/)
  assert.match(styles, /\.map-review-photo-count\b/)
  assert.match(styles, /\.map-review-photo-add,[\s\S]*?\.map-review-photo-preview \{[\s\S]*?width:\s*88px;[\s\S]*?height:\s*88px;/)
  assert.match(styles, /\.map-review-photo-preview-existing\b/)
  assert.match(styles, /\.map-review-photo-add \{[\s\S]*?border:\s*2px solid #f59e0b;[\s\S]*?background:\s*var\(--ait-color-gray-0\);/)
  assert.match(styles, /\.map-review-photo-preview button \{[\s\S]*?width:\s*22px;[\s\S]*?height:\s*22px;/)
  assert.match(styles, /\.map-review-leave-modal\b/)
  assert.match(styles, /\.map-place-review-actions\b/)
  assert.match(styles, /\.map-place-review-avatar\b/)
  assert.match(styles, /\.map-place-review-images \{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/)
  assert.doesNotMatch(styles, /\.map-place-review-photo-strip\b/)
  assert.doesNotMatch(styles, /\.map-place-review-photo-thumb\b/)
  assert.match(styles, /\.map-place-review-more-button\b/)
  assert.match(styles, /\.map-place-review-like\b/)
  assert.match(styles, /\.map-place-review-like \{[\s\S]*?gap:\s*var\(--ait-space-3\);/)
  assert.match(styles, /\.map-place-review-text-wrap \+ \.map-place-review-like-row \{[\s\S]*?margin-top:\s*var\(--ait-space-3\);/)
  assert.match(styles, /\.map-place-review-like-count\b/)
  assert.doesNotMatch(styles, /\.map-review-existing-photos\b/)
  assert.doesNotMatch(styles, /shop-detail-favorite-button/)
})
