import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const searchPageSource = () => fs.readFileSync(new URL('../src/pages/SearchPage.tsx', import.meta.url), 'utf8')
const mapSearchFieldShellSource = () =>
  fs.readFileSync(new URL('../src/shared/ui/MapSearchFieldShell.tsx', import.meta.url), 'utf8')
const filterSheetSource = () => fs.readFileSync(new URL('../src/shared/ui/SearchFilterSheet.tsx', import.meta.url), 'utf8')
const searchCopySource = () => fs.readFileSync(new URL('../src/shared/lib/searchCopy.ts', import.meta.url), 'utf8')
const appCssSource = () =>
  ['../src/App.css', '../src/styles/explore-search.css']
    .map((path) => fs.readFileSync(new URL(path, import.meta.url), 'utf8'))
    .join('\n')

const cssRuleBodies = (css: string, selector: string) => {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const matches = css.matchAll(new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\}`, 'g'))

  return Array.from(matches, (match) => match[1])
}

const cssRuleBody = (css: string, selector: string) => {
  const matches = cssRuleBodies(css, selector)

  assert.ok(matches.length > 0, `${selector} rule not found`)
  return matches[0]
}

test('SearchPage is an input route that sends submitted searches to the explore list', () => {
  const source = searchPageSource()

  assert.match(source, /function buildExploreSearchHref/)
  assert.match(source, /next\.set\('view', 'list'\)/)
  assert.match(source, /scope === 'work'[\s\S]*next\.set\('scope', 'work'\)/)
  assert.match(source, /next\.set\('keyword', trimmed\)/)
  assert.match(source, /return `\/explore\?\$\{next\.toString\(\)\}`/)
  assert.match(source, /function readSafeReturnTo/)
  assert.match(source, /submitSearchToExplore\(keyword\)/)
  assert.match(source, /navigate\(buildExploreSearchHref\(\{ keyword: trimmed, scope: nextScope, selectedFilters \}\)\)/)
  assert.doesNotMatch(source, /navigate\(buildExploreSearchHref\(\{ keyword: trimmed, scope: nextScope, selectedFilters \}\), \{ replace: true \}\)/)
  assert.match(source, /pushRecentSearchEntry\(trimmed, recentKind\)/)
  assert.doesNotMatch(source, /getShops/)
  assert.doesNotMatch(source, /search-page-results/)
  assert.doesNotMatch(source, /search-result-list/)
  assert.doesNotMatch(source, /search-result-card/)
  assert.doesNotMatch(source, /StatusPill/)
})

test('SearchPage keeps the shared map search field shell without TDS SearchField chrome', () => {
  const source = searchPageSource()
  const shellSource = mapSearchFieldShellSource()
  const styles = appCssSource()
  const copySource = searchCopySource()

  assert.match(copySource, /SHOP_SEARCH_PLACEHOLDER = '작품, 매장명, 지역으로 검색'/)
  assert.match(source, /import \{ Asset \} from '@aniwhere\/tds-mobile'/)
  assert.match(source, /import \{ MapSearchFieldForm \} from '\.\.\/shared\/ui\/MapSearchFieldShell'/)
  assert.match(source, /<MapSearchFieldForm/)
  assert.doesNotMatch(source, /<MapSearchFieldForm[\s\S]*autoFocus/)
  assert.doesNotMatch(shellSource, /autoFocus/)
  assert.match(source, /value=\{keyword\}/)
  assert.match(source, /onChange=\{setKeyword\}/)
  assert.doesNotMatch(source, /onClear=/)
  assert.doesNotMatch(shellSource, /search-screen-clear-button|검색어 지우기/)
  assert.doesNotMatch(styles, /\.search-screen-clear-button\b/)
  assert.match(shellSource, /<form className="search-screen-form search-screen-bar map-search-field" onSubmit=\{onSubmit\}>/)
  assert.match(shellSource, /<input/)
  assert.match(shellSource, /className="search-screen-input"/)
  assert.match(shellSource, /placeholder=\{SHOP_SEARCH_PLACEHOLDER\}/)
  assert.match(shellSource, /type="search"/)
  assert.match(source, /className="search-filter-button map-filter-button"/)
  assert.doesNotMatch(source, /import \{ SearchField \} from '@aniwhere\/tds-mobile'/)
  assert.doesNotMatch(source, /<SearchField/)
  assert.ok(
    cssRuleBodies(styles, '.search-screen-form.map-search-field .search-screen-input').some((rule) =>
      /font-size:\s*16px;/.test(rule),
    ),
  )
  assert.ok(cssRuleBodies(styles, '.search-screen-form.map-search-field .search-screen-input::-webkit-search-cancel-button').some((rule) => /display:\s*none;/.test(rule)))
  assert.ok(cssRuleBodies(styles, '.search-screen-form.map-search-field .search-screen-input::-webkit-search-decoration').some((rule) => /display:\s*none;/.test(rule)))
})

test('SearchPage uses the explore list route shell instead of a dedicated search screen surface', () => {
  const source = searchPageSource()
  const styles = appCssSource()

  assert.match(source, /<main className="map-page-shell">/)
  assert.match(source, /className="map-page map-page-list-mode"/)
  assert.match(source, /className="map-list-view/)
  assert.match(source, /<div className="map-list-view-top">/)
  assert.match(source, /<section className="map-results-list-panel"/)
  assert.doesNotMatch(source, /className="search-result-head"/)
  assert.doesNotMatch(source, /className="search-screen-shell"/)
  assert.doesNotMatch(source, /className="search-screen search-screen-v2"/)
  assert.doesNotMatch(source, /className="search-screen-top search-screen-top-v2"/)
  assert.doesNotMatch(source, /className="search-screen-content search-screen-content-v2"/)
  assert.doesNotMatch(styles, /\.search-screen-v2\s*\{/)
  assert.doesNotMatch(styles, /\.search-screen-top-v2\s*\{/)
  assert.doesNotMatch(styles, /\.search-screen-content-v2\s*\{/)
  assert.doesNotMatch(styles, /\.search-screen-shell\b/)
  assert.doesNotMatch(styles, /\.search-route-navigation\b/)
})

test('SearchPage preserves filter editing but leaves selected filter chips to explore results', () => {
  const source = searchPageSource()
  const filterSheet = filterSheetSource()

  assert.match(source, /parseShopFilters\(searchParams\)/)
  assert.match(source, /countShopFilters\(selectedFilters\)/)
  assert.match(source, /navigate\(buildExploreSearchHref\(\{ keyword, scope: currentSearchScope, selectedFilters: nextFilters \}\), \{ replace: true \}\)/)
  assert.match(source, /<SearchFilterSheet/)
  assert.match(source, /keyword=\{keyword\}/)
  assert.doesNotMatch(source, /keyword=\{currentKeyword\}/)
  assert.match(source, /selectedFilters=\{selectedFilters\}/)
  assert.match(source, /onApplyFilters=\{applyFilters\}/)
  assert.doesNotMatch(source, /setSearchParams\(writeShopFilters\(searchParams, nextFilters\)/)
  assert.doesNotMatch(source, /AppliedFilterChips/)
  assert.match(filterSheet, /const facetParams = \{ includeRegions: true, includeCategories: true, includeWorkTypes: true, includeSorts: true \}/)
  assert.match(filterSheet, /sort: current\.sort === sort\.value \? undefined : sort\.value/)
})

test('SearchPage back action returns to the safe caller route before falling back to history', () => {
  const source = searchPageSource()

  assert.match(source, /const safeReturnTo = readSafeReturnTo\(searchParams\.get\('returnTo'\)\)/)
  assert.match(source, /if \(safeReturnTo\) \{[\s\S]*navigate\(safeReturnTo, \{ replace: true \}\)/)
  assert.match(source, /navigate\(-1\)/)
  assert.doesNotMatch(source, /setSearchParams\(next, \{ replace: true \}\)[\s\S]*setKeyword\(''\)/)
})

test('SearchPage recent searches and nearby CTA remain the pre-search content', () => {
  const source = searchPageSource()

  assert.match(source, /const isComposingSearch = compactKeyword\.length > 0/)
  assert.match(source, /readRecentSearchEntries/)
  assert.match(source, /removeRecentSearchEntry/)
  assert.match(source, /clearRecentSearchEntries/)
  assert.match(source, /recentSearches\.map/)
  assert.match(source, /className="search-history-chip-list"/)
  assert.match(source, /className="search-history-clear-all"/)
  assert.match(source, /className="search-history-chip"/)
  assert.match(source, /className="search-history-chip-kind"/)
  assert.match(source, /className="search-history-chip-text"/)
  assert.match(source, /className="search-history-chip-remove applied-filter-chip-close"/)
  assert.match(source, /onClick=\{\(\) => submitSearchToExplore\(item\.keyword, item\.kind \?\? 'shop', item\.kind\)\}/)
  assert.match(source, /onClick=\{\(\) => removeRecentSearchItem\(item\)\}/)
  assert.match(source, /onClick=\{clearAllRecentSearches\}/)
  assert.doesNotMatch(source, /className="search-history-list"/)
  assert.doesNotMatch(source, /className="search-history-item"/)
  assert.match(source, /requestCurrentLocation/)
  assert.match(source, /buildNearbyExploreHref/)
  assert.match(source, /className="search-location-image"/)
  assert.match(source, /src=\{searchLocationGuideUrl\}/)
  assert.match(source, /\{isComposingSearch \? \(/)
})

test('SearchPage folds matching recent searches into the composing autocomplete panel', () => {
  const source = searchPageSource()

  assert.match(source, /type SearchAutocompleteIconKind = SearchAutocompleteKind \| 'RECENT'/)
  assert.match(source, /function SearchAutocompleteLeadingIcon/)
  assert.match(source, /getAutocompleteIconName\(kind: SearchAutocompleteIconKind\)/)
  assert.match(source, /return 'icon-clock-mono'/)
  assert.match(source, /const relatedRecentSearches = recentSearches/)
  assert.match(source, /\.filter\(\(item\) => item\.keyword\.trim\(\)\.toLocaleLowerCase\(\)\.includes\(normalizedCompactKeyword\)\)/)
  assert.match(source, /\.slice\(0, 3\)/)
  assert.match(source, /relatedRecentSearches\.length > 0 \? \(/)
  assert.match(source, /className="search-autocomplete-history"/)
  assert.match(source, /className="search-autocomplete-history-item"/)
  assert.match(source, /<SearchAutocompleteLeadingIcon kind="RECENT" \/>/)
  assert.match(source, /onClick=\{\(\) => submitSearchToExplore\(item\.keyword, item\.kind \?\? 'shop', item\.kind\)\}/)
})

test('SearchPage shows server autocomplete suggestions for shops and works', () => {
  const source = searchPageSource()

  assert.match(source, /import \{ getSearchAutocomplete \} from '\.\.\/shared\/api\/search'/)
  assert.match(source, /useQuery/)
  assert.match(source, /queryKey: \['search-autocomplete', currentSearchScope, compactKeyword\]/)
  assert.match(source, /const autocompleteScopes = currentSearchScope === 'work' \? \['work', 'shop'\] : \['shop', 'work'\]/)
  assert.match(source, /Promise\.allSettled\([\s\S]*autocompleteScopes\.map\(\(scope\) => getSearchAutocomplete\(\{ q: compactKeyword, scope, limit: 5 \}\)\),[\s\S]*\)/)
  assert.match(source, /if \(result\.status !== 'fulfilled'\) \{[\s\S]*return \[\][\s\S]*\}/)
  assert.match(source, /result\.value\.items\.map\(\(item\) => \(\{ \.\.\.item, scope \}\)\)/)
  assert.match(source, /enabled: compactKeyword\.length > 0/)
  assert.match(source, /autocompleteSuggestions = autocompleteQuery\.data \?\? \[\]/)
  assert.match(source, /const autocompleteGroupKinds: SearchAutocompleteKind\[\] = currentSearchScope === 'work' \? \['WORK', 'SHOP'\] : \['SHOP', 'WORK'\]/)
  assert.match(source, /const autocompleteGroups: SearchAutocompleteGroup\[\] = autocompleteGroupKinds/)
  assert.match(source, /className="search-autocomplete-panel"/)
  assert.match(source, /className="search-autocomplete-group"/)
  assert.match(source, /className="search-autocomplete-group-title"/)
  assert.match(source, /getAutocompleteGroupTitle\(group\.kind\)/)
  assert.doesNotMatch(source, /getAutocompleteGroupDescription/)
  assert.doesNotMatch(source, /className="search-autocomplete-group-description"/)
  assert.match(source, /className="search-autocomplete-item"/)
  assert.match(source, /className="search-autocomplete-item-main"/)
  assert.match(source, /<SearchAutocompleteLeadingIcon kind=\{item\.kind\} \/>/)
  assert.match(source, /color="currentColor"/)
  assert.match(source, /'icon-store-roof-mono'/)
  assert.match(source, /'icon-book-opened-mono'/)
  assert.match(source, /function getAutocompleteIconSize\(kind: SearchAutocompleteIconKind\)/)
  assert.match(source, /return kind === 'WORK' \? 18 : 20/)
  assert.doesNotMatch(source, /className="search-autocomplete-kind"/)
  assert.doesNotMatch(source, /className="search-autocomplete-helper"/)
  assert.match(source, /onClick=\{\(\) => submitSearchToExplore\(item\.label, item\.scope, item\.kind === 'WORK' \? 'work' : 'shop'\)\}/)
  assert.match(source, /'작품명'/)
  assert.match(source, /'매장명'/)
  assert.doesNotMatch(source, /'작품명 검색'/)
  assert.doesNotMatch(source, /'매장명 검색'/)
  assert.doesNotMatch(source, /'작품으로 취급 매장을 찾습니다'/)
  assert.doesNotMatch(source, /'매장 이름으로 바로 찾습니다'/)
})

test('SearchPage sends clicked work suggestions through work search scope', () => {
  const source = searchPageSource()

  assert.match(source, /const submitSearchToExplore = \(nextKeyword: string, nextScope: SearchScope = 'shop', recentKind\?: RecentSearchKind\) => \{/)
  assert.match(source, /submitSearchToExplore\(keyword\)/)
  assert.match(source, /navigate\(buildExploreSearchHref\(\{ keyword: trimmed, scope: nextScope, selectedFilters \}\)\)/)
  assert.match(source, /onClick=\{\(\) => submitSearchToExplore\(item\.label, item\.scope, item\.kind === 'WORK' \? 'work' : 'shop'\)\}/)
})

test('SearchPage autocomplete panel keeps compact ListRow-like mobile rhythm', () => {
  const styles = appCssSource()
  const panelRule = cssRuleBody(styles, '.search-autocomplete-panel')
  const groupRule = cssRuleBody(styles, '.search-autocomplete-group')
  const groupTitleRule = cssRuleBody(styles, '.search-autocomplete-group-title')
  const listRule = cssRuleBody(styles, '.search-autocomplete-list')
  const itemRule = cssRuleBody(styles, '.search-autocomplete-item')
  const itemMainRule = cssRuleBody(styles, '.search-autocomplete-item-main')
  const iconRule = cssRuleBody(styles, '.search-autocomplete-leading-icon')
  const labelRule = cssRuleBody(styles, '.search-autocomplete-label')
  const historyRule = cssRuleBody(styles, '.search-autocomplete-history')

  assert.match(panelRule, /border:\s*1px solid var\(--ait-color-border-strong\);/)
  assert.match(panelRule, /border-radius:\s*var\(--ait-radius-xl\);/)
  assert.match(panelRule, /flex:\s*0 0 auto;/)
  assert.match(groupRule, /display:\s*flex;/)
  assert.match(groupTitleRule, /font-size:\s*var\(--ait-font-size-caption\);/)
  assert.match(listRule, /list-style:\s*none;/)
  assert.match(itemRule, /min-height:\s*52px;/)
  assert.match(itemRule, /justify-content:\s*flex-start;/)
  assert.match(itemRule, /padding:\s*0 var\(--ait-space-6\);/)
  assert.match(itemRule, /text-align:\s*left;/)
  assert.match(itemMainRule, /min-width:\s*0;/)
  assert.match(iconRule, /width:\s*28px;/)
  assert.match(iconRule, /border-radius:\s*var\(--ait-radius-full\);/)
  assert.doesNotMatch(styles, /\.search-autocomplete-leading-icon-shop/)
  assert.doesNotMatch(styles, /\.search-autocomplete-leading-icon-work/)
  assert.match(labelRule, /text-overflow:\s*ellipsis;/)
  assert.match(historyRule, /border-bottom:\s*1px solid var\(--ait-color-border\);/)
})

test('SearchPage recent search and empty location copy use compact mobile text rhythm', () => {
  const source = searchPageSource()
  const styles = appCssSource()
  const historyHeadRule = cssRuleBody(styles, '.search-history-head strong')
  const historyChipListRules = cssRuleBodies(styles, '.search-history-chip-list')
  const historyChipRules = cssRuleBodies(styles, '.search-history-chip')
  const historyChipLabelRule = cssRuleBody(styles, '.search-history-chip-label')
  const historyChipKindRule = cssRuleBody(styles, '.search-history-chip-kind')
  const historyChipTextRule = cssRuleBody(styles, '.search-history-chip-text')
  const historyChipRemoveRule = cssRuleBody(styles, '.search-history-chip-remove')
  const precontentRule = cssRuleBody(styles, '.map-results-sheet-list.search-route-precontent')
  const locationCardRule = cssRuleBody(styles, '.search-location-card')
  const locationCopyRule = cssRuleBody(styles, '.search-location-copy strong')
  const locationButtonRule = cssRuleBody(styles, '.search-location-button')

  assert.match(source, /return kind === 'work' \? '작품' : '매장'/)
  assert.doesNotMatch(source, /return kind === 'work' \? '작품 검색' : '매장 검색'/)
  assert.match(historyHeadRule, /font-size:\s*var\(--ait-font-size-body-md\);/)
  assert.ok(historyChipListRules.some((rule) => /flex-wrap:\s*wrap;/.test(rule)))
  assert.ok(historyChipRules.some((rule) => /min-height:\s*40px;/.test(rule)))
  assert.match(historyChipLabelRule, /font-size:\s*var\(--ait-font-size-body-md\);/)
  assert.match(historyChipLabelRule, /display:\s*inline-flex;/)
  assert.match(historyChipKindRule, /border-radius:\s*var\(--ait-radius-full\);/)
  assert.match(historyChipKindRule, /font-size:\s*var\(--ait-font-size-caption\);/)
  assert.match(historyChipTextRule, /text-overflow:\s*ellipsis;/)
  assert.match(historyChipRemoveRule, /font-size:\s*12px;/)
  assert.match(precontentRule, /gap:\s*var\(--ait-space-12\);/)
  assert.match(locationCardRule, /justify-content:\s*center;/)
  assert.match(locationCardRule, /min-height:\s*340px;/)
  assert.match(locationCopyRule, /font-size:\s*var\(--ait-font-size-body-lg\);/)
  assert.match(locationCopyRule, /font-weight:\s*700;/)
  assert.match(locationButtonRule, /min-width:\s*168px;/)
  assert.match(locationButtonRule, /background:\s*var\(--ait-color-brand\);/)
  assert.match(locationButtonRule, /color:\s*var\(--ait-color-text-inverse\);/)
})
