import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = (path: string) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const routerSource = () => source('../src/app/router.tsx')
const lazyRouteComponentsSource = () => source('../src/app/lazyRouteComponents.tsx')
const homeSource = () => source('../src/pages/HomePage.tsx')
const myPageSource = () => source('../src/pages/MyPage.tsx')
const mainLayoutSource = () => source('../src/shared/ui/MainLayout.tsx')
const appCssSource = () => source('../src/App.css')
const usersApiSource = () => source('../src/shared/api/users.ts')
const shopReviewsApiSource = () => source('../src/shared/api/shopReviews.ts')

test('general users can open their profile from home without admin role', () => {
  const router = routerSource()
  const lazyRoutes = lazyRouteComponentsSource()
  const home = homeSource()
  const mainLayout = mainLayoutSource()
  const styles = appCssSource()

  assert.match(router, /path:\s*'my'[\s\S]*routeElement\(<MyPage \/>/)
  assert.match(lazyRoutes, /export const MyPage = lazy/)
  assert.doesNotMatch(home, /HomeProfileFloatingAction/)
  assert.doesNotMatch(home, /home-profile-floating-action/)
  assert.match(mainLayout, /location\.pathname === '\/my'/)
  assert.match(mainLayout, /hasRouteOwnedNavigation/)
  assert.match(styles, /\.ait-navigation-profile-button/)
  assert.match(styles, /\.ait-navigation-profile-icon/)
  assert.doesNotMatch(styles, /\.home-profile-floating-action/)
  assert.doesNotMatch(styles, /\.home-profile-entry-card/)
})

test('my page uses only exposed swagger profile fields and API-backed edit/activity sections', () => {
  const myPage = myPageSource()
  const styles = appCssSource()
  const usersApi = usersApiSource()
  const shopReviewsApi = shopReviewsApiSource()

  assert.match(usersApi, /export function getMyProfile/)
  assert.match(usersApi, /\/api\/v1\/users\/me/)
  assert.match(usersApi, /export function listMyFavoriteShops/)
  assert.match(usersApi, /\/api\/v1\/users\/me\/favorite-shops/)
  assert.match(usersApi, /export function checkNicknameAvailability/)
  assert.match(usersApi, /export function updateMyNickname/)
  assert.match(shopReviewsApi, /export function listMyReviews/)
  assert.match(shopReviewsApi, /\/api\/v1\/users\/me\/reviews/)

  assert.match(myPage, /getMyProfile/)
  assert.match(myPage, /readAuthSession/)
  assert.match(myPage, /listMyFavoriteShops/)
  assert.match(myPage, /listMyReviews/)
  assert.match(myPage, /checkNicknameAvailability/)
  assert.match(myPage, /updateMyNickname/)
  assert.match(myPage, /updateAuthSessionUser/)
  assert.doesNotMatch(myPage, /SessionCard/)
  assert.doesNotMatch(myPage, /function NicknameEditForm/)

  assert.match(myPage, /function ProfileAvatar/)
  assert.match(myPage, /function ProfileInfoSection/)
  assert.match(myPage, /function ProfileInfoRow/)
  assert.match(myPage, /function ProfileEditSheet/)
  assert.doesNotMatch(myPage, /function NicknameEditSheet/)
  assert.match(myPage, /function FavoriteShopRow/)
  assert.match(myPage, /function MyReviewRow/)
  assert.match(myPage, /className="my-profile-avatar-stage"/)
  assert.match(myPage, /className="my-profile-avatar-edit-button"/)
  assert.match(myPage, /my-profile-info-section/)
  assert.match(myPage, /const EMPTY_PROFILE_VALUE = '없음'/)
  assert.match(myPage, /닉네임/)
  assert.doesNotMatch(myPage, /상태/)
  assert.doesNotMatch(myPage, /권한/)
  assert.match(myPage, /가입일/)
  assert.match(myPage, /최근 로그인/)
  assert.match(myPage, /프로필 정보 수정/)
  assert.match(myPage, /import \{ Asset, BottomSheet, Button, TextField \} from '@aniwhere\/tds-mobile'/)
  assert.match(myPage, /<BottomSheet/)
  assert.match(myPage, /<TextField/)
  assert.doesNotMatch(myPage, /<TextField[\s\S]{0,500}disabled=\{disabled \|\| isSaving\}/)
  assert.match(myPage, /Asset\.Image/)
  assert.match(myPage, /intro-profile-emoji-options/)
  assert.match(myPage, /frameShape=\{isSelected \? PROFILE_EMOJI_FRAME : PROFILE_EMOJI_RAIL_FRAME\}/)
  assert.match(myPage, /내 관심 매장/)
  assert.match(myPage, /내 리뷰/)
  assert.match(myPage, /더보기/)
  assert.match(myPage, /tab:\s*'review'/)
  assert.match(myPage, /focus:\s*'review'/)
  assert.match(myPage, /reviewId:\s*String\(review\.id\)/)
  assert.match(myPage, /to=\{\{ pathname: '\/explore', search: `\?\$\{reviewSearchParams\.toString\(\)\}` \}\}/)
  assert.match(myPage, /프로필 정보가 변경됐어요/)
  assert.match(myPage, /createProfileEmojiPage\(\{ leadingFilename: profile\?\.emojiIconFilename/)
  assert.match(myPage, /value=\{nicknameInput\}/)
  assert.match(myPage, /onSave: \(nickname: string, emojiIconFilename: string \| null\) => Promise<void>/)
  assert.doesNotMatch(myPage, /my-profile-edit-sheet-backdrop/)
  assert.doesNotMatch(myPage, /my-profile-emoji-grid/)
  assert.doesNotMatch(myPage, /my-profile-emoji-page-dot/)
  assert.doesNotMatch(myPage, /PROFILE_EMOJI_PAGE_COUNT/)
  assert.doesNotMatch(myPage, /USER_STATUS_LABELS/)
  assert.doesNotMatch(myPage, /my-profile-nickname-label/)
  assert.doesNotMatch(myPage, /회원 번호/)
  assert.doesNotMatch(myPage, /사용자 키/)
  assert.doesNotMatch(myPage, /영문 이름/)
  assert.doesNotMatch(myPage, /생년월일/)
  assert.doesNotMatch(myPage, /국적/)
  assert.doesNotMatch(myPage, /휴대폰 번호/)
  assert.doesNotMatch(myPage, /이메일 주소/)
  assert.doesNotMatch(myPage, /집 정보/)
  assert.doesNotMatch(myPage, /회사 정보/)
  assert.doesNotMatch(myPage, /\{session\?\.accessToken\}/)
  assert.doesNotMatch(myPage, /\{session\?\.refreshToken\}/)

  assert.match(styles, /\.my-profile-shell/)
  assert.match(styles, /\.my-profile-avatar-stage/)
  assert.match(styles, /\.my-profile-avatar-edit-button/)
  assert.match(styles, /\.my-profile-edit-sheet/)
  assert.match(styles, /\.my-profile-info-section/)
  assert.match(styles, /\.my-profile-info-row/)
  assert.match(styles, /\.my-profile-info-list > \.my-profile-info-row \+ \.my-profile-info-row/)
  assert.match(styles, /border-bottom:\s*1px solid var\(--ait-color-gray-50\);/)
  assert.match(styles, /\.my-profile-info-label/)
  assert.match(styles, /\.my-profile-info-value/)
  assert.match(styles, /\.my-profile-nickname-form/)
  assert.match(styles, /\.intro-profile-emoji-options/)
  assert.doesNotMatch(styles, /\.my-profile-emoji-page-dot/)
  assert.match(styles, /\.my-profile-list-row/)
  assert.match(styles, /\.my-profile-list-row:any-link/)
  assert.match(styles, /-webkit-tap-highlight-color:\s*transparent;/)
  assert.match(styles, /\.my-profile-list-copy/)
  assert.match(styles, /\.my-profile-list-more-button/)
  assert.match(styles, /\.my-profile-toast/)
  assert.doesNotMatch(styles, /\.my-profile-footer-note/)
  assert.doesNotMatch(styles, /\.my-profile-nickname-label/)
  assert.doesNotMatch(styles, /\.my-profile-summary-grid/)
  assert.doesNotMatch(styles, /\.my-profile-session-card/)
})
