services:
  aniwhere-server:
    build: .
    image: aniwhere-server:latest
    container_name: aniwhere-server
    ports:
      - "61783:8080"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/mtls:/home/ubuntu/mtls:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
